/// {@category 8.0/tizen}
library tizen_interop_8_0.nsd_ssdp;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen nsd-ssdp APIs.
/// {@category 8.0/tizen}
class Tizen80NsdSsdp {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen80NsdSsdp(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen80NsdSsdp.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initializes SSDP.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_OPERATION_FAILED`: Operation failed
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_initialize() {
    return _ssdp_initialize();
  }

  late final _ssdp_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ssdp_initialize');
  late final _ssdp_initialize =
      _ssdp_initializePtr.asFunction<int Function()>();

  /// Deinitializes SSDP.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_deinitialize() {
    return _ssdp_deinitialize();
  }

  late final _ssdp_deinitializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('ssdp_deinitialize');
  late final _ssdp_deinitialize =
      _ssdp_deinitializePtr.asFunction<int Function()>();

  /// Creates a SSDP local service handle.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must release `local_service` using ssdp_destroy_local_service().
  ///
  /// **Parameters:**
  /// - `target` (in): The SSDP local service's target. It may be a device type or a service type specified in UPnP forum (http://upnp.org)
  /// - `local_service` (out): The SSDP local service handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  ///
  /// **Preconditions:**
  /// - This API needs ssdp_initialize() before use.
  ///
  /// **See also:**
  /// - `ssdp_destroy_local_service()`
  int ssdp_create_local_service(
    ffi.Pointer<ffi.Char> target,
    ffi.Pointer<ssdp_service_h> local_service,
  ) {
    return _ssdp_create_local_service(
      target,
      local_service,
    );
  }

  late final _ssdp_create_local_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ssdp_service_h>)>>('ssdp_create_local_service');
  late final _ssdp_create_local_service =
      _ssdp_create_local_servicePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ssdp_service_h>)>();

  /// Destroys the SSDP local service handle.
  ///
  /// You must call ssdp_deregister_local_service() before destroying the local service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Parameters:**
  /// - `local_service` (in): The SSDP local service handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  ///
  /// **See also:**
  /// - `ssdp_create_local_service()`
  int ssdp_destroy_local_service(
    int local_service,
  ) {
    return _ssdp_destroy_local_service(
      local_service,
    );
  }

  late final _ssdp_destroy_local_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ssdp_service_h)>>(
          'ssdp_destroy_local_service');
  late final _ssdp_destroy_local_service =
      _ssdp_destroy_local_servicePtr.asFunction<int Function(int)>();

  /// Sets the USN (Unique Service Name) of SSDP local service. The USN format is specified in UPnP forum (http://upnp.org).
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must pass only unregistered `local_service` created using ssdp_create_local_service().
  /// - If `local_service` is already registered, you cannot set `usn`.
  ///
  /// **Parameters:**
  /// - `local_service` (in): The SSDP local service handle
  /// - `usn` (in): The USN of SSDP local service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_service_set_usn(
    int local_service,
    ffi.Pointer<ffi.Char> usn,
  ) {
    return _ssdp_service_set_usn(
      local_service,
      usn,
    );
  }

  late final _ssdp_service_set_usnPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ssdp_service_h, ffi.Pointer<ffi.Char>)>>('ssdp_service_set_usn');
  late final _ssdp_service_set_usn = _ssdp_service_set_usnPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  /// Sets the URL (Uniform Resource Locator) for description of SSDP local service. See RFC 3986.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must pass only unregistered `local_service` created using ssdp_create_local_service().
  /// - If `local_service` is already registered, you cannot set `url`.
  ///
  /// **Parameters:**
  /// - `local_service` (in): The SSDP local service handle
  /// - `url` (in): The URL of SSDP local service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_service_set_url(
    int local_service,
    ffi.Pointer<ffi.Char> url,
  ) {
    return _ssdp_service_set_url(
      local_service,
      url,
    );
  }

  late final _ssdp_service_set_urlPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ssdp_service_h, ffi.Pointer<ffi.Char>)>>('ssdp_service_set_url');
  late final _ssdp_service_set_url = _ssdp_service_set_urlPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Char>)>();

  /// Gets the target of SSDP service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must release `target` using free().
  ///
  /// **Parameters:**
  /// - `service` (in): The SSDP service handle
  /// - `target` (out): The target of SSDP service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_service_get_target(
    int service,
    ffi.Pointer<ffi.Pointer<ffi.Char>> target,
  ) {
    return _ssdp_service_get_target(
      service,
      target,
    );
  }

  late final _ssdp_service_get_targetPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ssdp_service_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('ssdp_service_get_target');
  late final _ssdp_service_get_target = _ssdp_service_get_targetPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the USN of SSDP service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must release `usn` using free().
  ///
  /// **Parameters:**
  /// - `service` (in): The SSDP service handle
  /// - `usn` (out): The USN of SSDP service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_service_get_usn(
    int service,
    ffi.Pointer<ffi.Pointer<ffi.Char>> usn,
  ) {
    return _ssdp_service_get_usn(
      service,
      usn,
    );
  }

  late final _ssdp_service_get_usnPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ssdp_service_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('ssdp_service_get_usn');
  late final _ssdp_service_get_usn = _ssdp_service_get_usnPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the URL of SSDP service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must release `url` using free().
  ///
  /// **Parameters:**
  /// - `service` (in): The SSDP service handle
  /// - `url` (out): The URL of SSDP service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_service_get_url(
    int service,
    ffi.Pointer<ffi.Pointer<ffi.Char>> url,
  ) {
    return _ssdp_service_get_url(
      service,
      url,
    );
  }

  late final _ssdp_service_get_urlPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ssdp_service_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('ssdp_service_get_url');
  late final _ssdp_service_get_url = _ssdp_service_get_urlPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Registers the SSDP local service for publishing.
  ///
  /// You must set a USN and a URL of the local service before ssdp_register_local_service() is called.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/internet>
  ///
  /// **Remarks:**
  /// - You must pass only local_service created using ssdp_create_local_service().
  ///
  /// **Parameters:**
  /// - `local_service` (in): The SSDP local service handle
  /// - `registered_cb` (in): The callback function to be called
  /// - `user_data` (in): The user data passed to the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OPERATION_FAILED`: Operation failed
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SSDP_ERROR_SERVICE_ALREADY_REGISTERED`: Service already registered
  /// - `SSDP_ERROR_PERMISSION_DENIED`: Permission Denied
  ///
  /// **Preconditions:**
  /// - This API needs ssdp_service_set_usn() and ssdp_service_set_url() before use.
  int ssdp_register_local_service(
    int local_service,
    ssdp_registered_cb registered_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _ssdp_register_local_service(
      local_service,
      registered_cb,
      user_data,
    );
  }

  late final _ssdp_register_local_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ssdp_service_h, ssdp_registered_cb,
              ffi.Pointer<ffi.Void>)>>('ssdp_register_local_service');
  late final _ssdp_register_local_service =
      _ssdp_register_local_servicePtr.asFunction<
          int Function(int, ssdp_registered_cb, ffi.Pointer<ffi.Void>)>();

  /// Deregisters the SSDP local service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Remarks:**
  /// - You must pass only local_service created using ssdp_create_local_service().
  ///
  /// **Parameters:**
  /// - `local_service` (in): The SSDP local service handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_deregister_local_service(
    int local_service,
  ) {
    return _ssdp_deregister_local_service(
      local_service,
    );
  }

  late final _ssdp_deregister_local_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ssdp_service_h)>>(
          'ssdp_deregister_local_service');
  late final _ssdp_deregister_local_service =
      _ssdp_deregister_local_servicePtr.asFunction<int Function(int)>();

  /// Starts browsing the SSDP remote service.
  ///
  /// ssdp_start_browsing_service() keeps browsing services until calling ssdp_stop_browsing_service().
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/internet>
  ///
  /// **Parameters:**
  /// - `target` (in): The target to browse
  /// - `ssdp_browser` (out): The SSDP browser handle
  /// - `found_cb` (in): The callback function to be called
  /// - `user_data` (in): The user data passed to the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_OPERATION_FAILED`: Operation failed
  /// - `SSDP_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SSDP_ERROR_PERMISSION_DENIED`: Permission Denied
  int ssdp_start_browsing_service(
    ffi.Pointer<ffi.Char> target,
    ffi.Pointer<ssdp_browser_h> ssdp_browser,
    ssdp_found_cb found_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _ssdp_start_browsing_service(
      target,
      ssdp_browser,
      found_cb,
      user_data,
    );
  }

  late final _ssdp_start_browsing_servicePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ssdp_browser_h>,
              ssdp_found_cb,
              ffi.Pointer<ffi.Void>)>>('ssdp_start_browsing_service');
  late final _ssdp_start_browsing_service =
      _ssdp_start_browsing_servicePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ssdp_browser_h>,
              ssdp_found_cb, ffi.Pointer<ffi.Void>)>();

  /// Stops browsing the SSDP remote service.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Parameters:**
  /// - `ssdp_browser` (in): The SSDP browser handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise negative error value
  ///
  /// **Return values:**
  /// - `SSDP_ERROR_NONE`: Successful
  /// - `SSDP_ERROR_NOT_INITIALIZED`: Not initialized
  /// - `SSDP_ERROR_SERVICE_NOT_FOUND`: Service not found
  /// - `SSDP_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SSDP_ERROR_NOT_SUPPORTED`: Not supported
  int ssdp_stop_browsing_service(
    int ssdp_browser,
  ) {
    return _ssdp_stop_browsing_service(
      ssdp_browser,
    );
  }

  late final _ssdp_stop_browsing_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ssdp_browser_h)>>(
          'ssdp_stop_browsing_service');
  late final _ssdp_stop_browsing_service =
      _ssdp_stop_browsing_servicePtr.asFunction<int Function(int)>();
}

/// Enumeration for Network Service Discovery SSDP error code.
///
/// **Since Tizen:**
/// - 3.0
/// @nodoc
abstract class ssdp_error_e {
  /// < Successful
  static const int SSDP_ERROR_NONE = 0;

  /// < Out of memory
  static const int SSDP_ERROR_OUT_OF_MEMORY = -12;

  /// < Permission denied
  static const int SSDP_ERROR_PERMISSION_DENIED = -13;

  /// < Invalid function parameter
  static const int SSDP_ERROR_INVALID_PARAMETER = -22;

  /// < Not supported
  static const int SSDP_ERROR_NOT_SUPPORTED = -1073741822;

  /// < Not initialized
  static const int SSDP_ERROR_NOT_INITIALIZED = -29949951;

  /// < Operation failed
  static const int SSDP_ERROR_OPERATION_FAILED = -29949948;

  /// < Service not found
  static const int SSDP_ERROR_SERVICE_NOT_FOUND = -29949947;

  /// < Service already registered
  static const int SSDP_ERROR_SERVICE_ALREADY_REGISTERED = -29949946;
}

/// Enumeration for Network Service Discovery SSDP service browse state.
///
/// **Since Tizen:**
/// - 3.0
/// @nodoc
abstract class ssdp_service_state_e {
  /// < A new service is available
  static const int SSDP_SERVICE_STATE_AVAILABLE = 0;

  /// < A service is not available
  static const int SSDP_SERVICE_STATE_UNAVAILABLE = 1;
}

/// The SSDP service handle.
///
/// **Since Tizen:**
/// - 3.0
/// @nodoc
typedef ssdp_service_h = ffi.UnsignedInt;
/// @nodoc
typedef Dartssdp_service_h = int;

/// Called when the registration of SSDP service is finished.
///
/// **Since Tizen:**
/// - 3.0
///
/// **Parameters:**
/// - `result` (in): The result of registration
/// - `ssdp_local_service` (in): The SSDP local service handle
/// - `user_data` (in): The user data passed from the request function
///
/// **See also:**
/// - `ssdp_register_local_service()`
/// @nodoc
typedef ssdp_registered_cb
    = ffi.Pointer<ffi.NativeFunction<ssdp_registered_cbFunction>>;
/// @nodoc
typedef ssdp_registered_cbFunction = ffi.Void Function(ffi.Int32 result,
    ssdp_service_h ssdp_local_service, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartssdp_registered_cbFunction = void Function(int result,
    Dartssdp_service_h ssdp_local_service, ffi.Pointer<ffi.Void> user_data);

/// The SSDP browser handle.
///
/// **Since Tizen:**
/// - 3.0
/// @nodoc
typedef ssdp_browser_h = ffi.UnsignedInt;
/// @nodoc
typedef Dartssdp_browser_h = int;

/// Called when a service has become available or unavailable.
///
/// **Since Tizen:**
/// - 3.0
///
/// **Parameters:**
/// - `state` (in): The state of found service
/// - `ssdp_service` (in): The SSDP remote service handle
/// - `user_data` (in): The user data passed from the request function
///
/// **See also:**
/// - `ssdp_start_browsing_service()`
/// @nodoc
typedef ssdp_found_cb = ffi.Pointer<ffi.NativeFunction<ssdp_found_cbFunction>>;
/// @nodoc
typedef ssdp_found_cbFunction = ffi.Void Function(ffi.Int32 state,
    ssdp_service_h ssdp_remote_service, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartssdp_found_cbFunction = void Function(int state,
    Dartssdp_service_h ssdp_remote_service, ffi.Pointer<ffi.Void> user_data);
