preamble: |
  // Copyright 2022 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.

  // ignore_for_file: camel_case_types, non_constant_identifier_names
  // ignore_for_file: unused_element, unused_field

name: 'Tizen65Native'
description: 'Dart bindings for Tizen native APIs.'
output: 'lib/src/bindings/6.5/generated_bindings.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'configs/6.5/entrypoints.h'
  include-directives:
    - '**/account.h'
    - '**/autofill_common.h'
    - '**/autofill.h'
    - '**/autofill_manager.h'
    - '**/autofill_service.h'
    - '**/bundle.h'
    - '**/diagnostics.h'
    - '**/fido.h'
    - '**/fido_uaf_authenticator.h'
    - '**/fido_uaf_client.h'
    - '**/inputmethod.h'
    - '**/inputmethod_manager.h'
    - '**/multi_assistant_common.h'
    - '**/multi_assistant.h'
    - '**/oauth2.h'
    - '**/peripheral_io.h'
    - '**/privilege_information.h'
    - '**/push-service.h'
    - '**/stte.h'
    - '**/stt.h'
    - '**/sync_adapter.h'
    - '**/sync_manager.h'
    - '**/tbm_surface.h'
    - '**/tizen_error.h'
    - '**/tizen.h'
    - '**/trace.h'
    - '**/ttse.h'
    - '**/tts.h'
    - '**/usb_host.h'
    - '**/vce.h'
    - '**/voice_control.h'
    - '**/voice_control_manager.h'
    - '**/vpn_service.h'
    - '**/appcore-agent/*.h'
    - '**/appfw/*.h'
    - '**/asp/*.h'
    - '**/badge/*.h'
    - '**/calendar-service2/*.h'
    - '**/cbhm/*.h'
    - '**/cion/*.h'
    - '**/ckm/ckmc/*.h'
    - '**/contacts-svc/*.h'
    - '**/content/*.h'
    - '**/context-service/*.h'
    - '**/csr/*.h'
    - '**/device/*.h'
    - '**/device-certificate-manager/*.h'
    - '**/dlog/*.h'
    - '**/dpm/*.h'
    - '**/eom/*.h'
    - '**/feedback/*.h'
    - '**/geofence/*.h'
    - '**/iotcon/*.h'
    - '**/location/*.h'
    - '**/media/*.h'
    - '**/media-content/*.h'
    - '**/messaging/*.h'
    - '**/metadata-editor/*.h'
    - '**/network/*.h'
    - '**/nnstreamer/*.h'
    - '**/nntrainer/*.h'
    - '**/notification/*.h'
    - '**/notification-ex/api/*.h'
    - '**/nsd/*.h'
    - '**/phonenumber-utils/*.h'
    - '**/privacy-privilege-manager/*.h'
    - '**/rpc-port/*.h'
    - '**/sensor/*.h'
    - '**/shortcut/*.h'
    - '**/storage/*.h'
    - '**/system/*.h'
    - '**/web/*.h'
    - '**/wifi-direct/*.h'
    - '**/yaca/*.h'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.5/usr/include/'
  - '-I./rootstraps/6.5/usr/include/appcore-agent/'
  - '-I./rootstraps/6.5/usr/include/appfw/'
  - '-I./rootstraps/6.5/usr/include/asp/'
  - '-I./rootstraps/6.5/usr/include/badge/'
  - '-I./rootstraps/6.5/usr/include/calendar-service2/'
  - '-I./rootstraps/6.5/usr/include/cbhm/'
  - '-I./rootstraps/6.5/usr/include/cion/'
  - '-I./rootstraps/6.5/usr/include/ckm/'
  - '-I./rootstraps/6.5/usr/include/contacts-svc/'
  - '-I./rootstraps/6.5/usr/include/content/'
  - '-I./rootstraps/6.5/usr/include/context-service/'
  - '-I./rootstraps/6.5/usr/include/csr/'
  - '-I./rootstraps/6.5/usr/include/device-certificate-manager/'
  - '-I./rootstraps/6.5/usr/include/dlog/'
  - '-I./rootstraps/6.5/usr/include/eom/'
  - '-I./rootstraps/6.5/usr/include/feedback/'
  - '-I./rootstraps/6.5/usr/include/geofence/'
  - '-I./rootstraps/6.5/usr/include/iotcon/'
  - '-I./rootstraps/6.5/usr/include/location/'
  - '-I./rootstraps/6.5/usr/include/media/'
  - '-I./rootstraps/6.5/usr/include/media-content/'
  - '-I./rootstraps/6.5/usr/include/messaging/'
  - '-I./rootstraps/6.5/usr/include/metadata-editor/'
  - '-I./rootstraps/6.5/usr/include/network/'
  - '-I./rootstraps/6.5/usr/include/nnstreamer/'
  - '-I./rootstraps/6.5/usr/include/nntrainer/'
  - '-I./rootstraps/6.5/usr/include/notification/'
  - '-I./rootstraps/6.5/usr/include/notification-ex/api/'
  - '-I./rootstraps/6.5/usr/include/nsd/'
  - '-I./rootstraps/6.5/usr/include/phonenumber-utils/'
  - '-I./rootstraps/6.5/usr/include/privacy-privilege-manager/'
  - '-I./rootstraps/6.5/usr/include/rpc-port/'
  - '-I./rootstraps/6.5/usr/include/sensor/'
  - '-I./rootstraps/6.5/usr/include/shortcut/'
  - '-I./rootstraps/6.5/usr/include/storage/'
  - '-I./rootstraps/6.5/usr/include/system/'
  - '-I./rootstraps/6.5/usr/include/web/'
  - '-I./rootstraps/6.5/usr/include/wifi-direct/'
  - '-I./rootstraps/6.5/usr/include/yaca/'

  # include EFL directories
  - '-I./rootstraps/6.5/usr/include/ecore-imf-1/'
  - '-I./rootstraps/6.5/usr/include/efl-1/'
  - '-I./rootstraps/6.5/usr/include/eina-1/'
  - '-I./rootstraps/6.5/usr/include/eina-1/eina/'
  - '-I./rootstraps/6.5/usr/include/emile-1/'
  - '-I./rootstraps/6.5/usr/include/eo-1/'
  - '-I./rootstraps/6.5/usr/include/evas-1/'

  # include glib directories
  - '-I./rootstraps/6.5/usr/include/glib-2.0/'
  - '-I./rootstraps/6.5/usr/lib/glib-2.0/include/'

enums:
  rename:
    '_+(.*)': '$1'
