name: tizen_interop_example
description: Demonstrates how to use the tizen_interop plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_interop:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
