// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:symgen`.

const Map<String, List<String>> capiSystemSystemSettingsSymbols = {
  'libcapi-system-system-settings.so.0': [
    'system_settings_add_changed_cb',
    'system_settings_add_value_string',
    'system_settings_delete_value_string',
    'system_settings_foreach_value_string',
    'system_settings_get_value_bool',
    'system_settings_get_value_int',
    'system_settings_get_value_string',
    'system_settings_remove_changed_cb',
    'system_settings_set_changed_cb',
    'system_settings_set_value_bool',
    'system_settings_set_value_int',
    'system_settings_set_value_string',
    'system_settings_unset_changed_cb',
  ],
};
