// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:symgen`.

final Map<String, List<String>> cbhmSymbols = {
  'libcbhm.so.1': [
    'cbhm_close_service',
    'cbhm_hide',
    'cbhm_item_changed_callback_add',
    'cbhm_item_changed_callback_remove',
    'cbhm_item_count_get',
    'cbhm_item_selected_callback_add',
    'cbhm_item_selected_callback_remove',
    'cbhm_latest_item_type_get',
    'cbhml_changed_cb_hash_deinit',
    'cbhml_changed_cb_hash_init',
    'cbhml_changed_cb_table_get',
    'cbhml_monitor_cb_hash_deinit',
    'cbhml_monitor_cb_hash_init',
    'cbhml_monitor_cb_table_get',
    'cbhml_selection_handler_deinit',
    'cbhml_selection_handler_init',
    'cbhml_selection_hash_deinit',
    'cbhml_selection_hash_init',
    'cbhml_selection_obj_table_get',
    'cbhm_monitor_callback_add',
    'cbhm_monitor_callback_remove',
    'cbhm_open_service',
    'cbhm_selection_get',
    'cbhm_selection_set',
    'cbhm_selection_type_get',
    'cbhm_selection_type_set',
    'cbhm_show',
    'cbhm_state_get',
    'cbhm_utils_calloc',
    'cbhm_utils_free',
    'cbhm_utils_malloc',
  ],
};
