name: 'Tizen40Wearable'
output: 'lib/src/bindings/4.0/wearable/generated_bindings.dart'
llvm-path:
  - '/usr/lib/llvm-12'
headers:
  entry-points:
    - 'configs/4.0/wearable/entrypoints.h'
  include-directives:
    - '**/tizen*.h'
    - '**/account*.h'
    - '**/fido*.h'
    - '**/oauth2*.h'
    - '**/sync*.h'
    - '**/appfw/*.h'
    - '**/badge/*.h'
    - '**/appcore-agent/*.h'
    - '**/appcore-watch/*.h'
    - '**/widget-service/*.h'
    - '**/widget_viewer_evas/*.h'
    - '**/content/*.h'
    - '**/media-content/*.h'
    - '**/context-service/*.h'
    - '**/location/*.h'
    - '**/maps/*.h'
    - '**/messaging/*.h'
    - '**/push-service.h'
    - '**/media/*.h'
    - '**/metadata-editor/*.h'
    - '**/asp/*.h'
    - '**/network/*.h'
    - '**/nsd/*.h'
    - '**/iotcon/*.h'
    - '**/smartcard.h'
    - '**/csr/*.h'
    - '**/dpm/*.h'
    - '**/ckmc/*.h'
    - '**/privacy-privilege-manager/*.h'
    - '**/privilege_information.h'
    - '**/yaca/*.h'
    - '**/calendar-service2/*.h'
    - '**/contacts-svc/*.h'
    - '**/phonenumber-utils/*.h'
    - '**/device/*.h'
    - '**/dlog/*.h'
    - '**/feedback/*.h'
    - '**/system/*.h'
    - '**/sensor/*.h'
    - '**/storage/*.h'
    - '**/trace.h'
    - '**/telephony/*.h'
    - '**/inputmethod*.h'
    - '**/stt*.h'
    - '**/tts*.h'
    - '**/voice_control*.h'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/appfw/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/notification/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/badge/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/appcore-agent/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/appcore-watch/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/widget_service/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/widget_viewer_evas/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/content/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/media-content/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/context-service/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/location/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/maps/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/messaging/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/media/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/metadata-editor/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/asp/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/network/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/nsd/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/iotcon/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/csr/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/ckm/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/privacy-privilege-manager/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/yaca/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/calendar-service2/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/contacts-svc/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/phonenumber-utils/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/dlog/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/feedback/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/system/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/sensor/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/storage/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/telephony/'

# include efl directories
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/evas-1/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/efl-1/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/eo-1/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/eina-1/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/eina-1/eina/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/emile-1/'
  - '-I./rootstraps/wearable-4.0-device.core/usr/include/ecore-imf-1/'

dart-bool: true

typedef-map:
   'size_t': 'Int32'

preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
