/// {@category 6.5/tizen}
library tizen_interop_6_5.mv_inference;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_mv_common.dart' as mv_common;

/// Dart bindings for Tizen mv_inference APIs.
/// {@category 6.5/tizen}
class Tizen65MvInference {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen65MvInference(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen65MvInference.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// / /**
  ///
  /// Creates inference handle.
  ///
  /// Use this function to create an inference. After the creation the inference has to be prepared with mv_inference_prepare() function to prepare a network for the inference.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Remarks:**
  /// - If the app sets `MV_INFERENCE_MODEL_CONFIGURATION_FILE_PATH`,
  /// - `MV_INFERENCE_MODEL_WEIGHT_FILE_PATH`, and `MV_INFERENCE_MODEL_USER_FILE_PATH`
  /// - to media storage, then the media storage privilege
  /// - <http://tizen.org/privilege/mediastorage is needed.>
  /// - If the app sets any of the paths mentioned in the previous sentence
  /// - to external storage, then the external storage privilege
  /// - <http://tizen.org/privilege/externalstorage is needed.>
  /// - If the required privileges aren't set properly, mv_inference_prepare() will returned
  /// - `MEDIA_VISION_ERROR_PERMISSION_DENIED`.
  /// - The `infer` should be released using mv_inference_destroy().
  ///
  /// **Parameters:**
  /// - `infer` (out): The handle to the inference to be created
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_OUT_OF_MEMORY`: Out of memory
  ///
  /// **See also:**
  /// - `mv_inference_destroy()`
  /// - `mv_inference_prepare()`
  int mv_inference_create(
    ffi.Pointer<mv_inference_h> infer,
  ) {
    return _mv_inference_create(
      infer,
    );
  }

  late final _mv_inference_createPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<mv_inference_h>)>>(
      'mv_inference_create');
  late final _mv_inference_create = _mv_inference_createPtr
      .asFunction<int Function(ffi.Pointer<mv_inference_h>)>();

  /// Destroys inference handle and releases all its resources.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Parameters:**
  /// - `infer` (in): The handle to the inference to be destroyed
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - Create inference handle by using mv_inference_create()
  ///
  /// **See also:**
  /// - `mv_inference_create()`
  int mv_inference_destroy(
    mv_inference_h infer,
  ) {
    return _mv_inference_destroy(
      infer,
    );
  }

  late final _mv_inference_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mv_inference_h)>>(
          'mv_inference_destroy');
  late final _mv_inference_destroy =
      _mv_inference_destroyPtr.asFunction<int Function(mv_inference_h)>();

  /// Configures the network of the inference.
  ///
  /// Use this function to configure the network of the inference which is set to `engine_config`.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Parameters:**
  /// - `infer` (in): The handle to the inference
  /// - `engine_config` (in): The handle to the configuration of engine.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter in `engine_config`
  /// - `MEDIA_VISION_ERROR_INVALID_PATH`: Invalid path of model data in `engine_config`
  int mv_inference_configure(
    mv_inference_h infer,
    mv_common.mv_engine_config_h engine_config,
  ) {
    return _mv_inference_configure(
      infer,
      engine_config,
    );
  }

  late final _mv_inference_configurePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_inference_h,
              mv_common.mv_engine_config_h)>>('mv_inference_configure');
  late final _mv_inference_configure = _mv_inference_configurePtr
      .asFunction<int Function(mv_inference_h, mv_common.mv_engine_config_h)>();

  /// Prepares inference.
  ///
  /// Use this function to prepare inference based on the configured network.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Parameters:**
  /// - `infer` (in): The handle to the inference
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INVALID_DATA`: Invalid model data
  /// - `MEDIA_VISION_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `MEDIA_VISION_ERROR_INVALID_OPERATION`: Invalid operation
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Not supported format
  int mv_inference_prepare(
    mv_inference_h infer,
  ) {
    return _mv_inference_prepare(
      infer,
    );
  }

  late final _mv_inference_preparePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mv_inference_h)>>(
          'mv_inference_prepare');
  late final _mv_inference_prepare =
      _mv_inference_preparePtr.asFunction<int Function(mv_inference_h)>();

  /// Traverses the list of supported engines for inference.
  ///
  /// Using this function the supported engines can be obtained. The names can be used with `mv_engine_config_h` related getters and setters to get/set MV_INFERENCE_BACKEND_TYPE attribute value.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Parameters:**
  /// - `infer` (in): The handle to the inference
  /// - `callback` (in): The iteration callback function
  /// - `user_data` (in): The user data to be passed to the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **See also:**
  /// - `mv_inference_supported_engine_cb()`
  int mv_inference_foreach_supported_engine(
    mv_inference_h infer,
    mv_inference_supported_engine_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_foreach_supported_engine(
      infer,
      callback,
      user_data,
    );
  }

  late final _mv_inference_foreach_supported_enginePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_inference_h, mv_inference_supported_engine_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_foreach_supported_engine');
  late final _mv_inference_foreach_supported_engine =
      _mv_inference_foreach_supported_enginePtr.asFunction<
          int Function(mv_inference_h, mv_inference_supported_engine_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Performs image classification on the `source`.
  ///
  /// Use this function to launch image classification. Each time when mv_inference_image_classify() is called, `classified_cb` will receive classes which the media source may belong to.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Remarks:**
  /// - This function is synchronous and may take considerable time to run.
  ///
  /// **Parameters:**
  /// - `source` (in): The handle to the source of the media
  /// - `infer` (in): The handle to the inference
  /// - `roi` (in): Rectangular area in the `source` which will be analyzed. If NULL, then the whole source will be analyzed.
  /// - `classified_cb` (in): The callback which will be called for classification on `source`. This callback will receive classification results.
  /// - `user_data` (in): The user data passed from the code where mv_inference_image_classify() is invoked. This data will be accessible in `classified_cb` callback.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INVALID_OPERATION`: Invalid operation
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Source colorspace isn't supported
  ///
  /// **Preconditions:**
  /// - Create a source handle by calling mv_create_source()
  /// - Create an inference handle by calling mv_inference_create()
  /// - Configure an inference handle by calling mv_inference_configure()
  /// - Prepare an inference by calling mv_inference_prepare()
  ///
  /// **Postconditions:**
  /// - `classified_cb` will be called to provide classification results
  ///
  /// **See also:**
  /// - `mv_inference_image_classified_cb()`
  int mv_inference_image_classify(
    mv_common.mv_source_h source,
    mv_inference_h infer,
    ffi.Pointer<mv_common.mv_rectangle_s> roi,
    mv_inference_image_classified_cb classified_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_image_classify(
      source,
      infer,
      roi,
      classified_cb,
      user_data,
    );
  }

  late final _mv_inference_image_classifyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_image_classified_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_image_classify');
  late final _mv_inference_image_classify =
      _mv_inference_image_classifyPtr.asFunction<
          int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_image_classified_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Performs object detection on the `source`.
  ///
  /// Use this function to launch object detection. Each time when mv_inference_object_detect() is called, `detected_cb` will receive a list of objects and their locations in the media source.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Remarks:**
  /// - This function is synchronous and may take considerable time to run.
  ///
  /// **Parameters:**
  /// - `source` (in): The handle to the source of the media
  /// - `infer` (in): The handle to the inference
  /// - `detected_cb` (in): The callback which will be called for detecting objects in the media source. This callback will receive the detection results.
  /// - `user_data` (in): The user data passed from the code where mv_inference_object_detect() is invoked. This data will be accessible in `detected_cb` callback.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Source colorspace isn't supported
  ///
  /// **Preconditions:**
  /// - Create a source handle by calling mv_create_source()
  /// - Create an inference handle by calling mv_inference_create()
  /// - Configure an inference handle by calling mv_inference_configure()
  /// - Prepare an inference by calling mv_inference_prepare()
  ///
  /// **Postconditions:**
  /// - `detected_cb` will be called to provide detection results
  ///
  /// **See also:**
  /// - `mv_inference_object_detected_cb()`
  int mv_inference_object_detect(
    mv_common.mv_source_h source,
    mv_inference_h infer,
    mv_inference_object_detected_cb detected_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_object_detect(
      source,
      infer,
      detected_cb,
      user_data,
    );
  }

  late final _mv_inference_object_detectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              mv_inference_object_detected_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_object_detect');
  late final _mv_inference_object_detect =
      _mv_inference_object_detectPtr.asFunction<
          int Function(mv_common.mv_source_h, mv_inference_h,
              mv_inference_object_detected_cb, ffi.Pointer<ffi.Void>)>();

  /// Performs face detection on the `source`.
  ///
  /// Use this function to launch face detection. Each time when mv_inference_face_detect() is called, `detected_cb` will receive a list of faces and their locations in the media source.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Remarks:**
  /// - This function is synchronous and may take considerable time to run.
  ///
  /// **Parameters:**
  /// - `source` (in): The handle to the source of the media
  /// - `infer` (in): The handle to the inference
  /// - `detected_cb` (in): The callback which will be called for detecting faces on media source. This callback will receive the detection results.
  /// - `user_data` (in): The user data passed from the code where mv_inference_face_detect() is invoked. This data will be accessible in `detected_cb` callback.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Source colorspace isn't supported
  ///
  /// **Preconditions:**
  /// - Create a source handle by calling mv_create_source()
  /// - Create an inference handle by calling mv_inference_create()
  /// - Configure an inference handle by calling mv_inference_configure()
  /// - Prepare an inference by calling mv_inference_prepare()
  ///
  /// **Postconditions:**
  /// - `detected_cb` will be called to provide detection results
  ///
  /// **See also:**
  /// - `mv_inference_face_detected_cb()`
  int mv_inference_face_detect(
    mv_common.mv_source_h source,
    mv_inference_h infer,
    mv_inference_face_detected_cb detected_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_face_detect(
      source,
      infer,
      detected_cb,
      user_data,
    );
  }

  late final _mv_inference_face_detectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              mv_inference_face_detected_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_face_detect');
  late final _mv_inference_face_detect =
      _mv_inference_face_detectPtr.asFunction<
          int Function(mv_common.mv_source_h, mv_inference_h,
              mv_inference_face_detected_cb, ffi.Pointer<ffi.Void>)>();

  /// Performs facial landmarks detection on the `source`.
  ///
  /// Use this function to launch facial landmark detection. Each time when mv_inference_facial_landmark_detect() is called, `detected_cb` will receive a list facial landmark's locations in the media source.
  ///
  /// **Since Tizen:**
  /// - 5.5
  ///
  /// **Remarks:**
  /// - This function is synchronous and may take considerable time to run.
  ///
  /// **Parameters:**
  /// - `source` (in): The handle to the source of the media
  /// - `infer` (in): The handle to the inference
  /// - `roi` (in): Rectangular area including a face in `source` which will be analyzed. If NULL, then the whole source will be analyzed.
  /// - `detected_cb` (in): The callback which will receive the detection results.
  /// - `user_data` (in): The user data passed from the code where mv_inference_facial_landmark_detect() is invoked. This data will be accessible in `detected_cb` callback.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Source colorspace isn't supported
  ///
  /// **Preconditions:**
  /// - Create a source handle by calling mv_create_source()
  /// - Create an inference handle by calling mv_inference_create()
  /// - Configure an inference handle by calling mv_inference_configure()
  /// - Prepare an inference by calling mv_inference_prepare()
  ///
  /// **Postconditions:**
  /// - `detected_cb` will be called to provide detection results
  ///
  /// **See also:**
  /// - `mv_inference_facial_landmark_detected_cb()`
  int mv_inference_facial_landmark_detect(
    mv_common.mv_source_h source,
    mv_inference_h infer,
    ffi.Pointer<mv_common.mv_rectangle_s> roi,
    mv_inference_facial_landmark_detected_cb detected_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_facial_landmark_detect(
      source,
      infer,
      roi,
      detected_cb,
      user_data,
    );
  }

  late final _mv_inference_facial_landmark_detectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_facial_landmark_detected_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_facial_landmark_detect');
  late final _mv_inference_facial_landmark_detect =
      _mv_inference_facial_landmark_detectPtr.asFunction<
          int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_facial_landmark_detected_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Performs pose landmarks detection on the `source`.
  ///
  /// Use this function to launch pose landmark detection. Each time when mv_inference_pose_landmark_detect() is called, `detected_cb` will receive a list of pose landmark's locations in the media source.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Remarks:**
  /// - This function is synchronous and may take considerable time to run.
  ///
  /// **Parameters:**
  /// - `source` (in): The handle to the source of the media
  /// - `infer` (in): The handle to the inference
  /// - `roi` (in): Rectangular area including a face in `source` which will be analyzed. If NULL, then the whole source will be analyzed.
  /// - `detected_cb` (in): The callback which will receive the detection results.
  /// - `user_data` (in): The user data passed from the code where mv_inference_pose_landmark_detect() is invoked. This data will be accessible in `detected_cb` callback.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT`: Source colorspace isn't supported
  ///
  /// **Preconditions:**
  /// - Create a source handle by calling mv_create_source()
  /// - Create an inference handle by calling mv_inference_create()
  /// - Configure an inference handle by calling mv_inference_configure()
  /// - Prepare an inference by calling mv_inference_prepare()
  ///
  /// **Postconditions:**
  /// - `detected_cb` will be called to provide detection results
  ///
  /// **See also:**
  /// - `mv_inference_pose_landmark_detected_cb()`
  int mv_inference_pose_landmark_detect(
    mv_common.mv_source_h source,
    mv_inference_h infer,
    ffi.Pointer<mv_common.mv_rectangle_s> roi,
    mv_inference_pose_landmark_detected_cb detected_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_inference_pose_landmark_detect(
      source,
      infer,
      roi,
      detected_cb,
      user_data,
    );
  }

  late final _mv_inference_pose_landmark_detectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_pose_landmark_detected_cb,
              ffi.Pointer<ffi.Void>)>>('mv_inference_pose_landmark_detect');
  late final _mv_inference_pose_landmark_detect =
      _mv_inference_pose_landmark_detectPtr.asFunction<
          int Function(
              mv_common.mv_source_h,
              mv_inference_h,
              ffi.Pointer<mv_common.mv_rectangle_s>,
              mv_inference_pose_landmark_detected_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Gets the number of poses.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Parameters:**
  /// - `result` (in): The handle to inference result
  /// - `number_of_poses` (out): The pointer to the number of poses
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **See also:**
  /// - `mv_inference_pose_landmark_detected_cb()`
  /// - `mv_inference_pose_result_h`
  int mv_inference_pose_get_number_of_poses(
    mv_inference_pose_result_h result,
    ffi.Pointer<ffi.Int> number_of_poses,
  ) {
    return _mv_inference_pose_get_number_of_poses(
      result,
      number_of_poses,
    );
  }

  late final _mv_inference_pose_get_number_of_posesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_inference_pose_result_h,
              ffi.Pointer<ffi.Int>)>>('mv_inference_pose_get_number_of_poses');
  late final _mv_inference_pose_get_number_of_poses =
      _mv_inference_pose_get_number_of_posesPtr.asFunction<
          int Function(mv_inference_pose_result_h, ffi.Pointer<ffi.Int>)>();

  /// Gets the number of landmarks per a pose.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Parameters:**
  /// - `result` (in): The handle to inference result
  /// - `number_of_landmarks` (out): The pointer to the number of landmarks
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **See also:**
  /// - `mv_inference_pose_landmark_detected_cb()`
  /// - `mv_inference_pose_result_h`
  int mv_inference_pose_get_number_of_landmarks(
    mv_inference_pose_result_h result,
    ffi.Pointer<ffi.Int> number_of_landmarks,
  ) {
    return _mv_inference_pose_get_number_of_landmarks(
      result,
      number_of_landmarks,
    );
  }

  late final _mv_inference_pose_get_number_of_landmarksPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  mv_inference_pose_result_h, ffi.Pointer<ffi.Int>)>>(
      'mv_inference_pose_get_number_of_landmarks');
  late final _mv_inference_pose_get_number_of_landmarks =
      _mv_inference_pose_get_number_of_landmarksPtr.asFunction<
          int Function(mv_inference_pose_result_h, ffi.Pointer<ffi.Int>)>();

  /// Gets landmark location of a part of a pose.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Parameters:**
  /// - `result` (in): The handle to inference result
  /// - `pose_index` (in): The pose index between 0 and the number of poses which can be gotten by mv_inference_pose_get_number_of_poses()
  /// - `pose_part` (in): The landmark index between 0 and the number of landmarks which can be gotten by mv_inference_pose_get_number_of_landmarks()
  /// - `location` (out): The location of a landmark
  /// - `score` (out): The score of a landmark
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **See also:**
  /// - `mv_inference_pose_get_number_of_poses()`
  /// - `mv_inference_pose_get_number_of_landmarks()`
  /// - `mv_inference_pose_landmark_detected_cb()`
  /// - `mv_inference_pose_result_h`
  int mv_inference_pose_get_landmark(
    mv_inference_pose_result_h result,
    int pose_index,
    int pose_part,
    ffi.Pointer<mv_common.mv_point_s> location,
    ffi.Pointer<ffi.Float> score,
  ) {
    return _mv_inference_pose_get_landmark(
      result,
      pose_index,
      pose_part,
      location,
      score,
    );
  }

  late final _mv_inference_pose_get_landmarkPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_inference_pose_result_h,
              ffi.Int,
              ffi.Int,
              ffi.Pointer<mv_common.mv_point_s>,
              ffi.Pointer<ffi.Float>)>>('mv_inference_pose_get_landmark');
  late final _mv_inference_pose_get_landmark =
      _mv_inference_pose_get_landmarkPtr.asFunction<
          int Function(mv_inference_pose_result_h, int, int,
              ffi.Pointer<mv_common.mv_point_s>, ffi.Pointer<ffi.Float>)>();

  /// Gets a label of a pose.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Parameters:**
  /// - `result` (in): The handle to inference result
  /// - `pose_index` (in): The pose index between 0 and the number of poses which can be gotten by mv_inference_pose_get_number_of_poses()
  /// - `label` (out): The label of a pose
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **See also:**
  /// - `mv_inference_pose_get_number_of_poses()`
  /// - `mv_inference_pose_get_number_of_landmarks()`
  /// - `mv_inference_pose_landmark_detected_cb()`
  /// - `mv_inference_pose_result_h`
  int mv_inference_pose_get_label(
    mv_inference_pose_result_h result,
    int pose_index,
    ffi.Pointer<ffi.Int> label,
  ) {
    return _mv_inference_pose_get_label(
      result,
      pose_index,
      label,
    );
  }

  late final _mv_inference_pose_get_labelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_inference_pose_result_h, ffi.Int,
              ffi.Pointer<ffi.Int>)>>('mv_inference_pose_get_label');
  late final _mv_inference_pose_get_label =
      _mv_inference_pose_get_labelPtr.asFunction<
          int Function(
              mv_inference_pose_result_h, int, ffi.Pointer<ffi.Int>)>();

  /// Creates pose handle.
  ///
  /// Use this function to create a pose.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Remarks:**
  /// - The `pose` should be released using mv_pose_destroy().
  ///
  /// **Parameters:**
  /// - `pose` (out): The handle to the pose to be created
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_OUT_OF_MEMORY`: Out of memory
  ///
  /// **See also:**
  /// - `mv_pose_destroy()`
  int mv_pose_create(
    ffi.Pointer<mv_pose_h> pose,
  ) {
    return _mv_pose_create(
      pose,
    );
  }

  late final _mv_pose_createPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<mv_pose_h>)>>(
          'mv_pose_create');
  late final _mv_pose_create =
      _mv_pose_createPtr.asFunction<int Function(ffi.Pointer<mv_pose_h>)>();

  /// Destroys pose handle and releases all its resources.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Parameters:**
  /// - `pose` (in): The handle to the pose to be destroyed
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - Create pose handle by using mv_pose_create()
  ///
  /// **See also:**
  /// - `mv_pose_create()`
  int mv_pose_destroy(
    mv_pose_h pose,
  ) {
    return _mv_pose_destroy(
      pose,
    );
  }

  late final _mv_pose_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(mv_pose_h)>>(
          'mv_pose_destroy');
  late final _mv_pose_destroy =
      _mv_pose_destroyPtr.asFunction<int Function(mv_pose_h)>();

  /// Sets a motion capture file and its pose mapping file to the pose.
  ///
  /// Use this function to set a motion capture file and its pose mapping file. These are used by mv_pose_compare() to compare a given pose by mv_inference_pose_landmark_estimation().
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Remarks:**
  /// - If the app sets paths to media storage,
  /// - then the media storage privilege
  /// - <http://tizen.org/privilege/mediastorage is needed.>
  /// - If the app sets the paths to external storage,
  /// - then the external storage privilege
  /// - <http://tizen.org/privilege/externalstorage is needed.>
  /// - If the required privileges aren't set properly,
  /// - mv_pose_set_from_file() will returned `MEDIA_VISION_ERROR_PERMISSION_DENIED`.
  ///
  /// **Parameters:**
  /// - `pose` (in): The handle to the pose
  /// - `motion_capture_file_path` (in): The file path to the motion capture file
  /// - `motion_mapping_file_path` (in): The file path to the motion mapping file
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INVALID_PATH`: Invalid path of capture or mapping file
  /// - `MEDIA_VISION_ERROR_INTERNAL`: Internal error
  int mv_pose_set_from_file(
    mv_pose_h pose,
    ffi.Pointer<ffi.Char> motion_capture_file_path,
    ffi.Pointer<ffi.Char> motion_mapping_file_path,
  ) {
    return _mv_pose_set_from_file(
      pose,
      motion_capture_file_path,
      motion_mapping_file_path,
    );
  }

  late final _mv_pose_set_from_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_pose_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('mv_pose_set_from_file');
  late final _mv_pose_set_from_file = _mv_pose_set_from_filePtr.asFunction<
      int Function(mv_pose_h, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Compares an action pose with the pose which is set by mv_pose_set_from_file().
  ///
  /// Use this function to compare action pose with the pose which is set by mv_pose_set_from_file(). Parts to be compared can be selected by `mv_inference_human_body_part_e`. Their similarity will be given by the score between 0 ~ 1.
  ///
  /// **Since Tizen:**
  /// - 6.0
  ///
  /// **Remarks:**
  /// - If `action` contains multiple poses, the first pose is used for comparison.
  ///
  /// **Parameters:**
  /// - `pose` (in): The handle to the pose
  /// - `action` (in): The action pose
  /// - `parts` (in): The parts to be compared
  /// - `score` (out): The similarity score
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `MEDIA_VISION_ERROR_NONE`: Successful
  /// - `MEDIA_VISION_ERROR_NOT_SUPPORTED`: Not supported
  /// - `MEDIA_VISION_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `MEDIA_VISION_ERROR_INVALID_OPERATION`: Invalid operation
  ///
  /// **Preconditions:**
  /// - Sets the pose by using mv_pose_set_from_file()
  /// - Detects the pose by using mv_inference_pose_landmark_detect()
  int mv_pose_compare(
    mv_pose_h pose,
    mv_inference_pose_result_h action,
    int parts,
    ffi.Pointer<ffi.Float> score,
  ) {
    return _mv_pose_compare(
      pose,
      action,
      parts,
      score,
    );
  }

  late final _mv_pose_comparePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(mv_pose_h, mv_inference_pose_result_h, ffi.Int,
              ffi.Pointer<ffi.Float>)>>('mv_pose_compare');
  late final _mv_pose_compare = _mv_pose_comparePtr.asFunction<
      int Function(mv_pose_h, mv_inference_pose_result_h, int,
          ffi.Pointer<ffi.Float>)>();
}

/// Enumeration for inference backend. `MV_INFERENCE_BACKEND_OPENCV` An open source computer vision and machine learning software library. (https://opencv.org/about/) `MV_INFERENCE_BACKEND_TFLITE` Google-introduced open source inference engine for embedded systems, which runs Tensorflow Lite model. (https://www.tensorflow.org/lite/guide/get_started) `MV_INFERENCE_BACKEND_ARMNN` ARM-introduced open source inference engine for CPUs, GPUs and NPUs, which enables efficient translation of existing neural network frameworks such as TensorFlow, TensorFlow Lite and Caffes, allowing them to run efficiently without modification on Embedded hardware. (https://developer.arm.com/ip-products/processors/machine-learning/arm-nn) `MV_INFERENCE_BACKEND_MLAPI` Samsung-introduced open source ML single API framework of NNStreamer, which runs various NN models via tensor filters of NNStreamer. (https://github.com/nnstreamer/nnstreamer) `MV_INFERENCE_BACKEND_ONE` Samsung-introduced open source inference engine called On-device Neural Engine, which performs inference of a given NN model on various devices such as CPU, GPU, DSP and NPU. (https://github.com/Samsung/ONE)
///
/// **Since Tizen:**
/// - 5.5
///
/// **See also:**
/// - `mv_inference_prepare()`
/// @nodoc
abstract class mv_inference_backend_type_e {
  /// < None
  static const int MV_INFERENCE_BACKEND_NONE = -1;

  /// < OpenCV
  static const int MV_INFERENCE_BACKEND_OPENCV = 0;

  /// < TensorFlow-Lite
  static const int MV_INFERENCE_BACKEND_TFLITE = 1;

  /// < ARMNN (Since 6.0)
  static const int MV_INFERENCE_BACKEND_ARMNN = 2;

  /// < ML Single API of NNStreamer (Since 6.0)
  static const int MV_INFERENCE_BACKEND_MLAPI = 3;

  /// < On-device Neural Engine (Since 6.0)
  static const int MV_INFERENCE_BACKEND_ONE = 4;

  /// < Backend MAX
  static const int MV_INFERENCE_BACKEND_MAX = 5;
}

/// **Deprecated:** Deprecated since 6.0. Use `mv_inference_target_device_e` instead.
///
/// Enumeration for inference target.
///
/// **Since Tizen:**
/// - 5.5
/// @nodoc
abstract class mv_inference_target_type_e {
  /// < None
  static const int MV_INFERENCE_TARGET_NONE = -1;

  /// < CPU
  static const int MV_INFERENCE_TARGET_CPU = 0;

  /// < GPU
  static const int MV_INFERENCE_TARGET_GPU = 1;

  /// < CUSTOM
  static const int MV_INFERENCE_TARGET_CUSTOM = 2;

  /// < Target MAX
  static const int MV_INFERENCE_TARGET_MAX = 3;
}

/// Enumeration for inference target.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
abstract class mv_inference_target_device_e {
  /// < None
  static const int MV_INFERENCE_TARGET_DEVICE_NONE = 0;

  /// < CPU
  static const int MV_INFERENCE_TARGET_DEVICE_CPU = 1;

  /// < GPU
  static const int MV_INFERENCE_TARGET_DEVICE_GPU = 2;

  /// < CUSTOM
  static const int MV_INFERENCE_TARGET_DEVICE_CUSTOM = 4;

  /// < Target MAX
  static const int MV_INFERENCE_TARGET_DEVICE_MAX = 8;
}

/// Enumeration for input data type.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
abstract class mv_inference_data_type_e {
  /// < Data type of a given pre-trained model is float.
  static const int MV_INFERENCE_DATA_FLOAT32 = 0;

  /// < Data type of a given pre-trained model is unsigned char.
  static const int MV_INFERENCE_DATA_UINT8 = 1;
}

/// Enumeration for human pose landmark.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
abstract class mv_inference_human_pose_landmark_e {
  /// < Head of human pose
  static const int MV_INFERENCE_HUMAN_POSE_HEAD = 1;

  /// < Neck of human pose
  static const int MV_INFERENCE_HUMAN_POSE_NECK = 2;

  /// < Thorax of human pose
  static const int MV_INFERENCE_HUMAN_POSE_THORAX = 3;

  /// < Right shoulder of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_SHOULDER = 4;

  /// < Right elbow of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_ELBOW = 5;

  /// < Right wrist of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_WRIST = 6;

  /// < Left shoulder of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_SHOULDER = 7;

  /// < Left elbow of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_ELBOW = 8;

  /// < Left wrist of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_WRIST = 9;

  /// < Pelvis of human pose
  static const int MV_INFERENCE_HUMAN_POSE_PELVIS = 10;

  /// < Right hip of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_HIP = 11;

  /// < Right knee of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_KNEE = 12;

  /// < Right ankle of human pose
  static const int MV_INFERENCE_HUMAN_POSE_RIGHT_ANKLE = 13;

  /// < Left hip of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_HIP = 14;

  /// < Left knee of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_KNEE = 15;

  /// < Left ankle of human pose
  static const int MV_INFERENCE_HUMAN_POSE_LEFT_ANKLE = 16;
}

/// Enumeration for human body parts.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
abstract class mv_inference_human_body_part_e {
  /// < HEAD, NECK, and THORAX
  static const int MV_INFERENCE_HUMAN_BODY_PART_HEAD = 1;

  /// < RIGHT SHOULDER, ELBOW, and WRIST
  static const int MV_INFERENCE_HUMAN_BODY_PART_ARM_RIGHT = 2;

  /// < LEFT SHOULDER, ELBOW, and WRIST
  static const int MV_INFERENCE_HUMAN_BODY_PART_ARM_LEFT = 4;

  /// < THORAX, PELVIS, RIGHT HIP, and LEFT HIP
  static const int MV_INFERENCE_HUMAN_BODY_PART_BODY = 8;

  /// < RIGHT HIP, KNEE, and ANKLE
  static const int MV_INFERENCE_HUMAN_BODY_PART_LEG_RIGHT = 16;

  /// < LEFT HIP, KNEE, and ANKLE
  static const int MV_INFERENCE_HUMAN_BODY_PART_LEG_LEFT = 32;
}

/// The inference handle.
///
/// Contains information about location of detected landmarks for one or more poses.
///
/// **Since Tizen:**
/// - 5.5
/// @nodoc
typedef mv_inference_h = ffi.Pointer<ffi.Void>;

/// Called to provide information for supported engines for inference.
///
/// **Since Tizen:**
/// - 5.5
///
/// **Parameters:**
/// - `engine` (in): The supported engine. The `engine` can be used only in the callback. To use outside, make a copy.
/// - `supported` (in): The flag whether the engine is supported or not
/// - `user_data` (in): The user data passed from mv_inference_foreach_supported_engine()
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, otherwise `false` to break out of the loop
///
/// **Preconditions:**
/// - mv_inference_foreach_supported_engine()
/// @nodoc
typedef mv_inference_supported_engine_cb
    = ffi.Pointer<ffi.NativeFunction<mv_inference_supported_engine_cbFunction>>;
/// @nodoc
typedef mv_inference_supported_engine_cbFunction = ffi.Bool Function(
    ffi.Pointer<ffi.Char> engine,
    ffi.Bool supported,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_supported_engine_cbFunction = bool Function(
    ffi.Pointer<ffi.Char> engine,
    bool supported,
    ffi.Pointer<ffi.Void> user_data);

/// / /**
///
/// Called when `source` is classified.
///
/// This callback is invoked each time when mv_inference_image_classify() is called to provide the results of image classification.
///
/// **Since Tizen:**
/// - 5.5
///
/// **Remarks:**
/// - The `indices`, `names`, and `confidences` should not be released by the app.
/// - They can be used only in the callback. The number of elements in `indices`, `names`,
/// - and `confidences` is equal to `number_of_classes`.
///
/// **Parameters:**
/// - `source` (in): The handle to the source of the media where an image was classified. `source` is the same object for which mv_inference_image_classify() was called. It should be released by calling mv_destroy_source() when it's not needed anymore.
/// - `number_of_classes` (in): The number of classes
/// - `indices` (in): The indices of the classified image.
/// - `names` (in): Names corresponding to the indices.
/// - `confidences` (in): Each element is the confidence that the corresponding image belongs to the corresponding class.
/// - `user_data` (in): The user data passed from callback invoking code
///
/// **Preconditions:**
/// - Call mv_inference_image_classify() function to perform classification of the image and to invoke this callback as a result
///
/// **See also:**
/// - `mv_inference_image_classify()`
/// @nodoc
typedef mv_inference_image_classified_cb
    = ffi.Pointer<ffi.NativeFunction<mv_inference_image_classified_cbFunction>>;
/// @nodoc
typedef mv_inference_image_classified_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    ffi.Int number_of_classes,
    ffi.Pointer<ffi.Int> indices,
    ffi.Pointer<ffi.Pointer<ffi.Char>> names,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_image_classified_cbFunction = void Function(
    mv_common.mv_source_h source,
    int number_of_classes,
    ffi.Pointer<ffi.Int> indices,
    ffi.Pointer<ffi.Pointer<ffi.Char>> names,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<ffi.Void> user_data);

/// / /**
///
/// Called when objects in `source` are detected.
///
/// This callback is invoked each time when mv_inference_object_detect() is called to provide the results of object detection.
///
/// **Since Tizen:**
/// - 5.5
///
/// **Remarks:**
/// - The `indices`, `names`, `confidences`, and `locations` should not be released by app.
/// - They can be used only in the callback. The number of elements in `indices`, `names`,
/// - `confidences`, and `locations` is equal to `number_of_objects`.
///
/// **Parameters:**
/// - `source` (in): The handle to the source of the media where an image was classified. `source` is the same object for which mv_inference_object_detect() was called. It should be released by calling mv_destroy_source() when it's not needed anymore.
/// - `number_of_objects` (in): The number of objects
/// - `indices` (in): The indices of objects.
/// - `names` (in): Names corresponding to the indices.
/// - `confidences` (in): Confidences of the detected objects.
/// - `locations` (in): Locations of the detected objects.
/// - `user_data` (in): The user data passed from callback invoking code
///
/// **Preconditions:**
/// - Call mv_inference_object_detect() function to perform detection of the objects in `source` and to invoke this callback as a result
///
/// **See also:**
/// - `mv_inference_object_detect()`
/// @nodoc
typedef mv_inference_object_detected_cb
    = ffi.Pointer<ffi.NativeFunction<mv_inference_object_detected_cbFunction>>;
/// @nodoc
typedef mv_inference_object_detected_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    ffi.Int number_of_objects,
    ffi.Pointer<ffi.Int> indices,
    ffi.Pointer<ffi.Pointer<ffi.Char>> names,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<mv_common.mv_rectangle_s> locations,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_object_detected_cbFunction = void Function(
    mv_common.mv_source_h source,
    int number_of_objects,
    ffi.Pointer<ffi.Int> indices,
    ffi.Pointer<ffi.Pointer<ffi.Char>> names,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<mv_common.mv_rectangle_s> locations,
    ffi.Pointer<ffi.Void> user_data);

/// / /**
///
/// Called when faces in `source` are detected.
///
/// This callback is invoked each time when mv_inference_face_detect() is called to provide the results of face detection.
///
/// **Since Tizen:**
/// - 5.5
///
/// **Remarks:**
/// - The `confidences` and `locations` should not be released by app.
/// - They can be used only in the callback. The number of elements in `confidences`
/// - and `locations` is equal to `number_of_faces`.
///
/// **Parameters:**
/// - `source` (in): The handle to the source of the media where faces were detected. `source` is the same object for which mv_inference_face_detect() was called. It should be released by calling mv_destroy_source() when it's not needed anymore.
/// - `number_of_faces` (in): The number of faces
/// - `confidences` (in): Confidences of the detected faces.
/// - `locations` (in): Locations of the detected faces.
/// - `user_data` (in): The user data passed from callback invoking code
///
/// **Preconditions:**
/// - Call mv_inference_face_detect() function to perform detection of the faces in `source` and to invoke this callback as a result
///
/// **See also:**
/// - `mv_inference_face_detect()`
/// @nodoc
typedef mv_inference_face_detected_cb
    = ffi.Pointer<ffi.NativeFunction<mv_inference_face_detected_cbFunction>>;
/// @nodoc
typedef mv_inference_face_detected_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    ffi.Int number_of_faces,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<mv_common.mv_rectangle_s> locations,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_face_detected_cbFunction = void Function(
    mv_common.mv_source_h source,
    int number_of_faces,
    ffi.Pointer<ffi.Float> confidences,
    ffi.Pointer<mv_common.mv_rectangle_s> locations,
    ffi.Pointer<ffi.Void> user_data);

/// Called when facial landmarks in `source` are detected.
///
/// This type callback is invoked each time when mv_inference_facial_landmark_detect() is called to provide the results of the landmarks detection.
///
/// **Since Tizen:**
/// - 5.5
///
/// **Remarks:**
/// - The `locations` should not be released by app. They can be used only in the callback.
/// - The number of elements in `locations` is equal to `number_of_landmarks`.
///
/// **Parameters:**
/// - `source` (in): The handle to the source of the media where landmarks were detected. `source` is the same object for which mv_inference_facial_landmark_detect() was called. It should be released by calling mv_destroy_source() when it's not needed anymore.
/// - `number_of_landmarks` (in): The number of landmarks
/// - `locations` (in): Locations of the detected facial landmarks.
/// - `user_data` (in): The user data passed from callback invoking code
///
/// **Preconditions:**
/// - Call mv_inference_face_detect() function to perform detection of the faces in `source` and to invoke this callback as a result
///
/// **See also:**
/// - `mv_inference_face_detect()`
/// @nodoc
typedef mv_inference_facial_landmark_detected_cb = ffi.Pointer<
    ffi.NativeFunction<mv_inference_facial_landmark_detected_cbFunction>>;
/// @nodoc
typedef mv_inference_facial_landmark_detected_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    ffi.Int number_of_landmarks,
    ffi.Pointer<mv_common.mv_point_s> locations,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_facial_landmark_detected_cbFunction = void Function(
    mv_common.mv_source_h source,
    int number_of_landmarks,
    ffi.Pointer<mv_common.mv_point_s> locations,
    ffi.Pointer<ffi.Void> user_data);

/// Called when poses in `source` are detected.
///
/// This type callback is invoked each time when mv_inference_pose_landmark_detect() is called to provide the results of the pose landmark detection.
///
/// **Since Tizen:**
/// - 6.0
///
/// **Remarks:**
/// - The `locations` should not be released by app. They can be used only in the callback.
///
/// **Parameters:**
/// - `source` (in): The handle to the source of the media where landmarks were detected. `source` is the same object for which mv_inference_pose_landmark_detect() was called. It should be released by calling mv_destroy_source() when it's not needed anymore.
/// - `locations` (in): Locations of the detected pose landmarks.
/// - `user_data` (in): The user data passed from callback invoking code
///
/// **See also:**
/// - `mv_inference_pose_landmark_detect()`
/// @nodoc
typedef mv_inference_pose_landmark_detected_cb = ffi.Pointer<
    ffi.NativeFunction<mv_inference_pose_landmark_detected_cbFunction>>;
/// @nodoc
typedef mv_inference_pose_landmark_detected_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    mv_inference_pose_result_h locations,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartmv_inference_pose_landmark_detected_cbFunction = void Function(
    mv_common.mv_source_h source,
    mv_inference_pose_result_h locations,
    ffi.Pointer<ffi.Void> user_data);

/// The inference pose result handle.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
typedef mv_inference_pose_result_h = ffi.Pointer<ffi.Void>;

/// The pose handle.
///
/// **Since Tizen:**
/// - 6.0
/// @nodoc
typedef mv_pose_h = ffi.Pointer<ffi.Void>;

/// @nodoc
const String MV_INFERENCE_MODEL_CONFIGURATION_FILE_PATH =
    'MV_INFERENCE_MODEL_CONFIGURATION_FILE_PATH';

/// @nodoc
const String MV_INFERENCE_MODEL_WEIGHT_FILE_PATH =
    'MV_INFERENCE_MODEL_WEIGHT_FILE_PATH';

/// @nodoc
const String MV_INFERENCE_MODEL_USER_FILE_PATH =
    'MV_INFERENCE_MODEL_USER_FILE_PATH';

/// @nodoc
const String MV_INFERENCE_MODEL_META_FILE_PATH =
    'MV_INFERENCE_MODEL_META_FILE_PATH';

/// @nodoc
const String MV_INFERENCE_MODEL_MEAN_VALUE = 'MV_INFERENCE_MODEL_MEAN_VALUE';

/// @nodoc
const String MV_INFERENCE_MODEL_STD_VALUE = 'MV_INFERENCE_MODEL_STD_VALUE';

/// @nodoc
const String MV_INFERENCE_BACKEND_TYPE = 'MV_INFERENCE_BACKEND_TYPE';

/// @nodoc
const String MV_INFERENCE_TARGET_TYPE = 'MV_INFERENCE_TARGET_TYPE';

/// @nodoc
const String MV_INFERENCE_TARGET_DEVICE_TYPE =
    'MV_INFERENCE_TARGET_DEVICE_TYPE';

/// @nodoc
const String MV_INFERENCE_INPUT_TENSOR_WIDTH =
    'MV_INFERENCE_INPUT_TENSOR_WIDTH';

/// @nodoc
const String MV_INFERENCE_INPUT_TENSOR_HEIGHT =
    'MV_INFERENCE_INPUT_TENSOR_HEIGHT';

/// @nodoc
const String MV_INFERENCE_INPUT_TENSOR_CHANNELS =
    'MV_INFERENCE_INPUT_TENSOR_CHANNELS';

/// @nodoc
const String MV_INFERENCE_INPUT_DATA_TYPE = 'MV_INFERENCE_INPUT_DATA_TYPE';

/// @nodoc
const String MV_INFERENCE_INPUT_NODE_NAME = 'MV_INFERENCE_INPUT_NODE_NAME';

/// @nodoc
const String MV_INFERENCE_OUTPUT_NODE_NAMES = 'MV_INFERENCE_OUTPUT_NODE_NAMES';

/// @nodoc
const String MV_INFERENCE_OUTPUT_MAX_NUMBER = 'MV_INFERENCE_OUTPUT_MAX_NUMBER';

/// @nodoc
const String MV_INFERENCE_CONFIDENCE_THRESHOLD =
    'MV_INFERENCE_CONFIDENCE_THRESHOLD';
