// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen capi-appfw-job-scheduler APIs.
class Tizen65CapiAppfwJobScheduler {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen65CapiAppfwJobScheduler(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen65CapiAppfwJobScheduler.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Creates the job info handle.
  /// @since_tizen 4.0
  /// @remarks The @a job_info must be released by using job_info_destroy().
  /// The job will be started by the periodic interval or the trigger events.
  /// @param[out]  job_info        The job info handle to be newly created on success
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @see    job_info_destroy()
  /// @see    job_info_set_periodic()
  /// @see    job_info_add_trigger_event()
  int job_info_create(
    ffi.Pointer<job_info_h> job_info,
  ) {
    return _job_info_create(
      job_info,
    );
  }

  late final _job_info_createPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<job_info_h>)>>(
          'job_info_create');
  late final _job_info_create =
      _job_info_createPtr.asFunction<int Function(ffi.Pointer<job_info_h>)>();

  /// @brief Destroys the job info handle and releases all its resources.
  /// @since_tizen 4.0
  /// @param[in]   job_info        The job info handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see    job_info_create()
  int job_info_destroy(
    job_info_h job_info,
  ) {
    return _job_info_destroy(
      job_info,
    );
  }

  late final _job_info_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h)>>(
          'job_info_destroy');
  late final _job_info_destroy =
      _job_info_destroyPtr.asFunction<int Function(job_info_h)>();

  /// @brief Sets the periodic interval of the job.
  /// @since_tizen 4.0
  /// @remarks The platform does not guarantee the accuracy of the given interval for minimizing the wakeups of the device.
  /// Thus you should not rely on it for timing.
  /// If this function is called after adding the job trigger events by using job_info_add_trigger_event(),
  /// the function returns a negative error value.
  /// @param[in]   job_info        The job info handle
  /// @param[in]   interval        The periodic interval (in minutes)
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see    job_info_destroy()
  int job_info_set_periodic(
    job_info_h job_info,
    int interval,
  ) {
    return _job_info_set_periodic(
      job_info,
      interval,
    );
  }

  late final _job_info_set_periodicPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.UnsignedInt)>>(
      'job_info_set_periodic');
  late final _job_info_set_periodic =
      _job_info_set_periodicPtr.asFunction<int Function(job_info_h, int)>();

  /// @brief Sets the job to be automatically scheduled after the device reboots.
  /// @since_tizen 4.0
  /// @remarks If it's a one-time job, setting it to a persistent job returns
  /// a negative error value on scheduling by using job_scheduler_schedule().
  /// @param[in]   job_info        The job info handle
  /// @param[in]   persistent      @c true, if the job needs to be automatically scheduled
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see    job_info_set_once()
  /// @see    job_scheduler_schedule()
  int job_info_set_persistent(
    job_info_h job_info,
    bool persistent,
  ) {
    return _job_info_set_persistent(
      job_info,
      persistent,
    );
  }

  late final _job_info_set_persistentPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Bool)>>(
          'job_info_set_persistent');
  late final _job_info_set_persistent =
      _job_info_set_persistentPtr.asFunction<int Function(job_info_h, bool)>();

  /// @brief Sets the job not to be repeated.
  /// @since_tizen 4.0
  /// @remarks If it's a persistent job, setting it to a one-time job returns
  /// a negative error value on scheduling by using job_scheduler_schedule().
  /// @param[in]   job_info        The job info handle
  /// @param[in]   once            @c true, if the job does not need to be repeated
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see    job_info_set_persistent()
  /// @see    job_scheduler_schedule()
  int job_info_set_once(
    job_info_h job_info,
    bool once,
  ) {
    return _job_info_set_once(
      job_info,
      once,
    );
  }

  late final _job_info_set_oncePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Bool)>>(
          'job_info_set_once');
  late final _job_info_set_once =
      _job_info_set_oncePtr.asFunction<int Function(job_info_h, bool)>();

  /// @brief Sets the timeout interval of the requirements.
  /// @since_tizen 4.0
  /// @remarks If the requirements are not satisfied within the timeout value,
  /// the job does not start.
  /// @param[in]   job_info        The job info handle
  /// @param[in]   timeout         The timeout interval (ms)
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  int job_info_set_requirement_timeout(
    job_info_h job_info,
    int timeout,
  ) {
    return _job_info_set_requirement_timeout(
      job_info,
      timeout,
    );
  }

  late final _job_info_set_requirement_timeoutPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.UnsignedInt)>>(
      'job_info_set_requirement_timeout');
  late final _job_info_set_requirement_timeout =
      _job_info_set_requirement_timeoutPtr
          .asFunction<int Function(job_info_h, int)>();

  /// @brief Sets that the battery level must not be low to run the job.
  /// @since_tizen 4.0
  /// @param[in]   job_info        The job info handle
  /// @param[in]   battery_not_low @c true, the battery level must not be low.
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NOT_SUPPORTED     Not supported
  /// @pre    job_scheduler_init() must be called.
  /// @see    job_scheduler_init()
  int job_info_set_requires_battery_not_low(
    job_info_h job_info,
    bool battery_not_low,
  ) {
    return _job_info_set_requires_battery_not_low(
      job_info,
      battery_not_low,
    );
  }

  late final _job_info_set_requires_battery_not_lowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Bool)>>(
          'job_info_set_requires_battery_not_low');
  late final _job_info_set_requires_battery_not_low =
      _job_info_set_requires_battery_not_lowPtr
          .asFunction<int Function(job_info_h, bool)>();

  /// @brief Sets that the battery must be charging to run the job.
  /// @since_tizen 4.0
  /// @param[in]   job_info        The job info handle
  /// @param[in]   charging        @c true, the battery must be charging.
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NOT_SUPPORTED     Not supported
  /// @pre    job_scheduler_init() must be called.
  /// @see    job_scheduler_init()
  int job_info_set_requires_charging(
    job_info_h job_info,
    bool charging,
  ) {
    return _job_info_set_requires_charging(
      job_info,
      charging,
    );
  }

  late final _job_info_set_requires_chargingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Bool)>>(
          'job_info_set_requires_charging');
  late final _job_info_set_requires_charging =
      _job_info_set_requires_chargingPtr
          .asFunction<int Function(job_info_h, bool)>();

  /// @brief Sets that the WiFi must be connected to run the job.
  /// @since_tizen 4.0
  /// @privlevel   public
  /// @privilege   %http://tizen.org/privilege/network.get
  /// @param[in]   job_info        The job info handle
  /// @param[in]   wifi_connection @c true, the WiFi must be connected.
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NOT_SUPPORTED     Not supported
  /// @retval #JOB_ERROR_PERMISSION_DENIED Permission denied
  /// @pre    job_scheduler_init() must be called.
  /// @see    job_scheduler_init()
  int job_info_set_requires_wifi_connection(
    job_info_h job_info,
    bool wifi_connection,
  ) {
    return _job_info_set_requires_wifi_connection(
      job_info,
      wifi_connection,
    );
  }

  late final _job_info_set_requires_wifi_connectionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Bool)>>(
          'job_info_set_requires_wifi_connection');
  late final _job_info_set_requires_wifi_connection =
      _job_info_set_requires_wifi_connectionPtr
          .asFunction<int Function(job_info_h, bool)>();

  /// @brief Adds the trigger event to the job info handle.
  /// @since_tizen 4.0
  /// @remarks The periodic interval of the job info handle must be 0.
  /// If the interval of the job info handle is not 0, this function returns a negative error value.
  /// Regarding the @a event, the application may require the following privilege:
  /// %http://tizen.org/privilege/network.get @n
  /// If the application does not have the necessary privilege, this function returns #JOB_ERROR_PERMISSION_DENIED.
  /// See #job_trigger_event_e to find the corresponding privilege of each event.
  /// @param[in]   job_info        The job info handle
  /// @param[in]   event           The job trigger event
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NOT_SUPPORTED     Not supported
  /// @retval #JOB_ERROR_ALREADY_EXIST     Already exist
  /// @retval #JOB_ERROR_PERMISSION_DENIED Permission denied
  /// @pre    job_scheduler_init() must be called.
  /// @see    job_scheduler_init()
  /// @see    job_info_remove_trigger_event()
  /// @see    job_trigger_event_e
  int job_info_add_trigger_event(
    job_info_h job_info,
    int event,
  ) {
    return _job_info_add_trigger_event(
      job_info,
      event,
    );
  }

  late final _job_info_add_trigger_eventPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Int32)>>(
          'job_info_add_trigger_event');
  late final _job_info_add_trigger_event = _job_info_add_trigger_eventPtr
      .asFunction<int Function(job_info_h, int)>();

  /// @brief Removes the trigger event from the job info handle.
  /// @since_tizen 4.0
  /// @remarks The periodic interval of the job info handle must be 0.
  /// If the interval of the job info handle is not 0, this function returns a negative error value.
  /// @param[in]   job_info        The job info handle
  /// @param[in]   event           The job trigger event
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see    job_info_add_trigger_event()
  /// @see    job_trigger_event_e
  int job_info_remove_trigger_event(
    job_info_h job_info,
    int event,
  ) {
    return _job_info_remove_trigger_event(
      job_info,
      event,
    );
  }

  late final _job_info_remove_trigger_eventPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_info_h, ffi.Int32)>>(
          'job_info_remove_trigger_event');
  late final _job_info_remove_trigger_event = _job_info_remove_trigger_eventPtr
      .asFunction<int Function(job_info_h, int)>();

  /// @brief Gets the ID of the job.
  /// @since_tizen 4.0
  /// @remarks The @a job_info must be scheduled by using job_scheduler_schedule().
  /// If the job_info is not scheduled, this function returns a negative error value.
  /// The @a job_id must be released by using free().
  /// @param[in]   job_info        The job info handle
  /// @param[out]  job_id          The ID of the job
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @see    job_scheduler_schedule()
  int job_info_get_job_id(
    job_info_h job_info,
    ffi.Pointer<ffi.Pointer<ffi.Char>> job_id,
  ) {
    return _job_info_get_job_id(
      job_info,
      job_id,
    );
  }

  late final _job_info_get_job_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(job_info_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('job_info_get_job_id');
  late final _job_info_get_job_id = _job_info_get_job_idPtr.asFunction<
      int Function(job_info_h, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// @brief Clones the given job_info handle.
  /// @since_tizen 4.0
  /// @remarks The newly created job_info handle must be released by using job_info_destroy().
  /// @param[in]   job_info        The job info handle
  /// @param[out]  clone           If successful, a newly created job info handle will be returned
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @see    job_info_destroy()
  int job_info_clone(
    job_info_h job_info,
    ffi.Pointer<job_info_h> clone,
  ) {
    return _job_info_clone(
      job_info,
      clone,
    );
  }

  late final _job_info_clonePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              job_info_h, ffi.Pointer<job_info_h>)>>('job_info_clone');
  late final _job_info_clone = _job_info_clonePtr
      .asFunction<int Function(job_info_h, ffi.Pointer<job_info_h>)>();

  /// @brief Initializes the job scheduler.
  /// @since_tizen 4.0
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @see    job_scheduler_finish()
  int job_scheduler_init() {
    return _job_scheduler_init();
  }

  late final _job_scheduler_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('job_scheduler_init');
  late final _job_scheduler_init =
      _job_scheduler_initPtr.asFunction<int Function()>();

  /// @brief Finalizes the job scheduler.
  /// @since_tizen 4.0
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @see    job_scheduler_init()
  int job_scheduler_finish() {
    return _job_scheduler_finish();
  }

  late final _job_scheduler_finishPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('job_scheduler_finish');
  late final _job_scheduler_finish =
      _job_scheduler_finishPtr.asFunction<int Function()>();

  /// @brief Schedules the job.
  /// @since_tizen 4.0
  /// @privlevel   public
  /// @privilege   %http://tizen.org/privilege/appmanager.launch
  /// @param[in]   job_info        The job info handle
  /// @param[in]   job_id          The ID of the job
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_ALREADY_EXIST     Already exist
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @retval #JOB_ERROR_PERMISSION_DENIED Permission denied
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  /// @see    job_info_create()
  int job_scheduler_schedule(
    job_info_h job_info,
    ffi.Pointer<ffi.Char> job_id,
  ) {
    return _job_scheduler_schedule(
      job_info,
      job_id,
    );
  }

  late final _job_scheduler_schedulePtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(job_info_h, ffi.Pointer<ffi.Char>)>>(
      'job_scheduler_schedule');
  late final _job_scheduler_schedule = _job_scheduler_schedulePtr
      .asFunction<int Function(job_info_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Cancels the scheduled job.
  /// @since_tizen 4.0
  /// @param[in]   job_id          The ID of the scheduled job
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @retval #JOB_ERROR_NO_SUCH_JOB       No such job
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  int job_scheduler_cancel(
    ffi.Pointer<ffi.Char> job_id,
  ) {
    return _job_scheduler_cancel(
      job_id,
    );
  }

  late final _job_scheduler_cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'job_scheduler_cancel');
  late final _job_scheduler_cancel = _job_scheduler_cancelPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Cancels all scheduled jobs.
  /// @since_tizen 4.0
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  int job_scheduler_cancel_all() {
    return _job_scheduler_cancel_all();
  }

  late final _job_scheduler_cancel_allPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'job_scheduler_cancel_all');
  late final _job_scheduler_cancel_all =
      _job_scheduler_cancel_allPtr.asFunction<int Function()>();

  /// @brief Notifies that the job is finished.
  /// @since_tizen 4.0
  /// @remarks If the job has been launched, the system kept awake for a while.
  /// It is highly recommended to notify that the job is done,
  /// the system thus knows it does not need to be kept awake.
  /// @param[in]   job_id          The ID of the scheduled job
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NO_SUCH_JOB       No such job
  /// @retval #JOB_ERROR_IO_ERROR          IO error
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  int job_scheduler_notify_job_finished(
    ffi.Pointer<ffi.Char> job_id,
  ) {
    return _job_scheduler_notify_job_finished(
      job_id,
    );
  }

  late final _job_scheduler_notify_job_finishedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'job_scheduler_notify_job_finished');
  late final _job_scheduler_notify_job_finished =
      _job_scheduler_notify_job_finishedPtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Retrieves all scheduled jobs.
  /// @since_tizen 4.0
  /// @param[in]   callback        The iteration callback function
  /// @param[in]   user_data       The user data to be passed to the callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_NO_SUCH_JOB       No scheduled jobs
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  int job_scheduler_foreach_job(
    job_scheduler_foreach_job_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _job_scheduler_foreach_job(
      callback,
      user_data,
    );
  }

  late final _job_scheduler_foreach_jobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(job_scheduler_foreach_job_cb,
              ffi.Pointer<ffi.Void>)>>('job_scheduler_foreach_job');
  late final _job_scheduler_foreach_job =
      _job_scheduler_foreach_jobPtr.asFunction<
          int Function(job_scheduler_foreach_job_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Adds job service handler for receiving the information of the scheduled job.
  /// @since_tizen 4.0
  /// @remarks The @a job_service handle should be released using job_scheduler_service_remove().
  /// @param[in]   job_id          The ID of the job
  /// @param[in]   callback        The set of callback functions to handle jobs
  /// @param[in]   user_data       The user data to be passed to the callback function
  /// @param[out]  job_service     The job service handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @retval #JOB_ERROR_OUT_OF_MEMORY     Out of memory
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  /// @see    job_scheduler_service_remove()
  /// @see    job_service_start_cb()
  /// @see    job_service_stop_cb()
  /// @see    job_scheduler_notify_job_finished()
  /// @see    #job_service_callback_s
  int job_scheduler_service_add(
    ffi.Pointer<ffi.Char> job_id,
    ffi.Pointer<job_service_callback_s> callback,
    ffi.Pointer<ffi.Void> user_data,
    ffi.Pointer<job_service_h> job_service,
  ) {
    return _job_scheduler_service_add(
      job_id,
      callback,
      user_data,
      job_service,
    );
  }

  late final _job_scheduler_service_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<job_service_callback_s>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<job_service_h>)>>('job_scheduler_service_add');
  late final _job_scheduler_service_add =
      _job_scheduler_service_addPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<job_service_callback_s>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<job_service_h>)>();

  /// @brief Removes registered job service handler.
  /// @since_tizen 4.0
  /// @param[in]   job_service     The job service handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #JOB_ERROR_NONE              Successful
  /// @retval #JOB_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #JOB_ERROR_NOT_INITIALIZED   Not initialized
  /// @pre    job_scheduler_init() MUST be called.
  /// @see    job_scheduler_init()
  /// @see    job_scheduler_service_add()
  int job_scheduler_service_remove(
    job_service_h job_service,
  ) {
    return _job_scheduler_service_remove(
      job_service,
    );
  }

  late final _job_scheduler_service_removePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(job_service_h)>>(
          'job_scheduler_service_remove');
  late final _job_scheduler_service_remove = _job_scheduler_service_removePtr
      .asFunction<int Function(job_service_h)>();
}

/// @brief Enumeration for job error.
/// @since_tizen 4.0
abstract class job_error_e {
  /// < Successful
  static const int JOB_ERROR_NONE = 0;

  /// < Invalid parameter
  static const int JOB_ERROR_INVALID_PARAMETER = -22;

  /// < Out of memory
  static const int JOB_ERROR_OUT_OF_MEMORY = -12;

  /// < IO error
  static const int JOB_ERROR_IO_ERROR = -5;

  /// < Not initialized
  static const int JOB_ERROR_NOT_INITIALIZED = -49938399;

  /// < No such job
  static const int JOB_ERROR_NO_SUCH_JOB = -49938398;

  /// < Already exist
  static const int JOB_ERROR_ALREADY_EXIST = -49938397;

  /// < Permission denied
  static const int JOB_ERROR_PERMISSION_DENIED = -13;

  /// < Not supported
  static const int JOB_ERROR_NOT_SUPPORTED = -1073741822;
}

/// @brief Enumeration for the job trigger events.
/// @since_tizen 4.0
abstract class job_trigger_event_e {
  /// < The battery level status: Empty
  static const int JOB_TRIGGER_EVENT_BATTERY_LEVEL_EMPTY = 0;

  /// < The battery level status: Critical
  static const int JOB_TRIGGER_EVENT_BATTERY_LEVEL_CRITICAL = 1;

  /// < The battery level status: Low
  static const int JOB_TRIGGER_EVENT_BATTERY_LEVEL_LOW = 2;

  /// < The battery level status: High
  static const int JOB_TRIGGER_EVENT_BATTERY_LEVEL_HIGH = 3;

  /// < The charger state: Connected
  static const int JOB_TRIGGER_EVENT_CHARGER_STATE_CONNECTED = 4;

  /// < The charger state: Disconnected
  static const int JOB_TRIGGER_EVENT_CHARGER_STATE_DISCONNECTED = 5;

  /// < The display state: On
  static const int JOB_TRIGGER_EVENT_DISPLAY_STATE_ON = 6;

  /// < The display state: Off
  static const int JOB_TRIGGER_EVENT_DISPLAY_STATE_OFF = 7;

  /// < The display state: Dim
  static const int JOB_TRIGGER_EVENT_DISPLAY_STATE_DIM = 8;

  /// < The earjack state: Connected
  static const int JOB_TRIGGER_EVENT_EARJACK_STATE_CONNECTED = 9;

  /// < The earjack state: Disconnected
  static const int JOB_TRIGGER_EVENT_EARJACK_STATE_DISCONNECTED = 10;

  /// < The GPS state: Disabled
  static const int JOB_TRIGGER_EVENT_GPS_STATE_DISABLED = 11;

  /// < The GPS state: Searching
  static const int JOB_TRIGGER_EVENT_GPS_STATE_SEARCHING = 12;

  /// < The GPS state: Connected
  static const int JOB_TRIGGER_EVENT_GPS_STATE_CONNECTED = 13;

  /// < The Power-saving mode: Enabled
  static const int JOB_TRIGGER_EVENT_POWERSAVE_MODE_ENABLED = 14;

  /// < The Power-saving mode: Disabled
  static const int JOB_TRIGGER_EVENT_POWERSAVE_MODE_DISABLED = 15;

  /// < The USB state: Connected
  static const int JOB_TRIGGER_EVENT_USB_STATE_CONNECTED = 16;

  /// < The USB state: Disconnected
  static const int JOB_TRIGGER_EVENT_USB_STATE_DISCONNECTED = 17;

  /// < The WiFi state: Disabled @n Privilege: %http://tizen.org/privilege/network.get
  static const int JOB_TRIGGER_EVENT_WIFI_STATE_DISABLED = 18;

  /// < The WiFi state: Disconnected @n Privilege: %http://tizen.org/privilege/network.get
  static const int JOB_TRIGGER_EVENT_WIFI_STATE_DISCONNECTED = 19;

  /// < The WiFi state: Connected @n Privilege: %http://tizen.org/privilege/network.get
  static const int JOB_TRIGGER_EVENT_WIFI_STATE_CONNECTED = 20;
}

final class job_info_s extends ffi.Opaque {}

/// @brief The job info handle.
/// @since_tizen 4.0
typedef job_info_h = ffi.Pointer<job_info_s>;

final class job_service_s extends ffi.Opaque {}

/// @brief The structure type containing the set of callback functions for handling jobs.
/// @details It is one of the input parameter of the job_scheduler_service_add() function.
/// @since_tizen 4.0
/// @see    job_scheduler_service_add()
/// @see    job_service_start_cb()
/// @see    job_service_stop_cb()
final class job_service_callback_s extends ffi.Struct {
  /// < This callback function is called at the start of the job.
  external job_service_start_cb start;

  /// < This callback function is called at the stop of the job.
  external job_service_stop_cb stop;
}

/// @brief Called when the job starts.
/// @since_tizen 4.0
/// @remarks The @a job_info MUST NOT be deallocated by the application.
/// The @a job_info is managed by the platform and is valid only in the callback.
/// @param[in]   job_info        The job info handle
/// @param[in]   user_data       The user data passed from the callback registration function
/// @see    job_scheduler_service_add()
/// @see    #job_service_callback_s
typedef job_service_start_cb
    = ffi.Pointer<ffi.NativeFunction<job_service_start_cbFunction>>;
typedef job_service_start_cbFunction = ffi.Void Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);
typedef Dartjob_service_start_cbFunction = void Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the job stops.
/// @since_tizen 4.0
/// @remarks The @a job_info MUST not be deallocated by the application.
/// The @a job_info is managed by the platform and is valid only in the callback.
/// @param[in]   job_info        The job info handle
/// @param[in]   user_data       The user data passed from the callback registration function
/// @see    job_scheduler_service_add()
/// @see    #job_service_callback_s
typedef job_service_stop_cb
    = ffi.Pointer<ffi.NativeFunction<job_service_stop_cbFunction>>;
typedef job_service_stop_cbFunction = ffi.Void Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);
typedef Dartjob_service_stop_cbFunction = void Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);

/// @brief Called to retrieve the job information.
/// @since_tizen 4.0
/// @remarks The @a job_info must not be deallocated by the application.
/// @param[in]   job_info        The job_info handle
/// @param[in]   user_data       The user data passed from the foreach function
/// @return @c true continue with the next iteration of the loop,
/// otherwise @c false to break out of the loop
/// @pre    job_scheduler_foreach_job() will invoke this callback.
/// @see    job_scheduler_foreach_job()
typedef job_scheduler_foreach_job_cb
    = ffi.Pointer<ffi.NativeFunction<job_scheduler_foreach_job_cbFunction>>;
typedef job_scheduler_foreach_job_cbFunction = ffi.Bool Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);
typedef Dartjob_scheduler_foreach_job_cbFunction = bool Function(
    job_info_h job_info, ffi.Pointer<ffi.Void> user_data);

/// @brief The job service handle.
/// @since_tizen 4.0
typedef job_service_h = ffi.Pointer<job_service_s>;
