/// {@category 6.5/tizen}
library tizen_interop_6_5.core_sync_client;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_accounts_svc.dart' as account;
import 'generated_bindings_bundle.dart' as bundle;

/// Dart bindings for Tizen core-sync-client APIs.
/// {@category 6.5/tizen}
class Tizen65CoreSyncClient {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen65CoreSyncClient(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen65CoreSyncClient.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Sets client (Sync Adapter) callback functions
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - This API only can be called by a service application. And it can be set by only one service application per a package.
  ///
  /// **Parameters:**
  /// - `on_start_cb` (in): A callback function to be called by Sync Manager for performing sync operation
  /// - `on_cancel_cb` (in): A callback function to be called by Sync Manager for cancelling sync operation
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SYNC_ERROR_IO_ERROR`: I/O error
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_QUOTA_EXCEEDED`: Quota exceeded
  /// - `SYNC_ERROR_SYSTEM`: System error
  ///
  /// **See also:**
  /// - `sync_adapter_start_sync_cb()`
  /// - `sync_adapter_cancel_sync_cb()`
  /// - `sync_adapter_unset_callbacks()`
  int sync_adapter_set_callbacks(
    sync_adapter_start_sync_cb on_start_cb,
    sync_adapter_cancel_sync_cb on_cancel_cb,
  ) {
    return _sync_adapter_set_callbacks(
      on_start_cb,
      on_cancel_cb,
    );
  }

  late final _sync_adapter_set_callbacksPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(sync_adapter_start_sync_cb,
              sync_adapter_cancel_sync_cb)>>('sync_adapter_set_callbacks');
  late final _sync_adapter_set_callbacks =
      _sync_adapter_set_callbacksPtr.asFunction<
          int Function(
              sync_adapter_start_sync_cb, sync_adapter_cancel_sync_cb)>();

  /// Unsets client (Sync Adapter) callback functions
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_SYSTEM`: System error
  ///
  /// **Preconditions:**
  /// - Call sync_adapter_set_callbacks() before calling this function.
  ///
  /// **See also:**
  /// - `sync_adapter_start_sync_cb()`
  /// - `sync_adapter_cancel_sync_cb()`
  /// - `sync_adapter_set_callbacks()`
  int sync_adapter_unset_callbacks() {
    return _sync_adapter_unset_callbacks();
  }

  late final _sync_adapter_unset_callbacksPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
          'sync_adapter_unset_callbacks');
  late final _sync_adapter_unset_callbacks =
      _sync_adapter_unset_callbacksPtr.asFunction<int Function()>();

  /// Requests Sync Manager to perform one time sync operation.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Parameters:**
  /// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
  /// - `sync_job_name` (in): A string representing a sync job which will be operated just one time
  /// - `sync_option` (in): sync options determine an way to operate sync job and can be used as ORing.
  /// - `sync_job_user_data` (in): User data which contains additional information related registered sync job or it can be `NULL` in the case of requesting without sync_job_user_data
  /// - `sync_job_id` (out): A unique value which can manage sync jobs. The number of sync job id is limited as less than a hundred.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_QUOTA_EXCEEDED`: Quota exceeded
  /// - `SYNC_ERROR_SYSTEM`: Internal system error
  /// - `SYNC_ERROR_SYNC_ADAPTER_NOT_FOUND`: Sync adapter is not registered
  ///
  /// **Preconditions:**
  /// - This function requires calling below Sync Adapter's APIs by a service application before it is called.
  /// - Call sync_adapter_set_callbacks() before calling this function.
  ///
  /// **See also:**
  /// - `sync_manager_remove_sync_job()`
  /// - `sync_option_e`
  int sync_manager_on_demand_sync_job(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    int sync_option,
    ffi.Pointer<bundle.bundle> sync_job_user_data,
    ffi.Pointer<ffi.Int> sync_job_id,
  ) {
    return _sync_manager_on_demand_sync_job(
      account,
      sync_job_name,
      sync_option,
      sync_job_user_data,
      sync_job_id,
    );
  }

  late final _sync_manager_on_demand_sync_jobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              account.account_h,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<bundle.bundle>,
              ffi.Pointer<ffi.Int>)>>('sync_manager_on_demand_sync_job');
  late final _sync_manager_on_demand_sync_job =
      _sync_manager_on_demand_sync_jobPtr.asFunction<
          int Function(account.account_h, ffi.Pointer<ffi.Char>, int,
              ffi.Pointer<bundle.bundle>, ffi.Pointer<ffi.Int>)>();

  /// Requests Sync Manager to perform periodic sync operations.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/alarm.set>
  ///
  /// **Remarks:**
  /// - Sync job can be added with its name. In the case of adding periodic sync job with same sync job, it will replace previous setting with new one.
  ///
  /// **Parameters:**
  /// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
  /// - `sync_job_name` (in): A string representing a sync job which will be operated with period interval
  /// - `sync_period` (in): Determines time interval of periodic sync. The periodic sync operation can be triggered in that interval, but it does not guarantee exact time. The minimum value is 30 minutes.
  /// - `sync_option` (in): sync options determine an way to operate sync job and can be used as ORing.
  /// - `sync_job_user_data` (in): User data which contains additional information related registered sync job or it can be `NULL` in the case of requesting without sync_job_user_data
  /// - `sync_job_id` (out): A unique value which can manage sync jobs. The number of sync job id is limited as less than a hundred.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_QUOTA_EXCEEDED`: Quota exceeded
  /// - `SYNC_ERROR_SYSTEM`: Internal system error
  /// - `SYNC_ERROR_SYNC_ADAPTER_NOT_FOUND`: Sync adapter is not registered
  ///
  /// **Preconditions:**
  /// - This function requires calling below Sync Adapter's APIs by a service application before it is called.
  /// - Call sync_adapter_set_callbacks() before calling this function.
  ///
  /// **See also:**
  /// - `sync_manager_remove_sync_job()`
  /// - `sync_option_e`
  /// - `sync_period_e`
  int sync_manager_add_periodic_sync_job(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    int sync_period,
    int sync_option,
    ffi.Pointer<bundle.bundle> sync_job_user_data,
    ffi.Pointer<ffi.Int> sync_job_id,
  ) {
    return _sync_manager_add_periodic_sync_job(
      account,
      sync_job_name,
      sync_period,
      sync_option,
      sync_job_user_data,
      sync_job_id,
    );
  }

  late final _sync_manager_add_periodic_sync_jobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              account.account_h,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Int32,
              ffi.Pointer<bundle.bundle>,
              ffi.Pointer<ffi.Int>)>>('sync_manager_add_periodic_sync_job');
  late final _sync_manager_add_periodic_sync_job =
      _sync_manager_add_periodic_sync_jobPtr.asFunction<
          int Function(account.account_h, ffi.Pointer<ffi.Char>, int, int,
              ffi.Pointer<bundle.bundle>, ffi.Pointer<ffi.Int>)>();

  /// Requests Sync Manager to perform sync operations whenever corresponding DB changed.
  ///
  /// since @if MOBILE 2.4 @endif http://tizen.org/privilege/contact.read is needed to add data change sync job for receiving notification with `SYNC_SUPPORTS_CAPABILITY_CONTACT.`
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/calendar.read since @if MOBILE 2.4 @endif>
  /// - <http://tizen.org/privilege/contact.read>
  ///
  /// **Remarks:**
  /// - Data change sync job can be added by using its capability. In the case of adding a sync job with same capability, it will replace previous setting with new one.
  /// - <http://tizen.org/privilege/calendar.read is needed to add data change sync job for receiving notification with `SYNC_SUPPORTS_CAPABILITY_CALENDAR.` This capability is supported on Mobile profile only.>
  ///
  /// **Parameters:**
  /// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
  /// - `sync_capability` (in): A string representing a sync job which will be operated whenever data change of this capability
  /// - `sync_option` (in): sync options determine an way to operate sync job and can be used as ORing.
  /// - `sync_job_user_data` (in): User data which contains additional information related registered sync job or it can be `NULL` in the case of requesting without sync_job_user_data
  /// - `sync_job_id` (out): A unique value which can manage sync jobs. The number of sync job id is limited as less than a hundred.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_QUOTA_EXCEEDED`: Quota exceeded
  /// - `SYNC_ERROR_SYSTEM`: Internal system error
  /// - `SYNC_ERROR_SYNC_ADAPTER_NOT_FOUND`: Sync adapter is not registered
  ///
  /// **Preconditions:**
  /// - This function requires calling below Sync Adapter's APIs by a service application before it is called.
  /// - Call sync_adapter_set_callbacks() before calling this function.
  ///
  /// **See also:**
  /// - `sync_manager_remove_sync_job()`
  /// - `sync_option_e`
  int sync_manager_add_data_change_sync_job(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_capability,
    int sync_option,
    ffi.Pointer<bundle.bundle> sync_job_user_data,
    ffi.Pointer<ffi.Int> sync_job_id,
  ) {
    return _sync_manager_add_data_change_sync_job(
      account,
      sync_capability,
      sync_option,
      sync_job_user_data,
      sync_job_id,
    );
  }

  late final _sync_manager_add_data_change_sync_jobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              account.account_h,
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<bundle.bundle>,
              ffi.Pointer<ffi.Int>)>>('sync_manager_add_data_change_sync_job');
  late final _sync_manager_add_data_change_sync_job =
      _sync_manager_add_data_change_sync_jobPtr.asFunction<
          int Function(account.account_h, ffi.Pointer<ffi.Char>, int,
              ffi.Pointer<bundle.bundle>, ffi.Pointer<ffi.Int>)>();

  /// Requests Sync Manager to remove corresponding sync job id.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - sync_job_id can not be `NULL`.
  ///
  /// **Parameters:**
  /// - `sync_job_id` (in): A unique value of each sync job, it can be used to search specific sync job and remove it
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_SYSTEM`: Internal system error
  ///
  /// **Preconditions:**
  /// - This function requires calling at least one of the below Sync Manager's APIs before it is called.
  /// - sync_manager_on_demand_sync_job()
  /// - sync_manager_add_periodic_sync_job()
  /// - sync_manager_add_data_change_sync_job()
  ///
  /// **See also:**
  /// - `sync_manager_on_demand_sync_job()`
  /// - `sync_manager_add_periodic_sync_job()`
  /// - `sync_manager_add_data_change_sync_job()`
  int sync_manager_remove_sync_job(
    int sync_job_id,
  ) {
    return _sync_manager_remove_sync_job(
      sync_job_id,
    );
  }

  late final _sync_manager_remove_sync_jobPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
          'sync_manager_remove_sync_job');
  late final _sync_manager_remove_sync_job =
      _sync_manager_remove_sync_jobPtr.asFunction<int Function(int)>();

  /// Requests Sync Manager to query corresponding sync request.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Parameters:**
  /// - `sync_job_cb` (in): A callback function for receiving the result of this API
  /// - `user_data` (in): User data which contains additional information related foreach job or `NULL` if do not want to transfer user data
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYNC_ERROR_NONE`: Successful
  /// - `SYNC_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SYNC_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `SYNC_ERROR_SYSTEM`: Internal system error
  ///
  /// **Preconditions:**
  /// - This function requires calling at least one of the below Sync Manager's APIs before it is called.
  /// - sync_manager_on_demand_sync_job()
  /// - sync_manager_add_periodic_sync_job()
  /// - sync_manager_add_data_change_sync_job()
  ///
  /// **See also:**
  /// - `sync_manager_sync_job_cb()`
  /// - `sync_manager_on_demand_sync_job()`
  /// - `sync_manager_add_periodic_sync_job()`
  /// - `sync_manager_add_data_change_sync_job()`
  int sync_manager_foreach_sync_job(
    sync_manager_sync_job_cb sync_job_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _sync_manager_foreach_sync_job(
      sync_job_cb,
      user_data,
    );
  }

  late final _sync_manager_foreach_sync_jobPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(sync_manager_sync_job_cb,
              ffi.Pointer<ffi.Void>)>>('sync_manager_foreach_sync_job');
  late final _sync_manager_foreach_sync_job =
      _sync_manager_foreach_sync_jobPtr.asFunction<
          int Function(sync_manager_sync_job_cb, ffi.Pointer<ffi.Void>)>();
}

/// Callback function for Sync Adapter's start sync request.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Remarks:**
/// - This API only can be called at a service application.
/// - `Release` account with account_destroy() after using it.
/// - `Release` sync_job_user_data with bundle_free() after using it.
///
/// **Parameters:**
/// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
/// - `sync_job_name` (in): A string representing a sync job which has been operated or `NULL` in the case of data change sync operation
/// - `sync_capability` (in): A string representing a sync job which has been operated because of data change or `NULL` in the case of on demand or periodic sync operation
/// - `sync_job_user_data` (in): User data which contains additional information related registered sync job
///
/// **Returns:**
/// - `true` if sync operation is success, `false` otherwise
///
/// **Preconditions:**
/// - The callback must be set by using sync_adapter_set_callbacks().
/// - sync_manager_on_demand_sync_job() calls this callback.
/// - sync_manager_add_periodic_sync_job() calls this callback.
/// - sync_manager_add_data_change_sync_job() calls this callback.
///
/// **See also:**
/// - `sync_adapter_set_callbacks()`
/// - `sync_manager_on_demand_sync_job()`
/// - `sync_manager_add_periodic_sync_job()`
/// - `sync_manager_add_data_change_sync_job()`
/// @nodoc
typedef sync_adapter_start_sync_cb
    = ffi.Pointer<ffi.NativeFunction<sync_adapter_start_sync_cbFunction>>;
/// @nodoc
typedef sync_adapter_start_sync_cbFunction = ffi.Bool Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    ffi.Pointer<bundle.bundle> sync_job_user_data);
/// @nodoc
typedef Dartsync_adapter_start_sync_cbFunction = bool Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    ffi.Pointer<bundle.bundle> sync_job_user_data);

/// Callback function for Sync Adapter's cancel sync request.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Remarks:**
/// - This API only can be called at a service application after calling sync_manager_remove_sync_job().
/// - `Release` account with account_destroy() after using it.
/// - `Release` sync_job_user_data with bundle_free() after using it.
///
/// **Parameters:**
/// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
/// - `sync_job_name` (in): A string representing a sync job which has been operated or `NULL` in the case of data change sync operation
/// - `sync_capability` (in): A string representing a sync job which has been operated because of data change or `NULL` in the case of on demand and periodic sync operation
/// - `sync_job_user_data` (in): User data which contains additional information related registered sync job
///
/// **Preconditions:**
/// - The callback must be set by using sync_adapter_set_callbacks().
/// - sync_manager_remove_sync_job() calls this callback in the case there is removable sync job.
///
/// **See also:**
/// - `sync_adapter_set_callbacks()`
/// - `sync_manager_remove_sync_job()`
/// @nodoc
typedef sync_adapter_cancel_sync_cb
    = ffi.Pointer<ffi.NativeFunction<sync_adapter_cancel_sync_cbFunction>>;
/// @nodoc
typedef sync_adapter_cancel_sync_cbFunction = ffi.Void Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    ffi.Pointer<bundle.bundle> sync_job_user_data);
/// @nodoc
typedef Dartsync_adapter_cancel_sync_cbFunction = void Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    ffi.Pointer<bundle.bundle> sync_job_user_data);

/// Enumerations for sync options of sync job request APIs.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
/// @nodoc
abstract class sync_option_e {
  /// < Sync job will be operated normally
  static const int SYNC_OPTION_NONE = 0;

  /// < Sync job will be operated as soon as possible
  static const int SYNC_OPTION_EXPEDITED = 1;

  /// < Sync job will not be performed again when it fails
  static const int SYNC_OPTION_NO_RETRY = 2;
}

/// Enumerations for time intervals of a periodic sync.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
/// @nodoc
abstract class sync_period_e {
  /// < Sync within 30 minutes
  static const int SYNC_PERIOD_INTERVAL_30MIN = 0;

  /// < Sync within 1 hour
  static const int SYNC_PERIOD_INTERVAL_1H = 1;

  /// < Sync within 2 hours
  static const int SYNC_PERIOD_INTERVAL_2H = 2;

  /// < Sync within 3 hours
  static const int SYNC_PERIOD_INTERVAL_3H = 3;

  /// < Sync within 6 hours
  static const int SYNC_PERIOD_INTERVAL_6H = 4;

  /// < Sync within 12 hours
  static const int SYNC_PERIOD_INTERVAL_12H = 5;

  /// < Sync within 1 day
  static const int SYNC_PERIOD_INTERVAL_1DAY = 6;
  static const int SYNC_PERIOD_INTERVAL_MAX = 7;
}

/// Called to get the information once for each sync job.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Remarks:**
/// - `Release` account with account_destroy() after using it.
/// - `Release` sync_job_user_data with bundle_free() after using it.
///
/// **Parameters:**
/// - `account` (in): An account handle on which sync operation was requested or `NULL` in the case of accountless sync operation
/// - `sync_job_name` (in): A string representing a sync job which has been operated or `NULL` in the case of data change sync operation
/// - `sync_capability` (in): A string representing a sync job which has been operated because of data change or `NULL` in the case of on demand and periodic sync operation
/// - `sync_job_id` (in): A unique value which can manage sync jobs
/// - `sync_job_user_data` (in): User data which contains additional information related registered sync job or it can be `NULL` in the case of requesting without sync_job_user_data
/// - `user_data` (in): User data which contains additional information related foreach job or it can be `NULL` in the case of querying without user_data
///
/// **Returns:**
/// - `true` to continue with the next iteration of the loop, otherwise `false` to break out of the loop
///
/// **Preconditions:**
/// - sync_manager_foreach_sync_job() calls this callback.
///
/// **See also:**
/// - `sync_adapter_set_callbacks()`
/// - `sync_manager_foreach_sync_job()`
/// @nodoc
typedef sync_manager_sync_job_cb
    = ffi.Pointer<ffi.NativeFunction<sync_manager_sync_job_cbFunction>>;
/// @nodoc
typedef sync_manager_sync_job_cbFunction = ffi.Bool Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    ffi.Int sync_job_id,
    ffi.Pointer<bundle.bundle> sync_job_user_data,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartsync_manager_sync_job_cbFunction = bool Function(
    account.account_h account,
    ffi.Pointer<ffi.Char> sync_job_name,
    ffi.Pointer<ffi.Char> sync_capability,
    int sync_job_id,
    ffi.Pointer<bundle.bundle> sync_job_user_data,
    ffi.Pointer<ffi.Void> user_data);

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_CALENDAR =
    'http://tizen.org/sync/capability/calendar';

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_CONTACT =
    'http://tizen.org/sync/capability/contact';

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_IMAGE =
    'http://tizen.org/sync/capability/image';

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_VIDEO =
    'http://tizen.org/sync/capability/video';

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_SOUND =
    'http://tizen.org/sync/capability/sound';

/// @nodoc
const String SYNC_SUPPORTS_CAPABILITY_MUSIC =
    'http://tizen.org/sync/capability/music';
