name: tizen_interop_callbacks_example
description: Demonstrates how to use the tizen_interop_callbacks plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_interop: ^0.2.6
  tizen_interop_callbacks:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
