name: tizen_interop_callbacks_example
description: Demonstrates how to use the tizen_interop_callbacks plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_interop: 
    path: ../../../
  tizen_interop_callbacks:
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
