name: tizen_interop_callbacks
description: Cross-thread callbacks for Tizen Native API
version: 0.1.0
repository: https://github.com/flutter-tizen/tizen_interop/tree/main/packages/callbacks

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  tizen_log: ^0.1.2
  tizen_interop: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: TizenInteropCallbacksPlugin
        fileName: tizen_interop_callbacks_plugin.h
