preamble: |
  // Copyright 2025 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.

name: 'tizen100Symbols'
output: 'lib/src/bindings/10.0/generated_symbols.dart'
library-path: 'rootstraps/10.0/usr/lib'

target-libraries:
  - libaccounts-svc.so.0                        # Account / Account Manager
  - libcore-sync-client.so.1                    # Account / Sync Manager
  - libcapi-appfw-application.so.0              # Application Framework / Application (include i18n)
  - libcapi-appfw-alarm.so.0                    # Application Framework / Application / Alarm
  - libcapi-appfw-app-common.so.0               # Application Framework / Application / App Common, Resource Manager
  - libcapi-appfw-app-control.so.0              # Application Framework / Application / App Control
  - libcapi-appfw-app-control-uri.so.0          # Application Framework / Application / App Control URI
  - libcapi-appfw-event.so.0                    # Application Framework / Application / Event
  - libcapi-appfw-app-manager.so.0              # Application Framework / Application Manager
  - libcapi-appfw-preference.so.0               # Application Framework / Application / Preference
  - libbundle.so.0                              # Application Framework / Bundle
  - libcapi-appfw-job-scheduler.so.0            # Application Framework / Application / Job scheduler
  - libmessage-port.so.1                        # Application Framework / Message Port
  - libnotification.so.0                        # Application Framework / Notification
  - libcapi-appfw-package-manager.so.0          # Application Framework / Package Manager
  - librpc-port.so.1                            # Application Framework / RPC Port
  - libappcore-agent.so.1                       # Application Framework / Service Application
  - libtizen-core.so.0                          # Application Framework / Tizen Core
  - libcapi-base-common.so.0                    # Base / Common Error
  - libcapi-web-url-download.so.0               # Content / Download
  - libcapi-content-media-content.so.0          # Content / Media Content
  - libcapi-content-mime-type.so.0              # Content / Mime Type
  - libcapi-location-manager.so.0               # Location / Location Manager
  - libcapi-ml-service.so.1                     # Machine Learning / Service
  - libcapi-ml-inference-single.so.1            # Machine Learning / Single
  - libcapi-nnstreamer.so.1                     # Machine Learning / Pipeline
  - libcapi-nntrainer.so                        # Machine Learning / Trainer
  - libpush.so.0                                # Messaging / Push
  - libcapi-media-audio-io.so.0                 # Multimedia / Audio I/O
  - libcapi-media-camera.so.0                   # Multimedia / Camera
  - libcapi-media-image-util.so.0               # Multimedia / Image Util
  - libcapi-media-codec.so.0                    # Multimedia / Media Codec
  - libcapi-media-controller.so.0               # Multimedia / Media Controller
  - libcapi-media-editor.so.0                   # Multimedia / Media Editor
  - libcapi-media-tool.so.0                     # Multimedia / Media Tool
  - libcapi-media-metadata-extractor.so         # Multimedia / Metadata Extractor
  - libmv_3d.so                                 # Multimedia / Media Vision 3D
  - libmv_common.so                             # Multimedia / Media Vision Common
  - libmv_face.so                               # Multimedia / Media Vision Face
  - libmv_face_recognition.so                   # Multimedia / Media Vision Face Recognition
  - libmv_landmark_detection.so                 # Multimedia / Media Vision Pose Landmark Detection
  - libmv_image.so                              # Multimedia / Media Vision Image
  - libmv_image_classification.so               # Multimedia / Media Vision Image Classification
  - libmv_inference.so                          # Multimedia / Media Vision Inference
  - libmv_object_detection.so                   # Multimedia / Media Vision Object Detection
  - libmv_roi_tracker.so                        # Multimedia / Media Vision Roi tracker
  - libmv_surveillance.so                       # Multimedia / Media Vision Surveillance
  - libcapi-media-player.so.0                   # Multimedia / Player
  - libcapi-media-radio.so.0                    # Multimeida / Radio
  - libcapi-media-recorder.so.0                 # Multimedia / Recorder
  - libcapi-media-screen-mirroring.so.0         # Multimedia / Screen Mirroring
  - libcapi-media-sound-manager.so.0            # Multimedia / Sound Manager
  - libcapi-media-sound-pool.so.0               # Multimedia / Sound Pool
  - libcapi-media-thumbnail-util.so             # Multimedia / Thumbnail Util
  - libcapi-media-tone-player.so.0              # Multimedia / Tone Player
  - libcapi-media-wav-player.so.0               # Multimedia / WAV Player
  - libcapi-media-webrtc.so.1                   # Multimedia / WebRTC
  - libcapi-network-bluetooth.so.0              # Network / Bluetooth
  - libnsd-dns-sd.so.0                          # Network / DNSSD
  - libcapi-network-inm.so.0                    # Network / Intelligent Network Monitoring
  - libiotcon.so.0                              # Network / IoTCon
  - libcapi-network-mtp.so.1                    # Network / MTP
  - libcapi-network-connection.so.1             # Network / Connection
  - libcapi-network-softap.so.0.1.0             # Network / SoftAP
  - libnsd-ssdp.so.0                            # Network / SSDP
  - libcapi-vpnsvc.so.1                         # Network / VPN Service
  - libcapi-network-wifi-aware.so.0             # Network / Wi-Fi Aware
  - libwifi-direct.so.1                         # Network / Wi-Fi Direct
  - libcapi-network-wifi-manager.so.1           # Network / WI-Fi Manager
  - libkey-manager-client.so.1                  # Security / Key Manager Client
  - libdevice-certificate-manager.so.2.0        # Security / Device Certificate Manager
  - libprivilege-info.so.1                      # Security / Privilege Info
  - libwebauthn-client.so.1                     # Security / Web Authentication
  - libyaca.so.0                                # Security / YACA
  - libphonenumber-utils.so.0                   # Social / Phonenumber utils
  - libcapi-system-device.so.0                  # System / Device
  - libdlog.so.0                                # System / Dlog
  - libfeedback.so.0                            # System / Feedback
  - libcapi-system-media-key.so.0               # System / Media key
  - libcapi-system-runtime-info.so.0            # System / Runtime information
  - libcapi-system-sensor.so.0                  # System / Sensor
  - libcapi-system-resource-monitor.so.0        # System / Monitor
  - libcapi-system-info.so.0                    # System / System Information
  - libcapi-system-system-settings.so.0         # System / System Settings
  - libupdate-control.so.1                      # System / Update Control
  - libcapi-system-usbhost.so.0                 # System / USB Host
  - libtbm.so.1                                 # UI / TBM Surface
  - libcapi-ui-autofill.so.0                    # UIX / Autofill
  - libcapi-ui-autofill-common.so.0             # UIX / Autofill common
  - libcapi-ui-autofill-manager.so.0            # UIX / Autofill manager
  - libcapi-ui-autofill-service.so.0            # UIX / Autofill service
  - libcapi-ui-inputmethod.so.0                 # UIX / Input Method
  - libcapi-ui-inputmethod-manager.so.0         # UIX / Input Method Manager
  - libmmi.so.2                                 # UIX / MMI
  - libma.so                                    # UIX / Multi assistant
  - libstt.so                                   # UIX / STT
  - libstt_engine.so                            # UIX / STT Engine
  - libtts.so                                   # UIX / TTS
  - libtts_engine.so                            # UIX / TTS Engine
  - libvc_engine.so                             # UIX / Voice control engine
  - libvc.so                                    # UIX / Voice control
  - libvc_manager.so                            # UIX / Voice control manager
