// Copyright 2024 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:symgen`.

final Map<String, List<String>> storageSymbols = {
  'libstorage.so.0.1': [
    'storage_foreach_device_supported',
    'storage_format_mmc',
    'storage_get_available_space',
    'storage_get_compat_internal_path',
    'storage_get_directory',
    'storage_get_external_memory_size',
    'storage_get_external_memory_size64',
    'storage_get_internal_memory_size',
    'storage_get_internal_memory_size64',
    'storage_get_origin_internal_path',
    'storage_get_primary_sdcard',
    'storage_get_root_directory',
    'storage_get_state',
    'storage_get_storage_level',
    'storage_get_total_space',
    'storage_get_type',
    'storage_get_type_dev',
    'storage_is_mounted_opt_usr',
    'storage_request_format_mmc',
    'storage_request_mount_mmc',
    'storage_request_unmount_mmc',
    'storage_set_changed_cb',
    'storage_set_state_changed_cb',
    'storage_unset_changed_cb',
    'storage_unset_state_changed_cb',
  ],
};
