// Copyright 2022 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:symgen`.

final Map<String, List<String>> capiContextSymbols = {
  'libcapi-context.so.1': [
    'context_history_create',
    'context_history_destroy',
    'context_history_filter_create',
    'context_history_filter_destroy',
    'context_history_filter_set_int',
    'context_history_filter_set_string',
    'context_history_get_list',
    'context_history_is_supported',
    'context_history_list_destroy',
    'context_history_list_get_count',
    'context_history_list_get_current',
    'context_history_list_move_first',
    'context_history_list_move_next',
    'context_history_record_destroy',
    'context_history_record_get_double',
    'context_history_record_get_int',
    'context_history_record_get_string',
    'context_trigger_add_rule',
    'context_trigger_custom_publish',
    'context_trigger_custom_register',
    'context_trigger_custom_unregister',
    'context_trigger_disable_rule',
    'context_trigger_enable_rule',
    'context_trigger_get_own_rule_ids',
    'context_trigger_get_rule_by_id',
    'context_trigger_remove_rule',
    'context_trigger_rule_add_entry',
    'context_trigger_rule_condition_create',
    'context_trigger_rule_condition_is_supported',
    'context_trigger_rule_create',
    'context_trigger_rule_custom_condition_create',
    'context_trigger_rule_custom_event_create',
    'context_trigger_rule_destroy',
    'context_trigger_rule_entry_add_comparison',
    'context_trigger_rule_entry_add_comparison_int',
    'context_trigger_rule_entry_add_comparison_string',
    'context_trigger_rule_entry_add_key',
    'context_trigger_rule_entry_add_option',
    'context_trigger_rule_entry_add_option_int',
    'context_trigger_rule_entry_add_option_string',
    'context_trigger_rule_entry_destroy',
    'context_trigger_rule_event_create',
    'context_trigger_rule_event_is_supported',
    'context_trigger_rule_get_description',
    'context_trigger_rule_set_action_app_control',
    'context_trigger_rule_set_action_notification',
    'context_trigger_rule_set_description',
  ],
};
