// Copyright 2022 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:symgen`.

final Map<String, List<String>> capiSystemInfoSymbols = {
  'libcapi-system-info.so.0': [
    'system_info_get_custom_bool',
    'system_info_get_custom_double',
    'system_info_get_custom_int',
    'system_info_get_custom_string',
    'system_info_get_custom_type',
    'system_info_get_platform_bool',
    'system_info_get_platform_double',
    'system_info_get_platform_int',
    'system_info_get_platform_string',
    'system_info_get_platform_type',
    'system_info_get_value_bool',
    'system_info_get_value_double',
    'system_info_get_value_int',
    'system_info_get_value_string',
  ],
};
