// Copyright 2026 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_capi_ml_common.dart' as ml_common;

/// Dart bindings for Tizen capi-ml-service APIs.
class Tizen70CapiMlService {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70CapiMlService(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70CapiMlService.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Sets the pipeline description with a given name.
  /// @since_tizen 7.0
  /// @remarks If the name already exists, the pipeline description is overwritten. Overwriting an existing description is restricted to APP/service that set it. However, users should keep their @a name unexposed to prevent unexpected overwriting.
  /// @param[in] name Unique name to retrieve the associated pipeline description.
  /// @param[in] pipeline_desc The pipeline description to be stored.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_IO_ERROR The operation of DB or filesystem has failed.
  ///
  /// Here is an example of the usage:
  /// @code
  /// const gchar my_pipeline[] = "videotestsrc is-live=true ! videoconvert ! tensor_converter ! tensor_sink async=false";
  /// gchar *pipeline;
  /// int status;
  /// ml_pipeline_h handle;
  ///
  /// // Set pipeline description.
  /// status = ml_service_set_pipeline ("my_pipeline", my_pipeline);
  /// if (status != ML_ERROR_NONE) {
  /// // handle error case
  /// goto error;
  /// }
  ///
  /// // Example to construct a pipeline with stored pipeline description.
  /// // Users may register intelligence pipelines for other processes and fetch such registered pipelines.
  /// // For example, a developer adds a pipeline which includes preprocessing and invoking a neural network model,
  /// // then an application can fetch and construct this for intelligence service.
  /// status = ml_service_get_pipeline ("my_pipeline", &pipeline);
  /// if (status != ML_ERROR_NONE) {
  /// // handle error case
  /// goto error;
  /// }
  ///
  /// status = ml_pipeline_construct (pipeline, NULL, NULL, &handle);
  /// if (status != ML_ERROR_NONE) {
  /// // handle error case
  /// goto error;
  /// }
  ///
  /// error:
  /// ml_pipeline_destroy (handle);
  /// g_free (pipeline);
  /// @endcode
  int ml_service_set_pipeline(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> pipeline_desc,
  ) {
    return _ml_service_set_pipeline(
      name,
      pipeline_desc,
    );
  }

  late final _ml_service_set_pipelinePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('ml_service_set_pipeline');
  late final _ml_service_set_pipeline = _ml_service_set_pipelinePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Gets the pipeline description with a given name.
  /// @since_tizen 7.0
  /// @remarks If the function succeeds, @a pipeline_desc must be released using g_free().
  /// @param[in] name The unique name to retrieve.
  /// @param[out] pipeline_desc The pipeline corresponding with the given name.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_IO_ERROR The operation of DB or filesystem has failed.
  int ml_service_get_pipeline(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Pointer<ffi.Char>> pipeline_desc,
  ) {
    return _ml_service_get_pipeline(
      name,
      pipeline_desc,
    );
  }

  late final _ml_service_get_pipelinePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('ml_service_get_pipeline');
  late final _ml_service_get_pipeline = _ml_service_get_pipelinePtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// @brief Deletes the pipeline description with a given name.
  /// @since_tizen 7.0
  /// @param[in] name The unique name to delete.
  /// @return @c 0 on success. Otherwise a negative error value.
  /// @note If the name does not exist in the database, this function returns ML_ERROR_NONE without any errors.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_IO_ERROR The operation of DB or filesystem has failed.
  int ml_service_delete_pipeline(
    ffi.Pointer<ffi.Char> name,
  ) {
    return _ml_service_delete_pipeline(
      name,
    );
  }

  late final _ml_service_delete_pipelinePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'ml_service_delete_pipeline');
  late final _ml_service_delete_pipeline = _ml_service_delete_pipelinePtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Launches the pipeline of given service and gets the service handle.
  /// @details This requests machine learning agent daemon to launch a new pipeline of given service. The pipeline of service @a name should be set.
  /// @since_tizen 7.0
  /// @remarks The @a handle should be destroyed using ml_service_destroy().
  /// @param[in] name The service name.
  /// @param[out] handle Newly created service handle is returned.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  /// @retval #ML_ERROR_IO_ERROR The operation of DB or filesystem has failed.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to launch the pipeline.
  int ml_service_launch_pipeline(
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ml_service_h> handle,
  ) {
    return _ml_service_launch_pipeline(
      name,
      handle,
    );
  }

  late final _ml_service_launch_pipelinePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ml_service_h>)>>('ml_service_launch_pipeline');
  late final _ml_service_launch_pipeline =
      _ml_service_launch_pipelinePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ml_service_h>)>();

  /// @brief Starts the pipeline of given service handle.
  /// @details This requests machine learning agent daemon to start the pipeline.
  /// @since_tizen 7.0
  /// @param[in] handle The service handle.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to start the pipeline.
  int ml_service_start_pipeline(
    ml_service_h handle,
  ) {
    return _ml_service_start_pipeline(
      handle,
    );
  }

  late final _ml_service_start_pipelinePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ml_service_h)>>(
          'ml_service_start_pipeline');
  late final _ml_service_start_pipeline =
      _ml_service_start_pipelinePtr.asFunction<int Function(ml_service_h)>();

  /// @brief Stops the pipeline of given service handle.
  /// @details This requests machine learning agent daemon to stop the pipeline.
  /// @since_tizen 7.0
  /// @param[in] handle The service handle.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to stop the pipeline.
  int ml_service_stop_pipeline(
    ml_service_h handle,
  ) {
    return _ml_service_stop_pipeline(
      handle,
    );
  }

  late final _ml_service_stop_pipelinePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ml_service_h)>>(
          'ml_service_stop_pipeline');
  late final _ml_service_stop_pipeline =
      _ml_service_stop_pipelinePtr.asFunction<int Function(ml_service_h)>();

  /// @brief Destroys the given service handle.
  /// @details If given service handle is created by ml_service_launch_pipeline(), this requests machine learning agent daemon to destroy the pipeline.
  /// @since_tizen 7.0
  /// @param[in] handle The service handle.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to access the pipeline state.
  int ml_service_destroy(
    ml_service_h handle,
  ) {
    return _ml_service_destroy(
      handle,
    );
  }

  late final _ml_service_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ml_service_h)>>(
          'ml_service_destroy');
  late final _ml_service_destroy =
      _ml_service_destroyPtr.asFunction<int Function(ml_service_h)>();

  /// @brief Gets the state of given handle's pipeline.
  /// @since_tizen 7.0
  /// @param[in] handle The service handle.
  /// @param[out] state The pipeline state.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to access the pipeline state.
  int ml_service_get_pipeline_state(
    ml_service_h handle,
    ffi.Pointer<ffi.Int32> state,
  ) {
    return _ml_service_get_pipeline_state(
      handle,
      state,
    );
  }

  late final _ml_service_get_pipeline_statePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_service_h,
              ffi.Pointer<ffi.Int32>)>>('ml_service_get_pipeline_state');
  late final _ml_service_get_pipeline_state = _ml_service_get_pipeline_statePtr
      .asFunction<int Function(ml_service_h, ffi.Pointer<ffi.Int32>)>();

  /// @brief Creates query service handle with given ml-option handle.
  /// @since_tizen 7.0
  /// @remarks The @a handle should be destroyed using ml_service_destroy().
  /// @param[in] option The option used for creating query service.
  /// @param[out] handle Newly created query service handle is returned.
  /// @return @c 0 on Success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Fail. The parameter is invalid.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  /// @retval #ML_ERROR_STREAMS_PIPE Failed to launch the pipeline.
  /// @retval #ML_ERROR_TRY_AGAIN The pipeline is not ready yet.
  int ml_service_query_create(
    ml_common.ml_option_h option,
    ffi.Pointer<ml_service_h> handle,
  ) {
    return _ml_service_query_create(
      option,
      handle,
    );
  }

  late final _ml_service_query_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ml_common.ml_option_h,
              ffi.Pointer<ml_service_h>)>>('ml_service_query_create');
  late final _ml_service_query_create = _ml_service_query_createPtr.asFunction<
      int Function(ml_common.ml_option_h, ffi.Pointer<ml_service_h>)>();

  /// @brief Requests the query service to process the @a input and produce an @a output.
  /// @since_tizen 7.0
  /// @param[in] handle The query service handle created by ml_service_query_create().
  /// @param[in] input The handle of input tensors.
  /// @param[out] output The handle of output tensors. The caller is responsible for freeing the allocated data with ml_tensors_data_destroy().
  /// @return 0 on success. Otherwise a negative error value.
  /// @retval #ML_ERROR_NONE Successful.
  /// @retval #ML_ERROR_NOT_SUPPORTED Not supported.
  /// @retval #ML_ERROR_INVALID_PARAMETER Given parameter is invalid.
  /// @retval #ML_ERROR_OUT_OF_MEMORY Failed to allocate required memory.
  /// @retval #ML_ERROR_STREAMS_PIPE The input is incompatible with the pipeline.
  /// @retval #ML_ERROR_TRY_AGAIN The pipeline is not ready yet.
  /// @retval #ML_ERROR_TIMED_OUT Failed to get output from the query service.
  int ml_service_query_request(
    ml_service_h handle,
    ml_common.ml_tensors_data_h input,
    ffi.Pointer<ml_common.ml_tensors_data_h> output,
  ) {
    return _ml_service_query_request(
      handle,
      input,
      output,
    );
  }

  late final _ml_service_query_requestPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ml_service_h, ml_common.ml_tensors_data_h,
                  ffi.Pointer<ml_common.ml_tensors_data_h>)>>(
      'ml_service_query_request');
  late final _ml_service_query_request =
      _ml_service_query_requestPtr.asFunction<
          int Function(ml_service_h, ml_common.ml_tensors_data_h,
              ffi.Pointer<ml_common.ml_tensors_data_h>)>();
}

/// @brief A handle for ml-service instance.
/// @since_tizen 7.0
typedef ml_service_h = ffi.Pointer<ffi.Void>;

/// @brief Enumeration for pipeline state.
/// @details The pipeline state is described on @ref CAPI_ML_NNSTREAMER_PIPELINE_STATE_DIAGRAM.
/// Refer to https://gstreamer.freedesktop.org/documentation/plugin-development/basics/states.html.
/// @since_tizen 5.5
abstract class _ml_pipeline_state_e {
  /// < Unknown state. Maybe not constructed?
  static const int ML_PIPELINE_STATE_UNKNOWN = 0;

  /// < GST-State "Null"
  static const int ML_PIPELINE_STATE_NULL = 1;

  /// < GST-State "Ready"
  static const int ML_PIPELINE_STATE_READY = 2;

  /// < GST-State "Paused"
  static const int ML_PIPELINE_STATE_PAUSED = 3;

  /// < GST-State "Playing"
  static const int ML_PIPELINE_STATE_PLAYING = 4;
}
