/// {@category 7.0/tizen}
library tizen_interop_7_0.capi_system_info;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen capi-system-info APIs.
/// {@category 7.0/tizen}
class Tizen70CapiSystemInfo {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70CapiSystemInfo(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70CapiSystemInfo.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Gets the boolean value of the `platform` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the platform feature to get
  /// - `value` (out): The value of the given platform feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_platform_bool(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _system_info_get_platform_bool(
      key,
      value,
    );
  }

  late final _system_info_get_platform_boolPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Bool>)>>('system_info_get_platform_bool');
  late final _system_info_get_platform_bool = _system_info_get_platform_boolPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Bool>)>();

  /// Gets the integer value of the `platform` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the platform feature to get
  /// - `value` (out): The value of the given platform feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_platform_int(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Int> value,
  ) {
    return _system_info_get_platform_int(
      key,
      value,
    );
  }

  late final _system_info_get_platform_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int>)>>('system_info_get_platform_int');
  late final _system_info_get_platform_int = _system_info_get_platform_intPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)>();

  /// Gets the double value of the `platform` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the platform feature to get
  /// - `value` (out): The value of the given platform feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_platform_double(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Double> value,
  ) {
    return _system_info_get_platform_double(
      key,
      value,
    );
  }

  late final _system_info_get_platform_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Double>)>>('system_info_get_platform_double');
  late final _system_info_get_platform_double =
      _system_info_get_platform_doublePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Double>)>();

  /// Gets the string value of the `platform` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Remarks:**
  /// - You must release the `value` using free().
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the platform feature to get
  /// - `value` (out): The value of the given platform feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_platform_string(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  ) {
    return _system_info_get_platform_string(
      key,
      value,
    );
  }

  late final _system_info_get_platform_stringPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'system_info_get_platform_string');
  late final _system_info_get_platform_string =
      _system_info_get_platform_stringPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the boolean value of the `custom` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the custom feature to get. NOTE: This custom function uses a custom key which is provided by OEM's
  /// - `value` (out): The value of the given custom feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_custom_bool(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _system_info_get_custom_bool(
      key,
      value,
    );
  }

  late final _system_info_get_custom_boolPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Bool>)>>('system_info_get_custom_bool');
  late final _system_info_get_custom_bool = _system_info_get_custom_boolPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Bool>)>();

  /// Gets the integer value of the `custom` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the custom feature to get. NOTE: This custom function uses a custom key which is provided by OEM's
  /// - `value` (out): The value of the given custom feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot the find `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_custom_int(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Int> value,
  ) {
    return _system_info_get_custom_int(
      key,
      value,
    );
  }

  late final _system_info_get_custom_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int>)>>('system_info_get_custom_int');
  late final _system_info_get_custom_int = _system_info_get_custom_intPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int>)>();

  /// Gets the double value of the `custom` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the custom feature to get. NOTE: This custom function uses a custom key which is provided by OEM's
  /// - `value` (out): The value of the given custom feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_custom_double(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Double> value,
  ) {
    return _system_info_get_custom_double(
      key,
      value,
    );
  }

  late final _system_info_get_custom_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Double>)>>('system_info_get_custom_double');
  late final _system_info_get_custom_double =
      _system_info_get_custom_doublePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Double>)>();

  /// Gets the string value of the `custom` feature.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Remarks:**
  /// - You must release the `value` using free().
  ///
  /// **Parameters:**
  /// - `key` (in): The name of the custom feature to get. NOTE: This custom function uses a custom key which is provided by OEM's
  /// - `value` (out): The value of the given custom feature
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SYSTEM_INFO_ERROR_NONE`: Successful
  /// - `SYSTEM_INFO_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SYSTEM_INFO_ERROR_INVALID_PARAMETER`: Cannot find the `key` in the model config file
  /// - `SYSTEM_INFO_ERROR_IO_ERROR`: An input/output error occurred while reading the `value` from the model config file
  /// - `SYSTEM_INFO_ERROR_PERMISSION_DENIED`: No permission to use the API
  int system_info_get_custom_string(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  ) {
    return _system_info_get_custom_string(
      key,
      value,
    );
  }

  late final _system_info_get_custom_stringPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'system_info_get_custom_string');
  late final _system_info_get_custom_string =
      _system_info_get_custom_stringPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Do not use it. It will be removed.
  int system_info_get_value_int(
    int key,
    ffi.Pointer<ffi.Int> value,
  ) {
    return _system_info_get_value_int(
      key,
      value,
    );
  }

  late final _system_info_get_value_intPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int32, ffi.Pointer<ffi.Int>)>>(
      'system_info_get_value_int');
  late final _system_info_get_value_int = _system_info_get_value_intPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Int>)>();

  /// Do not use it. It will be removed.
  int system_info_get_value_bool(
    int key,
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _system_info_get_value_bool(
      key,
      value,
    );
  }

  late final _system_info_get_value_boolPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Int32, ffi.Pointer<ffi.Bool>)>>(
      'system_info_get_value_bool');
  late final _system_info_get_value_bool = _system_info_get_value_boolPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Bool>)>();

  /// Do not use it. It will be removed.
  int system_info_get_value_double(
    int key,
    ffi.Pointer<ffi.Double> value,
  ) {
    return _system_info_get_value_double(
      key,
      value,
    );
  }

  late final _system_info_get_value_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int32,
              ffi.Pointer<ffi.Double>)>>('system_info_get_value_double');
  late final _system_info_get_value_double = _system_info_get_value_doublePtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Double>)>();

  /// Do not use it. It will be removed.
  int system_info_get_value_string(
    int key,
    ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  ) {
    return _system_info_get_value_string(
      key,
      value,
    );
  }

  late final _system_info_get_value_stringPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Int32, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'system_info_get_value_string');
  late final _system_info_get_value_string = _system_info_get_value_stringPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// It is not decided if it should be opened to public.
  int system_info_get_platform_type(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Int32> type,
  ) {
    return _system_info_get_platform_type(
      key,
      type,
    );
  }

  late final _system_info_get_platform_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int32>)>>('system_info_get_platform_type');
  late final _system_info_get_platform_type =
      _system_info_get_platform_typePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>)>();

  /// It is not decided if it should be opened to public.
  int system_info_get_custom_type(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Int32> type,
  ) {
    return _system_info_get_custom_type(
      key,
      type,
    );
  }

  late final _system_info_get_custom_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Int32>)>>('system_info_get_custom_type');
  late final _system_info_get_custom_type =
      _system_info_get_custom_typePtr.asFunction<
          int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>)>();
}

/// Enumeration for system information error codes.
/// @nodoc
abstract class system_info_error_e {
  /// < Successful
  static const int SYSTEM_INFO_ERROR_NONE = 0;

  /// < Invalid parameter
  static const int SYSTEM_INFO_ERROR_INVALID_PARAMETER = -22;

  /// < Out of memory
  static const int SYSTEM_INFO_ERROR_OUT_OF_MEMORY = -12;

  /// < An input/output error occurred when reading value from system
  static const int SYSTEM_INFO_ERROR_IO_ERROR = -5;

  /// < No permission to use the API
  static const int SYSTEM_INFO_ERROR_PERMISSION_DENIED = -13;

  /// < Not supported parameter (Since 3.0)
  static const int SYSTEM_INFO_ERROR_NOT_SUPPORTED = -1073741822;
}

/// It is not decided if it should be opened to public.
/// @nodoc
abstract class system_info_type_e {
  static const int SYSTEM_INFO_TYPE_MIN = 0;
  static const int SYSTEM_INFO_BOOL = 0;
  static const int SYSTEM_INFO_INT = 1;
  static const int SYSTEM_INFO_DOUBLE = 2;
  static const int SYSTEM_INFO_STRING = 3;
  static const int SYSTEM_INFO_TYPE_MAX = 4;
}

/// Enumeration for system information key.
/// @nodoc
abstract class system_info_key_e {
  /// < @internal The model of the device
  static const int SYSTEM_INFO_KEY_MODEL = 0;

  /// < @internal The version of the Tizen API
  static const int SYSTEM_INFO_KEY_TIZEN_VERSION = 1;

  /// < @internal The name of platform
  static const int SYSTEM_INFO_KEY_PLATFORM_NAME = 2;

  /// < @internal The name of tizen version
  static const int SYSTEM_INFO_KEY_TIZEN_VERSION_NAME = 3;

  /// < @internal The manufacturer of the device
  static const int SYSTEM_INFO_KEY_MANUFACTURER = 4;

  /// < @internal The CORE CPU architecture of model
  static const int SYSTEM_INFO_KEY_CORE_CPU_ARCH = 5;

  /// < @internal The CORE CPU frequency of model
  static const int SYSTEM_INFO_KEY_CORE_CPU_FREQ = 6;

  /// < @internal The build string of platform binary
  static const int SYSTEM_INFO_KEY_BUILD_STRING = 7;

  /// < @internal The build date of platform binary
  static const int SYSTEM_INFO_KEY_BUILD_DATE = 8;

  /// < @internal The build time of platform binary
  static const int SYSTEM_INFO_KEY_BUILD_TIME = 9;

  /// < @internal The height of the screen in pixels
  static const int SYSTEM_INFO_KEY_SCREEN_HEIGHT = 10;

  /// < @internal The width of the screen in pixels
  static const int SYSTEM_INFO_KEY_SCREEN_WIDTH = 11;

  /// < @internal The physical screen height in millimeters
  static const int SYSTEM_INFO_KEY_PHYSICAL_SCREEN_HEIGHT = 12;

  /// < @internal The physical screen width in millimeters
  static const int SYSTEM_INFO_KEY_PHYSICAL_SCREEN_WIDTH = 13;

  /// < @internal Indicates whether the device supports tethering
  static const int SYSTEM_INFO_KEY_TETHERING_SUPPORTED = 14;
}
