/// {@category 7.0/tizen}
library tizen_interop_7_0.capi_media_thumbnail_util;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen capi-media-thumbnail-util APIs.
/// {@category 7.0/tizen}
class Tizen70CapiMediaThumbnailUtil {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70CapiMediaThumbnailUtil(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70CapiMediaThumbnailUtil.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// **Deprecated:** Deprecated since 5.0.
  ///
  /// Creates thumbnail info handle.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - The `thumb` info should be released using thumbnail_util_destroy().
  ///
  /// **Parameters:**
  /// - `thumb` (in): The handle to thumbnail info
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `THUMBNAIL_UTIL_ERROR_OUT_OF_MEMORY`: Out of memory
  ///
  /// **See also:**
  /// - `thumbnail_util_destroy()`
  int thumbnail_util_create(
    ffi.Pointer<thumbnail_h> thumb,
  ) {
    return _thumbnail_util_create(
      thumb,
    );
  }

  late final _thumbnail_util_createPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<thumbnail_h>)>>(
          'thumbnail_util_create');
  late final _thumbnail_util_create = _thumbnail_util_createPtr
      .asFunction<int Function(ffi.Pointer<thumbnail_h>)>();

  /// **Deprecated:** Deprecated since 5.0. Use thumbnail_util_extract_to_file() or thumbnail_util_extract_to_buffer() instead.
  ///
  /// Extracts the thumbnail for the given media, asynchronously.
  ///
  /// This function extracts the thumbnail for given media item and calls registered callback function for completion of extracting the thumbnail. You can distinguish generated thumbnails by `request_id`. Therefore, the `request_id` must be maintained until the request is completed. And the `request_id` is also used to cancel the request.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - The `request_id` should be released using free().
  /// - <http://tizen.org/privilege/mediastorage is needed if input or output path are relevant to media storage.>
  /// - <http://tizen.org/privilege/externalstorage is needed if input or output path are relevant to external storage.>
  /// - If you don't set the size, the thumbnail size will be set default size. Default size is 320x240.
  /// - Color space of the generated thumbnail is BGRA.
  /// - Since 3.0, http://tizen.org/privilege/content.write privilege is not required.
  ///
  /// **Parameters:**
  /// - `thumb` (in): The thumbnail info handle
  /// - `callback` (in): The callback function to be invoked
  /// - `user_data` (in): The user data to be passed to the callback function
  /// - `request_id` (out): The request id for the thumbnail extraction request
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `THUMBNAIL_UTIL_ERROR_PERMISSION_DENIED`: Permission denied
  ///
  /// **Preconditions:**
  /// - Create a thumbnail info handle by calling thumbnail_util_create(). The content path that you want to generate thumbnail must be set by calling thumbnail_util_set_path().
  ///
  /// **Postconditions:**
  /// - Thumbnail extraction result except canceled is provided by thumbnail_extracted_cb().
  ///
  /// **See also:**
  /// - `thumbnail_util_create()`
  /// - `thumbnail_util_set_path()`
  /// - `thumbnail_util_set_size()`
  /// - `thumbnail_extracted_cb()`
  /// - `thumbnail_util_cancel()`
  /// - `thumbnail_util_destroy()`
  int thumbnail_util_extract(
    thumbnail_h thumb,
    thumbnail_extracted_cb callback,
    ffi.Pointer<ffi.Void> user_data,
    ffi.Pointer<ffi.Pointer<ffi.Char>> request_id,
  ) {
    return _thumbnail_util_extract(
      thumb,
      callback,
      user_data,
      request_id,
    );
  }

  late final _thumbnail_util_extractPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              thumbnail_h,
              thumbnail_extracted_cb,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('thumbnail_util_extract');
  late final _thumbnail_util_extract = _thumbnail_util_extractPtr.asFunction<
      int Function(thumbnail_h, thumbnail_extracted_cb, ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// **Deprecated:** Deprecated since 5.0.
  ///
  /// Sets the path of original media file.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Parameters:**
  /// - `thumb` (in): The thumbnail info handle
  /// - `path` (in): The path of the original media file
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - Create a thumbnail info handle by calling thumbnail_util_create().
  ///
  /// **See also:**
  /// - `thumbnail_util_create()`
  /// - `thumbnail_util_set_size()`
  /// - `thumbnail_util_destroy()`
  int thumbnail_util_set_path(
    thumbnail_h thumb,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _thumbnail_util_set_path(
      thumb,
      path,
    );
  }

  late final _thumbnail_util_set_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              thumbnail_h, ffi.Pointer<ffi.Char>)>>('thumbnail_util_set_path');
  late final _thumbnail_util_set_path = _thumbnail_util_set_pathPtr
      .asFunction<int Function(thumbnail_h, ffi.Pointer<ffi.Char>)>();

  /// **Deprecated:** Deprecated since 5.0.
  ///
  /// Sets the size of thumbnail to be extracted.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - If you don't set the size, the thumbnail size will be set default size. Default size is 320x240.
  /// - If the set width is not a multiple of 8, it can be changed by inner process. the width will be a multiple of 8 greater than the set value.
  ///
  /// **Parameters:**
  /// - `thumb` (in): The thumbnail info handle
  /// - `width` (in): The width of the thumbnail
  /// - `height` (in): The height of the thumbnail
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - Create a thumbnail info handle by calling thumbnail_util_create().
  ///
  /// **See also:**
  /// - `thumbnail_util_create()`
  /// - `thumbnail_util_set_path()`
  /// - `thumbnail_util_destroy()`
  int thumbnail_util_set_size(
    thumbnail_h thumb,
    int width,
    int height,
  ) {
    return _thumbnail_util_set_size(
      thumb,
      width,
      height,
    );
  }

  late final _thumbnail_util_set_sizePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(thumbnail_h, ffi.Int, ffi.Int)>>(
      'thumbnail_util_set_size');
  late final _thumbnail_util_set_size = _thumbnail_util_set_sizePtr
      .asFunction<int Function(thumbnail_h, int, int)>();

  /// **Deprecated:** Deprecated since 5.0.
  ///
  /// Cancels the thumbnail extraction request for the given media.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Remarks:**
  /// - If there is no request to be canceled, this function returns `THUMBNAIL_UTIL_ERROR_INVALID_OPERATION`
  ///
  /// **Parameters:**
  /// - `thumb` (in): The media thumbnail info handle
  /// - `request_id` (in): The generated request id by thumbnail extraction request
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - It is available before thumbnail_extracted_cb() is called.
  ///
  /// **See also:**
  /// - `thumbnail_util_extract()`
  int thumbnail_util_cancel(
    thumbnail_h thumb,
    ffi.Pointer<ffi.Char> request_id,
  ) {
    return _thumbnail_util_cancel(
      thumb,
      request_id,
    );
  }

  late final _thumbnail_util_cancelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              thumbnail_h, ffi.Pointer<ffi.Char>)>>('thumbnail_util_cancel');
  late final _thumbnail_util_cancel = _thumbnail_util_cancelPtr
      .asFunction<int Function(thumbnail_h, ffi.Pointer<ffi.Char>)>();

  /// **Deprecated:** Deprecated since 5.0.
  ///
  /// Destroys thumbnail info handle.
  ///
  /// The function frees all resources related to the thumbnail info handle. This handle can no longer be used to perform any operations. New thumbnail info handle has to be created before the next usage.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.4; Wearable 3.0
  ///
  /// **Parameters:**
  /// - `thumb` (in): The thumbnail info handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  ///
  /// **Preconditions:**
  /// - Create a thumbnail info handle by calling thumbnail_util_create().
  ///
  /// **See also:**
  /// - `thumbnail_util_create()`
  int thumbnail_util_destroy(
    thumbnail_h thumb,
  ) {
    return _thumbnail_util_destroy(
      thumb,
    );
  }

  late final _thumbnail_util_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(thumbnail_h)>>(
          'thumbnail_util_destroy');
  late final _thumbnail_util_destroy =
      _thumbnail_util_destroyPtr.asFunction<int Function(thumbnail_h)>();

  /// Extracts the thumbnail for the given media into a file, synchronously.
  ///
  /// This function creates thumbnail from a given media file. The generated thumbnail is saved in the given thumbnail path. The format of the thumbnail file is determined by the extension of the thumbnail path (e.g. path is input.jpg and thumbnail_path is thumbnail.png then thumbnail.png is encoded in the PNG format). If the extension is missing or the format is not supported, the thumbnail is encoded in the same format as the given media (e.g. path is input.jpg and thumbnail_path is thumbnail.out then thumbnail.out is encoded in the JPEG format). Supported image formats are as follows:
  /// - GIF, JPEG, PNG, BMP, WBMP Video files only support JPEG format thumbnail.
  ///
  /// **Since Tizen:**
  /// - 5.0
  ///
  /// **Remarks:**
  /// - <http://tizen.org/privilege/mediastorage is needed if input or output path points to media storage.>
  /// - <http://tizen.org/privilege/externalstorage is needed if input or output path points to external storage.>
  /// - The width and height of the thumbnail to be generated cannot exceed 2000.
  /// - The width and height of the thumbnail to be generated cannot exceed the original resolution.
  /// - Since 5.5, if the width and height of the thumbnail to be generated exceeds the original resolution, the value changes to the original resolution.
  /// - In order to maintain the ratio, the requested size and generated size may be different. (Modify based on short axis)
  /// - If the parent directory of the thumbnail path to be generated does not exist, an error is returned.
  ///
  /// **Parameters:**
  /// - `path` (in): The path of the original media file
  /// - `width` (in): The width of the thumbnail
  /// - `height` (in): The height of the thumbnail
  /// - `thumbnail_path` (in): The path to save the generated thumbnail
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_OPERATION`: Invalid operation
  /// - `THUMBNAIL_UTIL_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `THUMBNAIL_UTIL_ERROR_PERMISSION_DENIED`: Permission denied
  int thumbnail_util_extract_to_file(
    ffi.Pointer<ffi.Char> path,
    int width,
    int height,
    ffi.Pointer<ffi.Char> thumbnail_path,
  ) {
    return _thumbnail_util_extract_to_file(
      path,
      width,
      height,
      thumbnail_path,
    );
  }

  late final _thumbnail_util_extract_to_filePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.UnsignedInt,
              ffi.UnsignedInt,
              ffi.Pointer<ffi.Char>)>>('thumbnail_util_extract_to_file');
  late final _thumbnail_util_extract_to_file =
      _thumbnail_util_extract_to_filePtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>, int, int, ffi.Pointer<ffi.Char>)>();

  /// Extracts the thumbnail for the given media into a buffer, synchronously.
  ///
  /// This function creates thumbnails from a given media file. The generated thumbnail is returned as a raw data stream.
  ///
  /// **Since Tizen:**
  /// - 5.0
  ///
  /// **Remarks:**
  /// - <http://tizen.org/privilege/mediastorage is needed if input or output path points to media storage.>
  /// - <http://tizen.org/privilege/externalstorage is needed if input or output path points to external storage.>
  /// - The width and height of the thumbnail to be generated cannot exceed 2000.
  /// - The width and height of the thumbnail to be generated cannot exceed the original resolution.
  /// - In the case of video file, color space of the generated thumbnail is RGB.
  /// - In the case of image file, color space of the generated thumbnail is BGRA.
  /// - The `thumb_buffer` should be released using free().
  /// - Since 5.5, if the width and height of the thumbnail to be generated exceeds the original resolution, the value changes to the original resolution.
  /// - In order to maintain the ratio, the requested size and generated size may be different. (Modify based on short axis)
  ///
  /// **Parameters:**
  /// - `path` (in): The path of the original media file
  /// - `width` (in): The width of the thumbnail
  /// - `height` (in): The height of the thumbnail
  /// - `thumb_buffer` (out): The raw data of the thumbnail which is generated
  /// - `thumb_size` (out): The size of the thumbnail which is generated
  /// - `thumb_width` (out): The width of the thumbnail which is generated
  /// - `thumb_height` (out): The height of the thumbnail which is generated
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `THUMBNAIL_UTIL_ERROR_NONE`: Successful
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `THUMBNAIL_UTIL_ERROR_INVALID_OPERATION`: Invalid operation
  /// - `THUMBNAIL_UTIL_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `THUMBNAIL_UTIL_ERROR_PERMISSION_DENIED`: Permission denied
  int thumbnail_util_extract_to_buffer(
    ffi.Pointer<ffi.Char> path,
    int width,
    int height,
    ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>> thumb_buffer,
    ffi.Pointer<ffi.Size> thumb_size,
    ffi.Pointer<ffi.UnsignedInt> thumb_width,
    ffi.Pointer<ffi.UnsignedInt> thumb_height,
  ) {
    return _thumbnail_util_extract_to_buffer(
      path,
      width,
      height,
      thumb_buffer,
      thumb_size,
      thumb_width,
      thumb_height,
    );
  }

  late final _thumbnail_util_extract_to_bufferPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  ffi.Pointer<ffi.Char>,
                  ffi.UnsignedInt,
                  ffi.UnsignedInt,
                  ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
                  ffi.Pointer<ffi.Size>,
                  ffi.Pointer<ffi.UnsignedInt>,
                  ffi.Pointer<ffi.UnsignedInt>)>>(
      'thumbnail_util_extract_to_buffer');
  late final _thumbnail_util_extract_to_buffer =
      _thumbnail_util_extract_to_bufferPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>,
              int,
              int,
              ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>,
              ffi.Pointer<ffi.Size>,
              ffi.Pointer<ffi.UnsignedInt>,
              ffi.Pointer<ffi.UnsignedInt>)>();
}

/// Enumeration for a thumbnail util error.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Group:**
/// - CAPI_MEDIA_THUMBNAIL_UTIL_MODULE
/// @nodoc
abstract class thumbnail_util_error_e {
  /// < Successful
  static const int THUMBNAIL_UTIL_ERROR_NONE = 0;

  /// < Invalid parameter
  static const int THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER = -22;

  /// < Out of memory
  static const int THUMBNAIL_UTIL_ERROR_OUT_OF_MEMORY = -12;

  /// < Invalid Operation
  static const int THUMBNAIL_UTIL_ERROR_INVALID_OPERATION = -38;

  /// < No space left on device
  static const int THUMBNAIL_UTIL_ERROR_FILE_NO_SPACE_ON_DEVICE = -28;

  /// < Permission denied
  static const int THUMBNAIL_UTIL_ERROR_PERMISSION_DENIED = -13;

  /// < Unsupported Content (Since 4.0)
  static const int THUMBNAIL_UTIL_ERROR_UNSUPPORTED_CONTENT = -49872895;
}

/// @nodoc
final class thumbnail_s extends ffi.Opaque {}

/// **Deprecated:** Deprecated since 5.0.
///
/// The structure type for the thumbnail info handle.
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Group:**
/// - CAPI_MEDIA_THUMBNAIL_UTIL_MODULE
/// @nodoc
typedef thumbnail_h = ffi.Pointer<thumbnail_s>;

/// **Deprecated:** Deprecated since 5.0.
///
/// Called when creating the thumbnail.
///
/// This callback is called for completion of generating the thumbnail. The following error codes can be received: `THUMBNAIL_UTIL_ERROR_NONE` : Successful `THUMBNAIL_UTIL_ERROR_INVALID_PARAMETER` : Invalid parameter `THUMBNAIL_UTIL_ERROR_PERMISSION_DENIED` : Permission denied
///
/// **Since Tizen:**
/// - Mobile 2.4; Wearable 3.0
///
/// **Remarks:**
/// - Color space of the generated thumbnail is BGRA.
/// - The callback is called in a separate thread(not in the main loop).
/// - The `thumb_data` should be released using free().
///
/// **Parameters:**
/// - `error` (in): The error code
/// - `request_id` (in): The generated request id by thumbnail extraction request
/// - `thumb_width` (in): The width of the thumbnail which is generated
/// - `thumb_height` (in): The height of the thumbnail which is generated
/// - `thumb_data` (in): The raw data of the thumbnail which is generated
/// - `thumb_size` (in): The size of the thumbnail which is generated
/// - `user_data` (in): The user data passed from the thumbnail_util_extract() function
///
/// **Preconditions:**
/// - thumbnail_util_extract() calls this callback.
///
/// **See also:**
/// - `thumbnail_util_extract()`
///
/// **Group:**
/// - CAPI_MEDIA_THUMBNAIL_UTIL_MODULE
/// @nodoc
typedef thumbnail_extracted_cb
    = ffi.Pointer<ffi.NativeFunction<thumbnail_extracted_cbFunction>>;
/// @nodoc
typedef thumbnail_extracted_cbFunction = ffi.Void Function(
    ffi.Int32 error,
    ffi.Pointer<ffi.Char> request_id,
    ffi.Int thumb_width,
    ffi.Int thumb_height,
    ffi.Pointer<ffi.UnsignedChar> thumb_data,
    ffi.Int thumb_size,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartthumbnail_extracted_cbFunction = void Function(
    int error,
    ffi.Pointer<ffi.Char> request_id,
    int thumb_width,
    int thumb_height,
    ffi.Pointer<ffi.UnsignedChar> thumb_data,
    int thumb_size,
    ffi.Pointer<ffi.Void> user_data);

/// @nodoc
const int THUMBNAIL_UTIL_ERROR_CLASS = -49872896;
