// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen cbhm APIs.
class Tizen70Cbhm {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70Cbhm(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70Cbhm.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Creates and initializes clipboard handle.
  /// @since_tizen 3.0
  /// @param[out] cbhm_handle Clipboard handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_OUT_OF_MEMORY Out of memory
  /// @see cbhm_close_service()
  int cbhm_open_service(
    ffi.Pointer<cbhm_h> cbhm_handle,
  ) {
    return _cbhm_open_service(
      cbhm_handle,
    );
  }

  late final _cbhm_open_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<cbhm_h>)>>(
          'cbhm_open_service');
  late final _cbhm_open_service =
      _cbhm_open_servicePtr.asFunction<int Function(ffi.Pointer<cbhm_h>)>();

  /// @brief Closes clipboard handle.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_open_service()
  int cbhm_close_service(
    cbhm_h cbhm_handle,
  ) {
    return _cbhm_close_service(
      cbhm_handle,
    );
  }

  late final _cbhm_close_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(cbhm_h)>>(
          'cbhm_close_service');
  late final _cbhm_close_service =
      _cbhm_close_servicePtr.asFunction<int Function(cbhm_h)>();

  /// @brief Shows clipboard.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_hide()
  int cbhm_show(
    cbhm_h cbhm_handle,
  ) {
    return _cbhm_show(
      cbhm_handle,
    );
  }

  late final _cbhm_showPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(cbhm_h)>>('cbhm_show');
  late final _cbhm_show = _cbhm_showPtr.asFunction<int Function(cbhm_h)>();

  /// @brief Hides clipboard.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_show()
  int cbhm_hide(
    cbhm_h cbhm_handle,
  ) {
    return _cbhm_hide(
      cbhm_handle,
    );
  }

  late final _cbhm_hidePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(cbhm_h)>>('cbhm_hide');
  late final _cbhm_hide = _cbhm_hidePtr.asFunction<int Function(cbhm_h)>();

  /// @brief Sets clipboard selection type.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] type Selection type
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_selection_type_get()
  int cbhm_selection_type_set(
    cbhm_h cbhm_handle,
    int type,
  ) {
    return _cbhm_selection_type_set(
      cbhm_handle,
      type,
    );
  }

  late final _cbhm_selection_type_setPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(cbhm_h, ffi.Int32)>>(
          'cbhm_selection_type_set');
  late final _cbhm_selection_type_set =
      _cbhm_selection_type_setPtr.asFunction<int Function(cbhm_h, int)>();

  /// @brief Gets clipboard selection type.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[out] type Selection type
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_selection_type_set()
  int cbhm_selection_type_get(
    cbhm_h cbhm_handle,
    ffi.Pointer<ffi.Int32> type,
  ) {
    return _cbhm_selection_type_get(
      cbhm_handle,
      type,
    );
  }

  late final _cbhm_selection_type_getPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>>(
      'cbhm_selection_type_get');
  late final _cbhm_selection_type_get = _cbhm_selection_type_getPtr
      .asFunction<int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>();

  /// @brief Adds event callback function of selecting a clipboard item.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] callback Callback function called when a clipboard item is selected
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_OUT_OF_MEMORY Out of memory
  int cbhm_item_selected_callback_add(
    cbhm_h cbhm_handle,
    cbhm_selected_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_item_selected_callback_add(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_item_selected_callback_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_selected_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_item_selected_callback_add');
  late final _cbhm_item_selected_callback_add =
      _cbhm_item_selected_callback_addPtr.asFunction<
          int Function(cbhm_h, cbhm_selected_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Removes event callback function for selecting a clipboard item.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle The clipboard handle
  /// @param[in] callback The callback function to be deleted
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  int cbhm_item_selected_callback_remove(
    cbhm_h cbhm_handle,
    cbhm_selected_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_item_selected_callback_remove(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_item_selected_callback_removePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_selected_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_item_selected_callback_remove');
  late final _cbhm_item_selected_callback_remove =
      _cbhm_item_selected_callback_removePtr.asFunction<
          int Function(cbhm_h, cbhm_selected_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Sends data to clipboard.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] type Selection type
  /// @param[in] data Data to be sent
  /// @param[in] len The length of data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_OUT_OF_MEMORY Out of memory
  /// @see cbhm_selection_get()
  int cbhm_selection_set(
    cbhm_h cbhm_handle,
    int type,
    ffi.Pointer<ffi.Void> data,
    int len,
  ) {
    return _cbhm_selection_set(
      cbhm_handle,
      type,
      data,
      len,
    );
  }

  late final _cbhm_selection_setPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, ffi.Int32, ffi.Pointer<ffi.Void>,
              ffi.Size)>>('cbhm_selection_set');
  late final _cbhm_selection_set = _cbhm_selection_setPtr
      .asFunction<int Function(cbhm_h, int, ffi.Pointer<ffi.Void>, int)>();

  /// @brief Receives data from clipboard.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] type Selection type
  /// @param[in] callback Callback function receiving data from clipboard
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_NO_DATA No data available
  /// @see cbhm_selection_set()
  int cbhm_selection_get(
    cbhm_h cbhm_handle,
    int type,
    cbhm_selection_data_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_selection_get(
      cbhm_handle,
      type,
      callback,
      user_data,
    );
  }

  late final _cbhm_selection_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, ffi.Int32, cbhm_selection_data_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_selection_get');
  late final _cbhm_selection_get = _cbhm_selection_getPtr.asFunction<
      int Function(
          cbhm_h, int, cbhm_selection_data_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Gets the count of clipboard items.
  /// @since_tizen 3.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @return The count of clipboard items
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  int cbhm_item_count_get(
    cbhm_h cbhm_handle,
  ) {
    return _cbhm_item_count_get(
      cbhm_handle,
    );
  }

  late final _cbhm_item_count_getPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(cbhm_h)>>(
          'cbhm_item_count_get');
  late final _cbhm_item_count_get =
      _cbhm_item_count_getPtr.asFunction<int Function(cbhm_h)>();

  /// @brief Gets the type of the latest item in clipboard.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle The clipboard handle
  /// @param[out] type The type of the latest item
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_selection_type_set()
  int cbhm_latest_item_type_get(
    cbhm_h cbhm_handle,
    ffi.Pointer<ffi.Int32> type,
  ) {
    return _cbhm_latest_item_type_get(
      cbhm_handle,
      type,
    );
  }

  late final _cbhm_latest_item_type_getPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>>(
      'cbhm_latest_item_type_get');
  late final _cbhm_latest_item_type_get = _cbhm_latest_item_type_getPtr
      .asFunction<int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>();

  /// @brief Adds event callback function for receiving changed event of clipboard items.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle The clipboard handle
  /// @param[in] callback The callback function called when a clipboard item is changed
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_OUT_OF_MEMORY Out of memory
  int cbhm_item_changed_callback_add(
    cbhm_h cbhm_handle,
    cbhm_item_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_item_changed_callback_add(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_item_changed_callback_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_item_changed_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_item_changed_callback_add');
  late final _cbhm_item_changed_callback_add =
      _cbhm_item_changed_callback_addPtr.asFunction<
          int Function(cbhm_h, cbhm_item_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Removes event callback function for receiving changed event of clipboard items.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle The clipboard handle
  /// @param[in] callback The callback function to be removed
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  int cbhm_item_changed_callback_remove(
    cbhm_h cbhm_handle,
    cbhm_item_changed_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_item_changed_callback_remove(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_item_changed_callback_removePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_item_changed_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_item_changed_callback_remove');
  late final _cbhm_item_changed_callback_remove =
      _cbhm_item_changed_callback_removePtr.asFunction<
          int Function(cbhm_h, cbhm_item_changed_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Gets the clipboard state.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[out] type State type
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  int cbhm_state_get(
    cbhm_h cbhm_handle,
    ffi.Pointer<ffi.Int32> type,
  ) {
    return _cbhm_state_get(
      cbhm_handle,
      type,
    );
  }

  late final _cbhm_state_getPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>>(
      'cbhm_state_get');
  late final _cbhm_state_get = _cbhm_state_getPtr
      .asFunction<int Function(cbhm_h, ffi.Pointer<ffi.Int32>)>();

  /// @brief Adds event callback function of receiving monitored event of clipboard.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] callback Callback function called when clipboard becomes active or inactive
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @retval #CBHM_ERROR_OUT_OF_MEMORY Out of memory
  /// @see cbhm_monitor_callback_remove()
  int cbhm_monitor_callback_add(
    cbhm_h cbhm_handle,
    cbhm_monitor_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_monitor_callback_add(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_monitor_callback_addPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_monitor_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_monitor_callback_add');
  late final _cbhm_monitor_callback_add =
      _cbhm_monitor_callback_addPtr.asFunction<
          int Function(cbhm_h, cbhm_monitor_cb, ffi.Pointer<ffi.Void>)>();

  /// @brief Deletes event callback function of receiving monitored event of clipboard.
  /// @since_tizen 4.0
  /// @param[in] cbhm_handle Clipboard handle
  /// @param[in] callback Callback function to be deleted
  /// @param[in] user_data User data to be passed to the given event callback function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #CBHM_ERROR_NONE Successful
  /// @retval #CBHM_ERROR_INVALID_PARAMETER Invalid function parameters
  /// @see cbhm_monitor_callback_add()
  int cbhm_monitor_callback_remove(
    cbhm_h cbhm_handle,
    cbhm_monitor_cb callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _cbhm_monitor_callback_remove(
      cbhm_handle,
      callback,
      user_data,
    );
  }

  late final _cbhm_monitor_callback_removePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(cbhm_h, cbhm_monitor_cb,
              ffi.Pointer<ffi.Void>)>>('cbhm_monitor_callback_remove');
  late final _cbhm_monitor_callback_remove =
      _cbhm_monitor_callback_removePtr.asFunction<
          int Function(cbhm_h, cbhm_monitor_cb, ffi.Pointer<ffi.Void>)>();
}

final class cbhm extends ffi.Opaque {}

/// @brief Clipboard handle.
/// @since_tizen 3.0
typedef cbhm_h = ffi.Pointer<cbhm>;

/// @brief Enumeration for Clipboard Data Type.
/// @since_tizen 3.0
abstract class cbhm_sel_type_e {
  /// < Content is from outside of Elementary
  static const int CBHM_SEL_TYPE_NONE = 0;

  /// < Plain unformatted text: Used for things that don't want rich markup
  static const int CBHM_SEL_TYPE_TEXT = 1;

  /// < Edje textblock markup, including inline images
  static const int CBHM_SEL_TYPE_MARKUP = 2;

  /// < Images
  static const int CBHM_SEL_TYPE_IMAGE = 4;

  /// < Raw HTML-like data (eg. webkit)
  static const int CBHM_SEL_TYPE_HTML = 8;
}

/// @brief Event callback signature of selecting a clipboard item.
/// @since_tizen 3.0
/// @param[in] cbhm_handle Clipboard handle
/// @param[in] user_data User data to be passed to the given event callback function
/// @return This is reserved
/// @see cbhm_item_selected_callback_add()
typedef cbhm_selected_cb
    = ffi.Pointer<ffi.NativeFunction<cbhm_selected_cbFunction>>;
typedef cbhm_selected_cbFunction = ffi.Int Function(
    cbhm_h cbhm_handle, ffi.Pointer<ffi.Void> user_data);
typedef Dartcbhm_selected_cbFunction = int Function(
    cbhm_h cbhm_handle, ffi.Pointer<ffi.Void> user_data);

/// @brief Event callback signature of receiving data from clipboard.
/// @since_tizen 3.0
/// @param[in] Clipboard handle
/// @param[out] buf Buffer for receiving data
/// @param[in] len The length of buffer
/// @param[in] user_data User data to be passed to the given event callback function
/// @return This is reserved
/// @see cbhm_item_selected_callback_add()
typedef cbhm_selection_data_cb
    = ffi.Pointer<ffi.NativeFunction<cbhm_selection_data_cbFunction>>;
typedef cbhm_selection_data_cbFunction = ffi.Int Function(cbhm_h cbhm_handle,
    ffi.Pointer<ffi.Char> buf, ffi.Size len, ffi.Pointer<ffi.Void> user_data);
typedef Dartcbhm_selection_data_cbFunction = int Function(cbhm_h cbhm_handle,
    ffi.Pointer<ffi.Char> buf, int len, ffi.Pointer<ffi.Void> user_data);

/// @brief Event callback signature for receiving changed event of clipboard items.
/// @since_tizen 4.0
/// @param[in] cbhm_handle The clipboard handle
/// @remarks @a cbhm_handle is the same handle as the one used in the cbhm_item_changed_callback_add() call with which the callback was added
/// @param[in] item_count The number of clipboard items
/// @param[in] user_data User data to be passed to the given event callback function
/// @return #CBHM_ERROR_NONE on success,
/// otherwise a negative error value
/// @retval #CBHM_ERROR_NONE Successful
/// @see cbhm_item_selected_callback_add()
typedef cbhm_item_changed_cb
    = ffi.Pointer<ffi.NativeFunction<cbhm_item_changed_cbFunction>>;
typedef cbhm_item_changed_cbFunction = ffi.Void Function(
    cbhm_h cbhm_handle, ffi.Int item_count, ffi.Pointer<ffi.Void> user_data);
typedef Dartcbhm_item_changed_cbFunction = void Function(
    cbhm_h cbhm_handle, int item_count, ffi.Pointer<ffi.Void> user_data);

/// @brief Enumeration for Clipboard State Type.
/// @since_tizen 3.0
abstract class cbhm_state_type_e {
  /// < Default State of Clipboard History Manager
  static const int CBHM_STATE_NONE = 0;

  /// < Clipboard History Manager is visible
  static const int CBHM_STATE_SHOW = 1;

  /// < Clipboard History Manager is invisible
  static const int CBHM_STATE_HIDE = 2;
}

/// @brief Event callback signature of receiving monitored event of clipboard.
/// @since_tizen 4.0
/// @param[in] cbhm_handle Clipboard handle
/// @param[in] active_state Clipboard is active if @c true, inactive otherwise
/// @param[in] user_data User data to be passed to the given event callback function
/// @see cbhm_monitor_callback_add()
/// @see cbhm_monitor_callback_remove()
typedef cbhm_monitor_cb
    = ffi.Pointer<ffi.NativeFunction<cbhm_monitor_cbFunction>>;
typedef cbhm_monitor_cbFunction = ffi.Void Function(
    cbhm_h cbhm_handle, ffi.Bool active_state, ffi.Pointer<ffi.Void> user_data);
typedef Dartcbhm_monitor_cbFunction = void Function(
    cbhm_h cbhm_handle, bool active_state, ffi.Pointer<ffi.Void> user_data);
