// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_bundle.dart' as bundle;
import 'generated_bindings_time.dart' as time;

/// Dart bindings for Tizen rpc-port APIs.
class Tizen70RpcPort {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen70RpcPort(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen70RpcPort.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Reads data from an RPC port.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  ///
  /// @param[in] h The rpc port handle
  /// @param[out] buf Buffer for reading data
  /// @param[in] size Size for reading data
  ///
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  /// @see rpc_port_write()
  int rpc_port_read(
    rpc_port_h h,
    ffi.Pointer<ffi.Void> buf,
    int size,
  ) {
    return _rpc_port_read(
      h,
      buf,
      size,
    );
  }

  late final _rpc_port_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_h, ffi.Pointer<ffi.Void>,
              ffi.UnsignedInt)>>('rpc_port_read');
  late final _rpc_port_read = _rpc_port_readPtr
      .asFunction<int Function(rpc_port_h, ffi.Pointer<ffi.Void>, int)>();

  /// @brief Writes data to an RPC port.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  ///
  /// @param[in] h The rpc port handle
  /// @param[in] buf Buffer for writing data
  /// @param[in] size Size for writing data
  ///
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  /// @see rpc_port_read()
  int rpc_port_write(
    rpc_port_h h,
    ffi.Pointer<ffi.Void> buf,
    int size,
  ) {
    return _rpc_port_write(
      h,
      buf,
      size,
    );
  }

  late final _rpc_port_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_h, ffi.Pointer<ffi.Void>,
              ffi.UnsignedInt)>>('rpc_port_write');
  late final _rpc_port_write = _rpc_port_writePtr
      .asFunction<int Function(rpc_port_h, ffi.Pointer<ffi.Void>, int)>();

  /// @brief Creates a rpc port proxy handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks You must release @a h using rpc_port_proxy_destroy().
  /// @param[out] h The rpc port proxy handle that is newly created
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_proxy_destroy()
  int rpc_port_proxy_create(
    ffi.Pointer<rpc_port_proxy_h> h,
  ) {
    return _rpc_port_proxy_create(
      h,
    );
  }

  late final _rpc_port_proxy_createPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<rpc_port_proxy_h>)>>(
      'rpc_port_proxy_create');
  late final _rpc_port_proxy_create = _rpc_port_proxy_createPtr
      .asFunction<int Function(ffi.Pointer<rpc_port_proxy_h>)>();

  /// @brief Destroys a rpc port proxy handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port proxy handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_proxy_create()
  int rpc_port_proxy_destroy(
    rpc_port_proxy_h h,
  ) {
    return _rpc_port_proxy_destroy(
      h,
    );
  }

  late final _rpc_port_proxy_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_proxy_h)>>(
          'rpc_port_proxy_destroy');
  late final _rpc_port_proxy_destroy =
      _rpc_port_proxy_destroyPtr.asFunction<int Function(rpc_port_proxy_h)>();

  /// @brief Connects to @a port of @a appid.
  /// @details To send and receive data, the proxy should connect to port of stub
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @privlevel public
  /// @privilege %http://tizen.org/privilege/appmanager.launch \n
  /// %http://tizen.org/privilege/datasharing
  /// @remarks If you want to use this function, you must add privileges.
  /// @param[in] h The rpc port proxy handle
  /// @param[in] appid The target stub appid
  /// @param[in] port The name of rpc port
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_PERMISSION_DENIED Permission denied
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  int rpc_port_proxy_connect(
    rpc_port_proxy_h h,
    ffi.Pointer<ffi.Char> appid,
    ffi.Pointer<ffi.Char> port,
  ) {
    return _rpc_port_proxy_connect(
      h,
      appid,
      port,
    );
  }

  late final _rpc_port_proxy_connectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('rpc_port_proxy_connect');
  late final _rpc_port_proxy_connect = _rpc_port_proxy_connectPtr.asFunction<
      int Function(
          rpc_port_proxy_h, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// @brief Adds a proxy connected callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port proxy handle
  /// @param[in] cb The callback function to be called when proxy is connected
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_proxy_connected_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_proxy_add_connected_event_cb(
    rpc_port_proxy_h h,
    rpc_port_proxy_connected_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_proxy_add_connected_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_proxy_add_connected_event_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, rpc_port_proxy_connected_event_cb,
              ffi.Pointer<ffi.Void>)>>('rpc_port_proxy_add_connected_event_cb');
  late final _rpc_port_proxy_add_connected_event_cb =
      _rpc_port_proxy_add_connected_event_cbPtr.asFunction<
          int Function(rpc_port_proxy_h, rpc_port_proxy_connected_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Adds a proxy disconnected callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port proxy handle
  /// @param[in] cb The callback function to be called when proxy is disconnected
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_proxy_disconnected_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_proxy_add_disconnected_event_cb(
    rpc_port_proxy_h h,
    rpc_port_proxy_disconnected_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_proxy_add_disconnected_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_proxy_add_disconnected_event_cbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  rpc_port_proxy_h,
                  rpc_port_proxy_disconnected_event_cb,
                  ffi.Pointer<ffi.Void>)>>(
      'rpc_port_proxy_add_disconnected_event_cb');
  late final _rpc_port_proxy_add_disconnected_event_cb =
      _rpc_port_proxy_add_disconnected_event_cbPtr.asFunction<
          int Function(rpc_port_proxy_h, rpc_port_proxy_disconnected_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Adds a proxy rejected callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port proxy handle
  /// @param[in] cb The callback function to be called when proxy is rejected
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_proxy_rejected_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_proxy_add_rejected_event_cb(
    rpc_port_proxy_h h,
    rpc_port_proxy_rejected_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_proxy_add_rejected_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_proxy_add_rejected_event_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, rpc_port_proxy_rejected_event_cb,
              ffi.Pointer<ffi.Void>)>>('rpc_port_proxy_add_rejected_event_cb');
  late final _rpc_port_proxy_add_rejected_event_cb =
      _rpc_port_proxy_add_rejected_event_cbPtr.asFunction<
          int Function(rpc_port_proxy_h, rpc_port_proxy_rejected_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Adds a proxy received callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port proxy handle
  /// @param[in] cb The callback function to be called when proxy received data
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_proxy_received_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_proxy_add_received_event_cb(
    rpc_port_proxy_h h,
    rpc_port_proxy_received_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_proxy_add_received_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_proxy_add_received_event_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, rpc_port_proxy_received_event_cb,
              ffi.Pointer<ffi.Void>)>>('rpc_port_proxy_add_received_event_cb');
  late final _rpc_port_proxy_add_received_event_cb =
      _rpc_port_proxy_add_received_event_cbPtr.asFunction<
          int Function(rpc_port_proxy_h, rpc_port_proxy_received_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Gets a port from proxy handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks This handle @a port will not be valid if the proxy was disconnected or destroyed.
  /// @param[in] h The rpc port proxy handle
  /// @param[in] type The type of port
  /// @param[out] port The port to communicate
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR No available ports
  /// @see rpc_port_write()
  /// @see rpc_port_read()
  /// @see rpc_port_parcel_create_from_port()
  /// @see rpc_port_parcel_send();
  int rpc_port_proxy_get_port(
    rpc_port_proxy_h h,
    int type,
    ffi.Pointer<rpc_port_h> port,
  ) {
    return _rpc_port_proxy_get_port(
      h,
      type,
      port,
    );
  }

  late final _rpc_port_proxy_get_portPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, ffi.Int32,
              ffi.Pointer<rpc_port_h>)>>('rpc_port_proxy_get_port');
  late final _rpc_port_proxy_get_port = _rpc_port_proxy_get_portPtr.asFunction<
      int Function(rpc_port_proxy_h, int, ffi.Pointer<rpc_port_h>)>();

  /// @brief Creates a rpc port stub handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks You must release @a h using rpc_port_stub_destroy().
  /// @param[out] h The rpc port stub handle that is newly created
  /// @param[in] port_name The name of the port which want to listen
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_stub_destroy()
  int rpc_port_stub_create(
    ffi.Pointer<rpc_port_stub_h> h,
    ffi.Pointer<ffi.Char> port_name,
  ) {
    return _rpc_port_stub_create(
      h,
      port_name,
    );
  }

  late final _rpc_port_stub_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<rpc_port_stub_h>,
              ffi.Pointer<ffi.Char>)>>('rpc_port_stub_create');
  late final _rpc_port_stub_create = _rpc_port_stub_createPtr.asFunction<
      int Function(ffi.Pointer<rpc_port_stub_h>, ffi.Pointer<ffi.Char>)>();

  /// @brief Destroys a rpc port stub handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_stub_create()
  int rpc_port_stub_destroy(
    rpc_port_stub_h h,
  ) {
    return _rpc_port_stub_destroy(
      h,
    );
  }

  late final _rpc_port_stub_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_stub_h)>>(
          'rpc_port_stub_destroy');
  late final _rpc_port_stub_destroy =
      _rpc_port_stub_destroyPtr.asFunction<int Function(rpc_port_stub_h)>();

  /// @brief Listens to the requests for connections.
  /// @details The stub listens requests to connect by port
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  int rpc_port_stub_listen(
    rpc_port_stub_h h,
  ) {
    return _rpc_port_stub_listen(
      h,
    );
  }

  late final _rpc_port_stub_listenPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_stub_h)>>(
          'rpc_port_stub_listen');
  late final _rpc_port_stub_listen =
      _rpc_port_stub_listenPtr.asFunction<int Function(rpc_port_stub_h)>();

  /// @brief Adds a privilege to the stub.
  /// @details The stub can control access to the port using tizen privilege.
  /// It allows connections only if the proxy which have the privileges.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @param[in] privilege The privilege to access this stub
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_stub_add_privilege(
    rpc_port_stub_h h,
    ffi.Pointer<ffi.Char> privilege,
  ) {
    return _rpc_port_stub_add_privilege(
      h,
      privilege,
    );
  }

  late final _rpc_port_stub_add_privilegePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_stub_h,
              ffi.Pointer<ffi.Char>)>>('rpc_port_stub_add_privilege');
  late final _rpc_port_stub_add_privilege = _rpc_port_stub_add_privilegePtr
      .asFunction<int Function(rpc_port_stub_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Sets trusted to the stub.
  /// @details The stub can control access to the port using tizen certificate.
  /// It allows connections only if the proxy is signed with the same
  /// certificate.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @param[in] trusted Whether stub allows only trusted proxy or not
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_stub_set_trusted(
    rpc_port_stub_h h,
    bool trusted,
  ) {
    return _rpc_port_stub_set_trusted(
      h,
      trusted,
    );
  }

  late final _rpc_port_stub_set_trustedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_stub_h, ffi.Bool)>>(
          'rpc_port_stub_set_trusted');
  late final _rpc_port_stub_set_trusted = _rpc_port_stub_set_trustedPtr
      .asFunction<int Function(rpc_port_stub_h, bool)>();

  /// @brief Adds a stub connected callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc stub stub handle
  /// @param[in] cb The callback function to be called when proxy is connected
  /// with the stub
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_stub_connected_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_stub_add_connected_event_cb(
    rpc_port_stub_h h,
    rpc_port_stub_connected_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_stub_add_connected_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_stub_add_connected_event_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_stub_h, rpc_port_stub_connected_event_cb,
              ffi.Pointer<ffi.Void>)>>('rpc_port_stub_add_connected_event_cb');
  late final _rpc_port_stub_add_connected_event_cb =
      _rpc_port_stub_add_connected_event_cbPtr.asFunction<
          int Function(rpc_port_stub_h, rpc_port_stub_connected_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Adds a stub disconnected callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @param[in] cb The callback function to be called when proxy is disconnected
  /// with the stub
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_stub_disconnected_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_stub_add_disconnected_event_cb(
    rpc_port_stub_h h,
    rpc_port_stub_disconnected_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_stub_add_disconnected_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_stub_add_disconnected_event_cbPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(rpc_port_stub_h,
                  rpc_port_stub_disconnected_event_cb, ffi.Pointer<ffi.Void>)>>(
      'rpc_port_stub_add_disconnected_event_cb');
  late final _rpc_port_stub_add_disconnected_event_cb =
      _rpc_port_stub_add_disconnected_event_cbPtr.asFunction<
          int Function(rpc_port_stub_h, rpc_port_stub_disconnected_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Adds a stub received callback.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port stub handle
  /// @param[in] cb The callback function to be called when stub received data
  /// @param[in] user_data The user data to be passed to
  /// the rpc_port_stub_received_event_cb() function
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  int rpc_port_stub_add_received_event_cb(
    rpc_port_stub_h h,
    rpc_port_stub_received_event_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _rpc_port_stub_add_received_event_cb(
      h,
      cb,
      user_data,
    );
  }

  late final _rpc_port_stub_add_received_event_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_stub_h, rpc_port_stub_received_event_cb,
              ffi.Pointer<ffi.Void>)>>('rpc_port_stub_add_received_event_cb');
  late final _rpc_port_stub_add_received_event_cb =
      _rpc_port_stub_add_received_event_cbPtr.asFunction<
          int Function(rpc_port_stub_h, rpc_port_stub_received_event_cb,
              ffi.Pointer<ffi.Void>)>();

  /// @brief Gets a port from stub handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks This handle @a port will not be valid if the instance of the stub was disconnected or destroyed.
  /// @param[in] h The rpc port stub handle
  /// @param[in] type The type of port
  /// @param[in] instance The ID of the instance which is connected
  /// @param[out] port The port to communicate
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR No available ports
  /// @see rpc_port_write()
  /// @see rpc_port_read()
  /// @see rpc_port_parcel_create_from_port()
  /// @see rpc_port_parcel_send();
  int rpc_port_stub_get_port(
    rpc_port_stub_h h,
    int type,
    ffi.Pointer<ffi.Char> instance,
    ffi.Pointer<rpc_port_h> port,
  ) {
    return _rpc_port_stub_get_port(
      h,
      type,
      instance,
      port,
    );
  }

  late final _rpc_port_stub_get_portPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_stub_h, ffi.Int32, ffi.Pointer<ffi.Char>,
              ffi.Pointer<rpc_port_h>)>>('rpc_port_stub_get_port');
  late final _rpc_port_stub_get_port = _rpc_port_stub_get_portPtr.asFunction<
      int Function(rpc_port_stub_h, int, ffi.Pointer<ffi.Char>,
          ffi.Pointer<rpc_port_h>)>();

  /// @brief Connects to @a port_name of @a appid synchronously.
  /// @details To send and receive data, the proxy should connect to port of stub.
  /// @since_tizen 6.0
  /// @privlevel public
  /// @privilege %http://tizen.org/privilege/appmanager.launch \n
  /// %http://tizen.org/privilege/datasharing
  /// @param[in] h The rpc port proxy handle
  /// @param[in] appid The application ID of the target stub
  /// @param[in] port_name The name of rpc port
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_PERMISSION_DENIED Permission denied
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_IO_ERROR I/O error
  int rpc_port_proxy_connect_sync(
    rpc_port_proxy_h h,
    ffi.Pointer<ffi.Char> appid,
    ffi.Pointer<ffi.Char> port_name,
  ) {
    return _rpc_port_proxy_connect_sync(
      h,
      appid,
      port_name,
    );
  }

  late final _rpc_port_proxy_connect_syncPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_proxy_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('rpc_port_proxy_connect_sync');
  late final _rpc_port_proxy_connect_sync =
      _rpc_port_proxy_connect_syncPtr.asFunction<
          int Function(rpc_port_proxy_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  /// @brief Sets the paths of private sharing files.
  /// @details If all added paths are under the caller application's data path which can be obtained by calling app_get_data_path() function,
  /// those will be shared to the target application. Platform will grant a temporary permission to the target application for those files and revoke it when the target application is terminated or rpc_port_unset_private_sharing() is called.
  /// Paths should be regular files. The target application can just read them.
  /// Note that the target application doesn't have read permission of the directory that is obtained by caller's app_get_data_path(),
  /// You should open the file path with read only mode directly. For example, access() call to the file path will return error because access() needs the read permission of the directory.
  /// The target application can call open() with O_RDONLY mode for the passed file path, because platform grants read permission to the passed file path.
  /// @since_tizen 6.0
  /// @param[in] port The rpc port handle
  /// @param[in] paths The array of paths of files
  /// @param[in] size The size of the array of the paths
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_IO_ERROR I/O error
  ///
  /// @see rpc_port_unset_private_sharing()
  int rpc_port_set_private_sharing_array(
    rpc_port_h port,
    ffi.Pointer<ffi.Pointer<ffi.Char>> paths,
    int size,
  ) {
    return _rpc_port_set_private_sharing_array(
      port,
      paths,
      size,
    );
  }

  late final _rpc_port_set_private_sharing_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_h, ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.UnsignedInt)>>('rpc_port_set_private_sharing_array');
  late final _rpc_port_set_private_sharing_array =
      _rpc_port_set_private_sharing_arrayPtr.asFunction<
          int Function(rpc_port_h, ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  /// @brief Sets the path of the private sharing file.
  /// @details See the description of rpc_port_set_private_sharing_array() for details.
  /// @since_tizen 6.0
  /// @param[in] port The rpc port handle
  /// @param[in] path The path of the file
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_IO_ERROR I/O error
  ///
  /// @see rpc_port_set_private_sharing_array()
  /// @see rpc_port_unset_private_sharing()
  int rpc_port_set_private_sharing(
    rpc_port_h port,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _rpc_port_set_private_sharing(
      port,
      path,
    );
  }

  late final _rpc_port_set_private_sharingPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(rpc_port_h, ffi.Pointer<ffi.Char>)>>(
      'rpc_port_set_private_sharing');
  late final _rpc_port_set_private_sharing = _rpc_port_set_private_sharingPtr
      .asFunction<int Function(rpc_port_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Unsets the private sharing.
  /// @since_tizen 6.0
  /// @param[in] port The rpc port handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_IO_ERROR I/O error
  ///
  /// @see rpc_port_set_private_sharing_array()
  /// @see rpc_port_set_private_sharing()
  int rpc_port_unset_private_sharing(
    rpc_port_h port,
  ) {
    return _rpc_port_unset_private_sharing(
      port,
    );
  }

  late final _rpc_port_unset_private_sharingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_h)>>(
          'rpc_port_unset_private_sharing');
  late final _rpc_port_unset_private_sharing =
      _rpc_port_unset_private_sharingPtr.asFunction<int Function(rpc_port_h)>();

  /// @brief Disconnects the port.
  /// @since_tizen 6.5
  /// @param[in] port The rpc port handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  int rpc_port_disconnect(
    rpc_port_h port,
  ) {
    return _rpc_port_disconnect(
      port,
    );
  }

  late final _rpc_port_disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_h)>>(
          'rpc_port_disconnect');
  late final _rpc_port_disconnect =
      _rpc_port_disconnectPtr.asFunction<int Function(rpc_port_h)>();

  /// @brief Creates a rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks You must release @a h using rpc_port_parcel_destroy().
  /// @param[out] h The rpc port parcel handle that is newly created
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see rpc_port_parcel_destroy()
  int rpc_port_parcel_create(
    ffi.Pointer<rpc_port_parcel_h> h,
  ) {
    return _rpc_port_parcel_create(
      h,
    );
  }

  late final _rpc_port_parcel_createPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<rpc_port_parcel_h>)>>(
      'rpc_port_parcel_create');
  late final _rpc_port_parcel_create = _rpc_port_parcel_createPtr
      .asFunction<int Function(ffi.Pointer<rpc_port_parcel_h>)>();

  /// @brief Creates a rpc port parcel handle from port.
  /// @details Creates a rpc port parcel handle using read data from the port.
  /// It calls rpc_port_read() internally.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks You must release @a h using rpc_port_parcel_destroy().
  /// @param[out] h The rpc port parcel handle that is newly created
  /// @param[in] port The rpc port handle for creating handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a port is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  /// @see rpc_port_parcel_destroy()
  /// @see rpc_port_parcel_send()
  int rpc_port_parcel_create_from_port(
    ffi.Pointer<rpc_port_parcel_h> h,
    rpc_port_h port,
  ) {
    return _rpc_port_parcel_create_from_port(
      h,
      port,
    );
  }

  late final _rpc_port_parcel_create_from_portPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<rpc_port_parcel_h>,
              rpc_port_h)>>('rpc_port_parcel_create_from_port');
  late final _rpc_port_parcel_create_from_port =
      _rpc_port_parcel_create_from_portPtr.asFunction<
          int Function(ffi.Pointer<rpc_port_parcel_h>, rpc_port_h)>();

  /// @brief Sends parcel data through the port.
  /// @details Sends parcel data through the port. It calls rpc_port_write()
  /// internally.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle that is newly created
  /// @param[in] port The rpc port handle for writing data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @retval #RPC_PORT_ERROR_IO_ERROR Internal I/O error
  /// @see rpc_port_parcel_create_from_port()
  int rpc_port_parcel_send(
    rpc_port_parcel_h h,
    rpc_port_h port,
  ) {
    return _rpc_port_parcel_send(
      h,
      port,
    );
  }

  late final _rpc_port_parcel_sendPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, rpc_port_h)>>(
      'rpc_port_parcel_send');
  late final _rpc_port_parcel_send = _rpc_port_parcel_sendPtr
      .asFunction<int Function(rpc_port_parcel_h, rpc_port_h)>();

  /// @brief Destroys a rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_create()
  int rpc_port_parcel_destroy(
    rpc_port_parcel_h h,
  ) {
    return _rpc_port_parcel_destroy(
      h,
    );
  }

  late final _rpc_port_parcel_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h)>>(
          'rpc_port_parcel_destroy');
  late final _rpc_port_parcel_destroy =
      _rpc_port_parcel_destroyPtr.asFunction<int Function(rpc_port_parcel_h)>();

  /// @brief Writes a byte value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] b Byte data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_byte()
  int rpc_port_parcel_write_byte(
    rpc_port_parcel_h h,
    int b,
  ) {
    return _rpc_port_parcel_write_byte(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_write_bytePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Char)>>(
      'rpc_port_parcel_write_byte');
  late final _rpc_port_parcel_write_byte = _rpc_port_parcel_write_bytePtr
      .asFunction<int Function(rpc_port_parcel_h, int)>();

  /// @brief Writes a short value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] i short data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_int16()
  int rpc_port_parcel_write_int16(
    rpc_port_parcel_h h,
    int i,
  ) {
    return _rpc_port_parcel_write_int16(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_write_int16Ptr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Short)>>(
      'rpc_port_parcel_write_int16');
  late final _rpc_port_parcel_write_int16 = _rpc_port_parcel_write_int16Ptr
      .asFunction<int Function(rpc_port_parcel_h, int)>();

  /// @brief Writes a integer value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] i int data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_int32()
  int rpc_port_parcel_write_int32(
    rpc_port_parcel_h h,
    int i,
  ) {
    return _rpc_port_parcel_write_int32(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_write_int32Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Int)>>(
          'rpc_port_parcel_write_int32');
  late final _rpc_port_parcel_write_int32 = _rpc_port_parcel_write_int32Ptr
      .asFunction<int Function(rpc_port_parcel_h, int)>();

  /// @brief Writes a long long integer value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] i long long data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_int64()
  int rpc_port_parcel_write_int64(
    rpc_port_parcel_h h,
    int i,
  ) {
    return _rpc_port_parcel_write_int64(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_write_int64Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.LongLong)>>(
      'rpc_port_parcel_write_int64');
  late final _rpc_port_parcel_write_int64 = _rpc_port_parcel_write_int64Ptr
      .asFunction<int Function(rpc_port_parcel_h, int)>();

  /// @brief Writes a floating point value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] f float data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_float()
  int rpc_port_parcel_write_float(
    rpc_port_parcel_h h,
    double f,
  ) {
    return _rpc_port_parcel_write_float(
      h,
      f,
    );
  }

  late final _rpc_port_parcel_write_floatPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Float)>>(
      'rpc_port_parcel_write_float');
  late final _rpc_port_parcel_write_float = _rpc_port_parcel_write_floatPtr
      .asFunction<int Function(rpc_port_parcel_h, double)>();

  /// @brief Writes a double precision floating point value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] d double data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_double()
  int rpc_port_parcel_write_double(
    rpc_port_parcel_h h,
    double d,
  ) {
    return _rpc_port_parcel_write_double(
      h,
      d,
    );
  }

  late final _rpc_port_parcel_write_doublePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Double)>>(
      'rpc_port_parcel_write_double');
  late final _rpc_port_parcel_write_double = _rpc_port_parcel_write_doublePtr
      .asFunction<int Function(rpc_port_parcel_h, double)>();

  /// @brief Writes a string value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] str string data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_string()
  int rpc_port_parcel_write_string(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Char> str,
  ) {
    return _rpc_port_parcel_write_string(
      h,
      str,
    );
  }

  late final _rpc_port_parcel_write_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Char>)>>('rpc_port_parcel_write_string');
  late final _rpc_port_parcel_write_string = _rpc_port_parcel_write_stringPtr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Writes a boolean value into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] b boolean data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_bool()
  int rpc_port_parcel_write_bool(
    rpc_port_parcel_h h,
    bool b,
  ) {
    return _rpc_port_parcel_write_bool(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_write_boolPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Bool)>>(
      'rpc_port_parcel_write_bool');
  late final _rpc_port_parcel_write_bool = _rpc_port_parcel_write_boolPtr
      .asFunction<int Function(rpc_port_parcel_h, bool)>();

  /// @brief Writes a bundle data into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] b Bundle data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_bundle()
  int rpc_port_parcel_write_bundle(
    rpc_port_parcel_h h,
    ffi.Pointer<bundle.bundle> b,
  ) {
    return _rpc_port_parcel_write_bundle(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_write_bundlePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<bundle.bundle>)>>('rpc_port_parcel_write_bundle');
  late final _rpc_port_parcel_write_bundle =
      _rpc_port_parcel_write_bundlePtr.asFunction<
          int Function(rpc_port_parcel_h, ffi.Pointer<bundle.bundle>)>();

  /// @brief Writes a count for array into rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] count Array count
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read_array_count()
  int rpc_port_parcel_write_array_count(
    rpc_port_parcel_h h,
    int count,
  ) {
    return _rpc_port_parcel_write_array_count(
      h,
      count,
    );
  }

  late final _rpc_port_parcel_write_array_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(rpc_port_parcel_h, ffi.Int)>>(
          'rpc_port_parcel_write_array_count');
  late final _rpc_port_parcel_write_array_count =
      _rpc_port_parcel_write_array_countPtr
          .asFunction<int Function(rpc_port_parcel_h, int)>();

  /// @brief Writes the data into parcel handle using @a parcelable.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] parcelable The interface to write the data into parcel handle
  /// @param[in] data Data which write into parcel
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_read()
  int rpc_port_parcel_write(
    rpc_port_parcel_h h,
    ffi.Pointer<rpc_port_parcelable_t> parcelable,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _rpc_port_parcel_write(
      h,
      parcelable,
      data,
    );
  }

  late final _rpc_port_parcel_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              rpc_port_parcel_h,
              ffi.Pointer<rpc_port_parcelable_t>,
              ffi.Pointer<ffi.Void>)>>('rpc_port_parcel_write');
  late final _rpc_port_parcel_write = _rpc_port_parcel_writePtr.asFunction<
      int Function(rpc_port_parcel_h, ffi.Pointer<rpc_port_parcelable_t>,
          ffi.Pointer<ffi.Void>)>();

  /// @brief Reads a byte value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] b Byte data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_byte()
  int rpc_port_parcel_read_byte(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Char> b,
  ) {
    return _rpc_port_parcel_read_byte(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_read_bytePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Char>)>>('rpc_port_parcel_read_byte');
  late final _rpc_port_parcel_read_byte = _rpc_port_parcel_read_bytePtr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Reads a short value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] i short data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_int16()
  int rpc_port_parcel_read_int16(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Short> i,
  ) {
    return _rpc_port_parcel_read_int16(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_read_int16Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Short>)>>('rpc_port_parcel_read_int16');
  late final _rpc_port_parcel_read_int16 = _rpc_port_parcel_read_int16Ptr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Short>)>();

  /// @brief Reads a integer value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] i int data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_int32()
  int rpc_port_parcel_read_int32(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Int> i,
  ) {
    return _rpc_port_parcel_read_int32(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_read_int32Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Int>)>>('rpc_port_parcel_read_int32');
  late final _rpc_port_parcel_read_int32 = _rpc_port_parcel_read_int32Ptr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Int>)>();

  /// @brief Reads a long long integer value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] i long long data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_int64()
  int rpc_port_parcel_read_int64(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.LongLong> i,
  ) {
    return _rpc_port_parcel_read_int64(
      h,
      i,
    );
  }

  late final _rpc_port_parcel_read_int64Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.LongLong>)>>('rpc_port_parcel_read_int64');
  late final _rpc_port_parcel_read_int64 = _rpc_port_parcel_read_int64Ptr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.LongLong>)>();

  /// @brief Reads a floating point value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] f float data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_float()
  int rpc_port_parcel_read_float(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Float> f,
  ) {
    return _rpc_port_parcel_read_float(
      h,
      f,
    );
  }

  late final _rpc_port_parcel_read_floatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Float>)>>('rpc_port_parcel_read_float');
  late final _rpc_port_parcel_read_float = _rpc_port_parcel_read_floatPtr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Float>)>();

  /// @brief Reads a double precision floating point value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] d double data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_double()
  int rpc_port_parcel_read_double(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Double> d,
  ) {
    return _rpc_port_parcel_read_double(
      h,
      d,
    );
  }

  late final _rpc_port_parcel_read_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Double>)>>('rpc_port_parcel_read_double');
  late final _rpc_port_parcel_read_double = _rpc_port_parcel_read_doublePtr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Double>)>();

  /// @brief Reads a string value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks The @a str should be released using free().
  /// @param[in] h The rpc port parcel handle
  /// @param[out] str string data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_string()
  int rpc_port_parcel_read_string(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Pointer<ffi.Char>> str,
  ) {
    return _rpc_port_parcel_read_string(
      h,
      str,
    );
  }

  late final _rpc_port_parcel_read_stringPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  rpc_port_parcel_h, ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'rpc_port_parcel_read_string');
  late final _rpc_port_parcel_read_string =
      _rpc_port_parcel_read_stringPtr.asFunction<
          int Function(
              rpc_port_parcel_h, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// @brief Reads a boolean value from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] b boolean data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_bool()
  int rpc_port_parcel_read_bool(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Bool> b,
  ) {
    return _rpc_port_parcel_read_bool(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_read_boolPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Bool>)>>('rpc_port_parcel_read_bool');
  late final _rpc_port_parcel_read_bool = _rpc_port_parcel_read_boolPtr
      .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Bool>)>();

  /// @brief Reads a bundle data from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @remarks The @a b should be released using bundle_free().
  /// @param[in] h The rpc port parcel handle
  /// @param[out] b Bundle data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_bundle()
  int rpc_port_parcel_read_bundle(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Pointer<bundle.bundle>> b,
  ) {
    return _rpc_port_parcel_read_bundle(
      h,
      b,
    );
  }

  late final _rpc_port_parcel_read_bundlePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  rpc_port_parcel_h, ffi.Pointer<ffi.Pointer<bundle.bundle>>)>>(
      'rpc_port_parcel_read_bundle');
  late final _rpc_port_parcel_read_bundle =
      _rpc_port_parcel_read_bundlePtr.asFunction<
          int Function(
              rpc_port_parcel_h, ffi.Pointer<ffi.Pointer<bundle.bundle>>)>();

  /// @brief Reads a count for array from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] count Array count
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_array_count()
  int rpc_port_parcel_read_array_count(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Int> count,
  ) {
    return _rpc_port_parcel_read_array_count(
      h,
      count,
    );
  }

  late final _rpc_port_parcel_read_array_countPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h,
              ffi.Pointer<ffi.Int>)>>('rpc_port_parcel_read_array_count');
  late final _rpc_port_parcel_read_array_count =
      _rpc_port_parcel_read_array_countPtr
          .asFunction<int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Int>)>();

  /// @brief Reads a parcel from the data using @a parcelable.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] parcelable The interface to get data from parcel handle
  /// @param[in] data Data which get from parcel
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write()
  int rpc_port_parcel_read(
    rpc_port_parcel_h h,
    ffi.Pointer<rpc_port_parcelable_t> parcelable,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _rpc_port_parcel_read(
      h,
      parcelable,
      data,
    );
  }

  late final _rpc_port_parcel_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              rpc_port_parcel_h,
              ffi.Pointer<rpc_port_parcelable_t>,
              ffi.Pointer<ffi.Void>)>>('rpc_port_parcel_read');
  late final _rpc_port_parcel_read = _rpc_port_parcel_readPtr.asFunction<
      int Function(rpc_port_parcel_h, ffi.Pointer<rpc_port_parcelable_t>,
          ffi.Pointer<ffi.Void>)>();

  /// @brief Reads bytes from rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[out] buf The array buffer to read
  /// @param[in] size Bytes to read
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_bool()
  int rpc_port_parcel_burst_read(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.UnsignedChar> buf,
    int size,
  ) {
    return _rpc_port_parcel_burst_read(
      h,
      buf,
      size,
    );
  }

  late final _rpc_port_parcel_burst_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h, ffi.Pointer<ffi.UnsignedChar>,
              ffi.UnsignedInt)>>('rpc_port_parcel_burst_read');
  late final _rpc_port_parcel_burst_read =
      _rpc_port_parcel_burst_readPtr.asFunction<
          int Function(
              rpc_port_parcel_h, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Writes bytes to rpc port parcel handle.
  /// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
  /// @param[in] h The rpc port parcel handle
  /// @param[in] buf The array buffer to write
  /// @param[in] size Bytes to write
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER The specified @a h is NULL
  /// @see rpc_port_parcel_write_bool()
  int rpc_port_parcel_burst_write(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.UnsignedChar> buf,
    int size,
  ) {
    return _rpc_port_parcel_burst_write(
      h,
      buf,
      size,
    );
  }

  late final _rpc_port_parcel_burst_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_h, ffi.Pointer<ffi.UnsignedChar>,
              ffi.UnsignedInt)>>('rpc_port_parcel_burst_write');
  late final _rpc_port_parcel_burst_write =
      _rpc_port_parcel_burst_writePtr.asFunction<
          int Function(
              rpc_port_parcel_h, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Gets the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @remarks The @a header is managed by the platform and will be released when rpc_port_parcel_destroy() is called.
  /// @param[in] h The rpc port parcel handle
  /// @param[out] header The header handle of the rpc port parcel
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  int rpc_port_parcel_get_header(
    rpc_port_parcel_h h,
    ffi.Pointer<rpc_port_parcel_header_h> header,
  ) {
    return _rpc_port_parcel_get_header(
      h,
      header,
    );
  }

  late final _rpc_port_parcel_get_headerPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  rpc_port_parcel_h, ffi.Pointer<rpc_port_parcel_header_h>)>>(
      'rpc_port_parcel_get_header');
  late final _rpc_port_parcel_get_header =
      _rpc_port_parcel_get_headerPtr.asFunction<
          int Function(
              rpc_port_parcel_h, ffi.Pointer<rpc_port_parcel_header_h>)>();

  /// @brief Sets the tag to the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @param[in] header The header handle of the rpc port parcel
  /// @param[in] tag The tag
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see rpc_port_parcel_header_get_tag()
  int rpc_port_parcel_header_set_tag(
    rpc_port_parcel_header_h header,
    ffi.Pointer<ffi.Char> tag,
  ) {
    return _rpc_port_parcel_header_set_tag(
      header,
      tag,
    );
  }

  late final _rpc_port_parcel_header_set_tagPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_header_h,
              ffi.Pointer<ffi.Char>)>>('rpc_port_parcel_header_set_tag');
  late final _rpc_port_parcel_header_set_tag =
      _rpc_port_parcel_header_set_tagPtr.asFunction<
          int Function(rpc_port_parcel_header_h, ffi.Pointer<ffi.Char>)>();

  /// @brief Gets the tag from the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @remarks The @a tag should be released using free().
  /// @param[in] header The header handle of the rpc port parcel
  /// @param[out] tag The tag
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_OUT_OF_MEMORY Out of memory
  /// @see rpc_port_parcel_header_set_tag()
  int rpc_port_parcel_header_get_tag(
    rpc_port_parcel_header_h header,
    ffi.Pointer<ffi.Pointer<ffi.Char>> tag,
  ) {
    return _rpc_port_parcel_header_get_tag(
      header,
      tag,
    );
  }

  late final _rpc_port_parcel_header_get_tagPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(rpc_port_parcel_header_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'rpc_port_parcel_header_get_tag');
  late final _rpc_port_parcel_header_get_tag =
      _rpc_port_parcel_header_get_tagPtr.asFunction<
          int Function(
              rpc_port_parcel_header_h, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// @brief Sets the sequence number to the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @param[in] header The header handle of the rpc port parcel
  /// @param[in] seq_num The sequence number
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see rpc_port_parcel_header_get_seq_num()
  int rpc_port_parcel_header_set_seq_num(
    rpc_port_parcel_header_h header,
    int seq_num,
  ) {
    return _rpc_port_parcel_header_set_seq_num(
      header,
      seq_num,
    );
  }

  late final _rpc_port_parcel_header_set_seq_numPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(rpc_port_parcel_header_h, ffi.Int)>>(
      'rpc_port_parcel_header_set_seq_num');
  late final _rpc_port_parcel_header_set_seq_num =
      _rpc_port_parcel_header_set_seq_numPtr
          .asFunction<int Function(rpc_port_parcel_header_h, int)>();

  /// @brief Gets the sequence number from the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @param[in] header The header handle of the rpc port parcel
  /// @param[out] seq_num The sequence number
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @see rpc_port_parcel_header_set_seq_num()
  int rpc_port_parcel_header_get_seq_num(
    rpc_port_parcel_header_h header,
    ffi.Pointer<ffi.Int> seq_num,
  ) {
    return _rpc_port_parcel_header_get_seq_num(
      header,
      seq_num,
    );
  }

  late final _rpc_port_parcel_header_get_seq_numPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(rpc_port_parcel_header_h,
              ffi.Pointer<ffi.Int>)>>('rpc_port_parcel_header_get_seq_num');
  late final _rpc_port_parcel_header_get_seq_num =
      _rpc_port_parcel_header_get_seq_numPtr.asFunction<
          int Function(rpc_port_parcel_header_h, ffi.Pointer<ffi.Int>)>();

  /// @brief Gets the timestamp from the header handle of the rpc port parcel.
  /// @since_tizen 6.5
  /// @remarks The @a timestamp represents monotonic time since some unspecified starting point.
  /// To get elapsed time properly, you have to get the timestamp using the clock_gettime() with CLOCK_MONITONIC_RAW.
  /// @param[in] header The header handle of the rpc port parcel
  /// @param[out] timestamp The timestamp
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  int rpc_port_parcel_header_get_timestamp(
    rpc_port_parcel_header_h header,
    ffi.Pointer<time.timespec> timestamp,
  ) {
    return _rpc_port_parcel_header_get_timestamp(
      header,
      timestamp,
    );
  }

  late final _rpc_port_parcel_header_get_timestampPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  rpc_port_parcel_header_h, ffi.Pointer<time.timespec>)>>(
      'rpc_port_parcel_header_get_timestamp');
  late final _rpc_port_parcel_header_get_timestamp =
      _rpc_port_parcel_header_get_timestampPtr.asFunction<
          int Function(rpc_port_parcel_header_h, ffi.Pointer<time.timespec>)>();

  /// @brief Gets the raw data of the rpc port parcel handle.
  /// @since_tizen 6.5
  /// @remarks You MUST NOT release @a raw using free(). It's managed by platform.
  /// @param[in] h The rpc port parcel handle
  /// @param[out] raw The raw data
  /// @param[out] size The size of the raw data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  int rpc_port_parcel_get_raw(
    rpc_port_parcel_h h,
    ffi.Pointer<ffi.Pointer<ffi.Void>> raw,
    ffi.Pointer<ffi.UnsignedInt> size,
  ) {
    return _rpc_port_parcel_get_raw(
      h,
      raw,
      size,
    );
  }

  late final _rpc_port_parcel_get_rawPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              rpc_port_parcel_h,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
              ffi.Pointer<ffi.UnsignedInt>)>>('rpc_port_parcel_get_raw');
  late final _rpc_port_parcel_get_raw = _rpc_port_parcel_get_rawPtr.asFunction<
      int Function(rpc_port_parcel_h, ffi.Pointer<ffi.Pointer<ffi.Void>>,
          ffi.Pointer<ffi.UnsignedInt>)>();

  /// @brief Creates the rpc port parcel handle with given the raw data.
  /// @since_tizen 6.5
  /// @remarks You must release @a h using rpc_port_parcel_destroy().
  /// @param[out] h The rpc port parcel handle
  /// @param[in] raw The raw data
  /// @param[in] size The size of the raw data
  /// @return @c 0 on success,
  /// otherwise a negative error value
  /// @retval #RPC_PORT_ERROR_NONE Successful
  /// @retval #RPC_PORT_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #RPC_PORT_ERROR_OUT_OF_MEMORY Out of memory
  /// @see rpc_port_parcel_destroy()
  int rpc_port_parcel_create_from_raw(
    ffi.Pointer<rpc_port_parcel_h> h,
    ffi.Pointer<ffi.Void> raw,
    int size,
  ) {
    return _rpc_port_parcel_create_from_raw(
      h,
      raw,
      size,
    );
  }

  late final _rpc_port_parcel_create_from_rawPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<rpc_port_parcel_h>,
              ffi.Pointer<ffi.Void>,
              ffi.UnsignedInt)>>('rpc_port_parcel_create_from_raw');
  late final _rpc_port_parcel_create_from_raw =
      _rpc_port_parcel_create_from_rawPtr.asFunction<
          int Function(
              ffi.Pointer<rpc_port_parcel_h>, ffi.Pointer<ffi.Void>, int)>();
}

/// @brief Enumeration for error codes of a rpc port.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
abstract class rpc_port_error_e {
  /// < Successful
  static const int RPC_PORT_ERROR_NONE = 0;

  /// < Internal I/O error
  static const int RPC_PORT_ERROR_IO_ERROR = -5;

  /// < Out of memory
  static const int RPC_PORT_ERROR_OUT_OF_MEMORY = -12;

  /// < Invalid parameter
  static const int RPC_PORT_ERROR_INVALID_PARAMETER = -22;

  /// < Permission denied
  static const int RPC_PORT_ERROR_PERMISSION_DENIED = -13;
}

/// @brief Enumeration for types of communication channels.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
abstract class rpc_port_port_type_e {
  /// < Main channel
  static const int RPC_PORT_PORT_MAIN = 0;

  /// < The channel for callbacks
  static const int RPC_PORT_PORT_CALLBACK = 1;
}

/// @brief The rpc port handle.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
typedef rpc_port_h = ffi.Pointer<ffi.Void>;

/// @brief The rpc port proxy handle.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
typedef rpc_port_proxy_h = ffi.Pointer<ffi.Void>;

/// @brief Called when the proxy is connected.
/// @details The function is called when the proxy is connected with stub by port.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] receiver The target stub app id
/// @param[in] port_name The name of the port
/// @param[in] port The rpc port handle for reading and writing
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_proxy_connected_event_cb = ffi
    .Pointer<ffi.NativeFunction<rpc_port_proxy_connected_event_cbFunction>>;
typedef rpc_port_proxy_connected_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    rpc_port_h port,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_proxy_connected_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    rpc_port_h port,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the proxy is disconnected.
/// @details The function is called when the proxy is disconnected from stub.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] receiver The target stub app id
/// @param[in] port_name The name of the port
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_proxy_disconnected_event_cb = ffi
    .Pointer<ffi.NativeFunction<rpc_port_proxy_disconnected_event_cbFunction>>;
typedef rpc_port_proxy_disconnected_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_proxy_disconnected_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the proxy is rejected.
/// @details The function is called when the proxy is rejected to connect stub.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] receiver The target stub app id
/// @param[in] port_name The name of the port
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_proxy_rejected_event_cb
    = ffi.Pointer<ffi.NativeFunction<rpc_port_proxy_rejected_event_cbFunction>>;
typedef rpc_port_proxy_rejected_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_proxy_rejected_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the proxy received data.
/// @details The function is called when the proxy received data from stub.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] receiver The target stub app id
/// @param[in] port_name The name of the port
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_proxy_received_event_cb
    = ffi.Pointer<ffi.NativeFunction<rpc_port_proxy_received_event_cbFunction>>;
typedef rpc_port_proxy_received_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_proxy_received_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> receiver,
    ffi.Pointer<ffi.Char> port_name,
    ffi.Pointer<ffi.Void> user_data);

/// @brief The rpc port stub handle.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
typedef rpc_port_stub_h = ffi.Pointer<ffi.Void>;

/// @brief Called when the proxy is connected with stub.
/// @details The function is called when the proxy is connected with stub.
/// When a proxy connects to stub several times with new port,
/// you can handle each request by using @a instance.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] sender The target proxy app id
/// @param[in] instance The information of the request
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_stub_connected_event_cb
    = ffi.Pointer<ffi.NativeFunction<rpc_port_stub_connected_event_cbFunction>>;
typedef rpc_port_stub_connected_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_stub_connected_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the proxy is disconnected from stub.
/// @details The function is called when the proxy is disconnected from stub.
/// When a proxy is disconnected, you can check the request
/// by using @a instance.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] sender The target proxy app id
/// @param[in] instance The information of the request
/// @param[in] user_data The user data passed from the register function
typedef rpc_port_stub_disconnected_event_cb = ffi
    .Pointer<ffi.NativeFunction<rpc_port_stub_disconnected_event_cbFunction>>;
typedef rpc_port_stub_disconnected_event_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_stub_disconnected_event_cbFunction = void Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Called when the stub received data from proxy.
/// @details The function is called when the stub received data from stub.
/// When a stub received data from several ports, you can handle
/// each request by using @a instance. If the function returns non zero
/// value, the stub is disconnected.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
/// @param[in] sender The target proxy app id
/// @param[in] instance The information of the request
/// @param[in] port The rpc port handle for reading and writing
/// @param[in] user_data The user data passed from the register function
/// @return @c zero to continue receive data with the sender,
/// otherwise @c nonzero to disconnect from the port
typedef rpc_port_stub_received_event_cb
    = ffi.Pointer<ffi.NativeFunction<rpc_port_stub_received_event_cbFunction>>;
typedef rpc_port_stub_received_event_cbFunction = ffi.Int Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    rpc_port_h port,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartrpc_port_stub_received_event_cbFunction = int Function(
    ffi.Pointer<ffi.Char> sender,
    ffi.Pointer<ffi.Char> instance,
    rpc_port_h port,
    ffi.Pointer<ffi.Void> user_data);

/// @brief The interface for converting data to/from a parcel.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
final class __rpc_port_parcelable extends ffi.Struct {
  /// < The function pointer to read from parcel
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              rpc_port_parcel_h h, ffi.Pointer<ffi.Void> data)>> to;

  /// < The function pointer to write to parcel
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              rpc_port_parcel_h h, ffi.Pointer<ffi.Void> data)>> from;
}

/// @brief The rpc port parcel handle.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
typedef rpc_port_parcel_h = ffi.Pointer<ffi.Void>;

/// @brief The interface for converting data to/from a parcel.
/// @since_tizen @if MOBILE 4.0 @elseif WEARABLE 5.0 @endif
typedef rpc_port_parcelable_t = __rpc_port_parcelable;

/// @brief The header handle of the rpc port parcel.
/// @since_tizen 6.5
typedef rpc_port_parcel_header_h = ffi.Pointer<ffi.Void>;
