// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_mv_common.dart' as mv_common;

/// Dart bindings for Tizen mv_barcode_detector APIs.
class Tizen60MvBarcodeDetector {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen60MvBarcodeDetector(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen60MvBarcodeDetector.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Detects barcode(s) on source and reads message from it.
  ///
  /// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
  /// @param [in] source            The media source handle
  /// @param [in] engine_cfg        The handle to the configuration of the engine
  /// @param [in] roi               Region of interest - rectangular area on the
  /// @a source which will be used for barcode detection
  /// Note that @a roi should be inside area on the
  /// @a source.
  /// @param [in] detect_cb         The callback for result handling
  /// @param [in] user_data    The user data to be passed to the callback function
  /// @return @c 0 on success, otherwise a negative error value
  /// @retval #MEDIA_VISION_ERROR_NONE Successful
  /// @retval #MEDIA_VISION_ERROR_INVALID_PARAMETER Invalid parameter
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED Not supported
  /// @retval #MEDIA_VISION_ERROR_NOT_SUPPORTED_FORMAT Not supported format
  /// @retval #MEDIA_VISION_ERROR_INTERNAL Internal error
  ///
  /// @pre Create a source handle by calling mv_create_source()
  /// @pre Create an engine configuration handle by calling
  /// mv_create_engine_config(), otherwise use NULL
  ///
  /// @see mv_barcode_detected_cb()
  int mv_barcode_detect(
    mv_common.mv_source_h source,
    mv_common.mv_engine_config_h engine_cfg,
    mv_common.mv_rectangle_s roi,
    mv_barcode_detected_cb detect_cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _mv_barcode_detect(
      source,
      engine_cfg,
      roi,
      detect_cb,
      user_data,
    );
  }

  late final _mv_barcode_detectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              mv_common.mv_source_h,
              mv_common.mv_engine_config_h,
              mv_common.mv_rectangle_s,
              mv_barcode_detected_cb,
              ffi.Pointer<ffi.Void>)>>('mv_barcode_detect');
  late final _mv_barcode_detect = _mv_barcode_detectPtr.asFunction<
      int Function(
          mv_common.mv_source_h,
          mv_common.mv_engine_config_h,
          mv_common.mv_rectangle_s,
          mv_barcode_detected_cb,
          ffi.Pointer<ffi.Void>)>();
}

/// @brief Enumeration to target attribute
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
abstract class mv_barcode_detect_attr_target_e {
  /// < 1D and 2D
  static const int MV_BARCODE_DETECT_ATTR_TARGET_ALL = 0;

  /// < 1D barcode only
  static const int MV_BARCODE_DETECT_ATTR_TARGET_1D_BARCODE = 1;

  /// < 2D barcode only
  static const int MV_BARCODE_DETECT_ATTR_TARGET_2D_BARCODE = 2;
}

/// @brief Called when barcode detection is completed.
/// @details If no barcode is detected then the method will be called, barcodes
/// and states will be equal to NULL, and @a number_of_barcodes - 0.
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
/// @param [in] source               The handle to the media source
/// @param [in] engine_cfg           The handle to the configuration of the engine
/// @param [in] barcode_locations    The quadrangle locations of detected barcodes
/// @param [in] messages             The decoded messages of barcodes
/// @param [in] types                The types of detected barcodes
/// @param [in] number_of_barcodes   The number of detected barcodes
/// @param [in] user_data            The user data passed from
/// the mv_barcode_detect() function
///
/// @pre mv_barcode_detect() invokes this callback
///
/// @see mv_barcode_detect()
typedef mv_barcode_detected_cb
    = ffi.Pointer<ffi.NativeFunction<mv_barcode_detected_cbFunction>>;
typedef mv_barcode_detected_cbFunction = ffi.Void Function(
    mv_common.mv_source_h source,
    mv_common.mv_engine_config_h engine_cfg,
    ffi.Pointer<mv_common.mv_quadrangle_s> barcode_locations,
    ffi.Pointer<ffi.Pointer<ffi.Char>> messages,
    ffi.Pointer<ffi.Int32> types,
    ffi.Int number_of_barcodes,
    ffi.Pointer<ffi.Void> user_data);
typedef Dartmv_barcode_detected_cbFunction = void Function(
    mv_common.mv_source_h source,
    mv_common.mv_engine_config_h engine_cfg,
    ffi.Pointer<mv_common.mv_quadrangle_s> barcode_locations,
    ffi.Pointer<ffi.Pointer<ffi.Char>> messages,
    ffi.Pointer<ffi.Int32> types,
    int number_of_barcodes,
    ffi.Pointer<ffi.Void> user_data);

/// @brief Enumeration for supported barcode types.
/// @details QR codes (versions 1 to 40) and set of 1D barcodes are supported
///
/// @since_tizen @if MOBILE 2.4 @else 3.0 @endif
/// @remarks #MV_BARCODE_UNDEFINED is deprecated. Use #MV_BARCODE_UNKNOWN instead
abstract class mv_barcode_type_e {
  /// < 2D barcode - Quick Response code
  static const int MV_BARCODE_QR = 0;

  /// < 1D barcode - Universal Product Code with 12-digit
  static const int MV_BARCODE_UPC_A = 1;

  /// < 1D barcode - Universal Product Code with 6-digit
  static const int MV_BARCODE_UPC_E = 2;

  /// < 1D barcode - International Article Number with 8-digit
  static const int MV_BARCODE_EAN_8 = 3;

  /// < 1D barcode - International Article Number with 13-digit
  static const int MV_BARCODE_EAN_13 = 4;

  /// < 1D barcode - Code 128
  static const int MV_BARCODE_CODE128 = 5;

  /// < 1D barcode - Code 39
  static const int MV_BARCODE_CODE39 = 6;

  /// < 1D barcode - Interleaved Two of Five
  static const int MV_BARCODE_I2_5 = 7;

  /// < @deprecated Undefined (Deprecated since 6.0)
  static const int MV_BARCODE_UNDEFINED = 8;

  /// < 1D barcode - International Article Number with 2-digit(add-on) (since 6.0)
  static const int MV_BARCODE_EAN_2 = 9;

  /// < 1D barcode - International Article Number with 5-digit(add-on) (since 6.0)
  static const int MV_BARCODE_EAN_5 = 10;

  /// < 1D barcode - Code 93 (since 6.0)
  static const int MV_BARCODE_CODE93 = 11;

  /// < 1D barcode - CODABAR (since 6.0)
  static const int MV_BARCODE_CODABAR = 12;

  /// < 1D barcode - GS1 DATABAR (since 6.0)
  static const int MV_BARCODE_DATABAR = 13;

  /// < 1D barcode - GS1 DATABAR EXPAND(since 6.0)
  static const int MV_BARCODE_DATABAR_EXPAND = 14;

  /// < Unknown (since 6.0)
  static const int MV_BARCODE_UNKNOWN = 100;
}

const String MV_BARCODE_DETECT_ATTR_TARGET = 'MV_BARCODE_DETECT_ATTR_TARGET';
