/// {@category 6.0/tizen}
library tizen_interop_6_0.push;

// Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;
import 'generated_bindings_capi_appfw_app_control.dart' as app_control;

/// Dart bindings for Tizen push APIs.
/// {@category 6.0/tizen}
class Tizen60Push {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen60Push(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen60Push.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Connects to the push service and sets callback functions.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/push>
  ///
  /// **Remarks:**
  /// - If there is a connection between an application and the push service,
  /// - the notify callback passes the notification upon its arrival.
  /// - Otherwise, the push service posts a UI notification to alert users.
  /// - The connection should be freed with push_service_disconnect() by you.
  ///
  /// **Parameters:**
  /// - `push_app_id` (in): App id received from Tizen Push Server team
  /// - `state_callback` (in): State callback function
  /// - `notify_callback` (in): Notify callback function
  /// - `user_data` (in): User data to pass to <I>state_cb</I> and <I>notify_cb</I>
  /// - `connection` (out): The connection handle to the push service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: Connection to the daemon failed
  /// - `PUSH_SERVICE_ERROR_PERMISSION_DENIED`: No push privilege
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **Preconditions:**
  /// - There is no connection to the push service for the <I>app_id</I>.
  ///
  /// **Postconditions:**
  /// - The state callback will be called to let you know the current registration state immediately.
  ///
  /// **See also:**
  /// - `push_service_disconnect()`
  int push_service_connect(
    ffi.Pointer<ffi.Char> push_app_id,
    push_service_state_cb state_callback,
    push_service_notify_cb notify_callback,
    ffi.Pointer<ffi.Void> user_data,
    ffi.Pointer<push_service_connection_h> connection,
  ) {
    return _push_service_connect(
      push_app_id,
      state_callback,
      notify_callback,
      user_data,
      connection,
    );
  }

  late final _push_service_connectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              push_service_state_cb,
              push_service_notify_cb,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<push_service_connection_h>)>>('push_service_connect');
  late final _push_service_connect = _push_service_connectPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          push_service_state_cb,
          push_service_notify_cb,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<push_service_connection_h>)>();

  /// . Closes the connection and releases all its resources
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - If you call this function in the push callback functions,
  /// - it may cause your application to crash.
  /// - The specific error code can be obtained using the get_last_result()
  /// - Error codes are described in the exception section.
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  ///
  /// **Exceptions:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_connect()`
  void push_service_disconnect(
    push_service_connection_h connection,
  ) {
    return _push_service_disconnect(
      connection,
    );
  }

  late final _push_service_disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(push_service_connection_h)>>(
          'push_service_disconnect');
  late final _push_service_disconnect = _push_service_disconnectPtr
      .asFunction<void Function(push_service_connection_h)>();

  /// Registers an application to the push server.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  /// - `result_callback` (in): Result callback function
  /// - `user_data` (in): User data to pass to <I>result_cb</I>
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: No connection to the push service
  /// - `PUSH_SERVICE_ERROR_OPERATION_FAILED`: Operation failed
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **Preconditions:**
  /// - The application should be connected to the push service.
  ///
  /// **Postconditions:**
  /// - As a result, the state callback will be invoked.
  ///
  /// **See also:**
  /// - `push_service_deregister()`
  int push_service_register(
    push_service_connection_h connection,
    push_service_result_cb result_callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _push_service_register(
      connection,
      result_callback,
      user_data,
    );
  }

  late final _push_service_registerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(push_service_connection_h, push_service_result_cb,
              ffi.Pointer<ffi.Void>)>>('push_service_register');
  late final _push_service_register = _push_service_registerPtr.asFunction<
      int Function(push_service_connection_h, push_service_result_cb,
          ffi.Pointer<ffi.Void>)>();

  /// Deregisters an application from the Push server.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  /// - `result_callback` (in): Result callback function
  /// - `user_data` (in): User data to pass to <I>result_cb</I>
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: No connection to the push service
  /// - `PUSH_SERVICE_ERROR_OPERATION_FAILED`: Operation failed
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **Preconditions:**
  /// - The application should be connected to the push service.
  ///
  /// **Postconditions:**
  /// - As a result, the state callback will be invoked.
  ///
  /// **See also:**
  /// - `push_service_register()`
  int push_service_deregister(
    push_service_connection_h connection,
    push_service_result_cb result_callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _push_service_deregister(
      connection,
      result_callback,
      user_data,
    );
  }

  late final _push_service_deregisterPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(push_service_connection_h, push_service_result_cb,
              ffi.Pointer<ffi.Void>)>>('push_service_deregister');
  late final _push_service_deregister = _push_service_deregisterPtr.asFunction<
      int Function(push_service_connection_h, push_service_result_cb,
          ffi.Pointer<ffi.Void>)>();

  /// Retrieves the payload data of a notification that forcibly launched the app.
  ///
  /// When a notification arrives at the device with the "LAUNCH" option or a user clicks a notification in the quick panel, the push daemon forcibly launches the app and delivers the notification to the app as a bundle. This function returns the payload data in the notification.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/push>
  ///
  /// **Remarks:**
  /// - This function must be called in the app control callback function.
  /// - You must release the payload data using free().
  /// - push_service_app_control_to_notification() is preferred to this API.
  /// - The specific error code can be obtained using the get_last_result()
  /// - Error codes are described in the exception section.
  ///
  /// **Parameters:**
  /// - `app_control` (in): The app control handle that is handed over in the app control callback function
  /// - `operation` (in): The operation in the app control handle retrieved by app_control_get_operation()
  ///
  /// **Returns:**
  /// - The payload data (appData) in the notification NULL if the app is not launched by a push notification.
  ///
  /// **Exceptions:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: Not launched by a notification
  /// - `PUSH_SERVICE_ERROR_OPERATION_FAILED`: Operation fail
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: Connection to the daemon failed
  /// - `PUSH_SERVICE_ERROR_PERMISSION_DENIED`: No push privilege
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `app_control_get_operation()`
  ffi.Pointer<ffi.Char> push_service_app_control_to_noti_data(
    app_control.app_control_h app_control,
    ffi.Pointer<ffi.Char> operation,
  ) {
    return _push_service_app_control_to_noti_data(
      app_control,
      operation,
    );
  }

  late final _push_service_app_control_to_noti_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(app_control.app_control_h,
              ffi.Pointer<ffi.Char>)>>('push_service_app_control_to_noti_data');
  late final _push_service_app_control_to_noti_data =
      _push_service_app_control_to_noti_dataPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              app_control.app_control_h, ffi.Pointer<ffi.Char>)>();

  /// Retrieves the notification that forcibly launched the app.
  ///
  /// When a notification arrives at the device with the "LAUNCH" option or a user clicks a notification in the quick panel, the push daemon forcibly launches the app and delivers the notification to the app as a bundle. This function returns the notification from the bundle.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/push>
  ///
  /// **Remarks:**
  /// - This function must be called in the app control callback function.
  /// - You must release the notification using push_service_free_notification().
  ///
  /// **Parameters:**
  /// - `app_control` (in): The app control handle that is handed over in the app control callback function
  /// - `operation` (in): The operation in the app control handle retrieved by app_control_get_operation()
  /// - `noti` (out): The handle of the notification that forcibly launched the app
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: Not launched by a notification
  /// - `PUSH_SERVICE_ERROR_OPERATION_FAILED`: Operation fail
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: Connection to the daemon failed
  /// - `PUSH_SERVICE_ERROR_PERMISSION_DENIED`: No push privilege
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_free_notification()`
  /// - `app_control_get_operation()`
  int push_service_app_control_to_notification(
    app_control.app_control_h app_control,
    ffi.Pointer<ffi.Char> operation,
    ffi.Pointer<push_service_notification_h> noti,
  ) {
    return _push_service_app_control_to_notification(
      app_control,
      operation,
      noti,
    );
  }

  late final _push_service_app_control_to_notificationPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(app_control.app_control_h, ffi.Pointer<ffi.Char>,
                  ffi.Pointer<push_service_notification_h>)>>(
      'push_service_app_control_to_notification');
  late final _push_service_app_control_to_notification =
      _push_service_app_control_to_notificationPtr.asFunction<
          int Function(app_control.app_control_h, ffi.Pointer<ffi.Char>,
              ffi.Pointer<push_service_notification_h>)>();

  /// Gets notification data sent by the server.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - You must release `data` using free().
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `data` (out): The notification data Set NULL if error but <I>`PUSH_SERVICE_ERROR_INVALID_PARAMETER`</I>
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_request_unread_notification()`
  int push_service_get_notification_data(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Pointer<ffi.Char>> data,
  ) {
    return _push_service_get_notification_data(
      notification,
      data,
    );
  }

  late final _push_service_get_notification_dataPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_notification_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_notification_data');
  late final _push_service_get_notification_data =
      _push_service_get_notification_dataPtr.asFunction<
          int Function(push_service_notification_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the notification message sent by the server.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - The <I>msg</I> must be released with free().
  /// - push_service_request_unread_notification() is
  /// - preferred to this API.
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `msg` (out): The notification message Set NULL if error but <I>`PUSH_SERVICE_ERROR_INVALID_PARAMETER`</I>
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_get_unread_notification()`
  int push_service_get_notification_message(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Pointer<ffi.Char>> msg,
  ) {
    return _push_service_get_notification_message(
      notification,
      msg,
    );
  }

  late final _push_service_get_notification_messagePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_notification_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_notification_message');
  late final _push_service_get_notification_message =
      _push_service_get_notification_messagePtr.asFunction<
          int Function(push_service_notification_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the received time of the notification message.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `received_time` (out): The received time of the notification message The `received_time` is based on UTC.
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_request_unread_notification()`
  int push_service_get_notification_time(
    push_service_notification_h notification,
    ffi.Pointer<ffi.LongLong> received_time,
  ) {
    return _push_service_get_notification_time(
      notification,
      received_time,
    );
  }

  late final _push_service_get_notification_timePtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(
                  push_service_notification_h, ffi.Pointer<ffi.LongLong>)>>(
      'push_service_get_notification_time');
  late final _push_service_get_notification_time =
      _push_service_get_notification_timePtr.asFunction<
          int Function(
              push_service_notification_h, ffi.Pointer<ffi.LongLong>)>();

  /// Gets the sender of the notification.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - You must release `sender` using free().
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `sender` (out): The sender Set `NULL` if error but `PUSH_SERVICE_ERROR_INVALID_PARAMETER`
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_get_unread_notification()`
  int push_service_get_notification_sender(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Pointer<ffi.Char>> sender,
  ) {
    return _push_service_get_notification_sender(
      notification,
      sender,
    );
  }

  late final _push_service_get_notification_senderPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_notification_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_notification_sender');
  late final _push_service_get_notification_sender =
      _push_service_get_notification_senderPtr.asFunction<
          int Function(push_service_notification_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the session ID of the notification.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - You must release `session_info` using free().
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `session_info` (out): The session ID Set `NULL` if error but `PUSH_SERVICE_ERROR_INVALID_PARAMETER`
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_request_unread_notification()`
  int push_service_get_notification_session_info(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Pointer<ffi.Char>> session_info,
  ) {
    return _push_service_get_notification_session_info(
      notification,
      session_info,
    );
  }

  late final _push_service_get_notification_session_infoPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_notification_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_notification_session_info');
  late final _push_service_get_notification_session_info =
      _push_service_get_notification_session_infoPtr.asFunction<
          int Function(push_service_notification_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Gets the request ID assigned by the sender.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - You must release `request_id` using free().
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `request_id` (out): The request ID Set `NULL` if error but `PUSH_SERVICE_ERROR_INVALID_PARAMETER`
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_request_unread_notification()`
  int push_service_get_notification_request_id(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Pointer<ffi.Char>> request_id,
  ) {
    return _push_service_get_notification_request_id(
      notification,
      request_id,
    );
  }

  late final _push_service_get_notification_request_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_notification_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_notification_request_id');
  late final _push_service_get_notification_request_id =
      _push_service_get_notification_request_idPtr.asFunction<
          int Function(push_service_notification_h,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// . Gets the value in the type field of the notification
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Parameters:**
  /// - `notification` (in): The notification handle
  /// - `type` (out): The type value assigned by the sender
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_notify_cb()`
  /// - `push_service_request_unread_notification()`
  int push_service_get_notification_type(
    push_service_notification_h notification,
    ffi.Pointer<ffi.Int> type,
  ) {
    return _push_service_get_notification_type(
      notification,
      type,
    );
  }

  late final _push_service_get_notification_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(push_service_notification_h,
              ffi.Pointer<ffi.Int>)>>('push_service_get_notification_type');
  late final _push_service_get_notification_type =
      _push_service_get_notification_typePtr.asFunction<
          int Function(push_service_notification_h, ffi.Pointer<ffi.Int>)>();

  /// Gets an unread notification message from the push server.
  ///
  /// If an application receives an unread message with this method, the message is removed from the system. This method can be called repeatedly until it returns <I>`PUSH_SERVICE_ERROR_NO_DATA`</I> But, this method does NOT guarantee order and reliability of notification messages. Some notification messages can be dropped when the system message queue is full.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - It is recommended to use push_service_request_unread_notification().
  /// - You must release `noti` using push_service_free_notification().
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  /// - `noti` (out): The notification handle
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No data available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_get_notification_message()`
  /// - `push_service_get_notification_time()`
  /// - `push_service_get_notification_data()`
  int push_service_get_unread_notification(
    push_service_connection_h connection,
    ffi.Pointer<push_service_notification_h> noti,
  ) {
    return _push_service_get_unread_notification(
      connection,
      noti,
    );
  }

  late final _push_service_get_unread_notificationPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_connection_h,
                  ffi.Pointer<push_service_notification_h>)>>(
      'push_service_get_unread_notification');
  late final _push_service_get_unread_notification =
      _push_service_get_unread_notificationPtr.asFunction<
          int Function(push_service_connection_h,
              ffi.Pointer<push_service_notification_h>)>();

  /// Requests unread notification messages to the push server.
  ///
  /// When the app wants to receive messages that arrived before it launched, this method should be called. Upon receiving this request, the daemon sends messages stored in its DB to the app. The notify_callback() method assigned in push_service_connect() will be called when these messages arrive. No need to call this method multiple times to receive multiple messages. This method does NOT guarantee order and reliability of notification messages.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - This method is preferred to push_service_get_unread_notification().
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NOT_CONNECTED`: Not connected to the daemon
  /// - `PUSH_SERVICE_ERROR_OPERATION_FAILED`: Error when sending the request
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  ///
  /// **See also:**
  /// - `push_service_get_unread_notification()`
  /// - `push_service_connect()`
  int push_service_request_unread_notification(
    push_service_connection_h connection,
  ) {
    return _push_service_request_unread_notification(
      connection,
    );
  }

  late final _push_service_request_unread_notificationPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(push_service_connection_h)>>(
          'push_service_request_unread_notification');
  late final _push_service_request_unread_notification =
      _push_service_request_unread_notificationPtr
          .asFunction<int Function(push_service_connection_h)>();

  /// Gets the registration ID in the <I>`PUSH_SERVICE_STATE_REGISTERED`</I> state.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - You must release `reg_id` using free().
  ///
  /// **Parameters:**
  /// - `connection` (in): The connection handle to the push service
  /// - `reg_id` (out): The registration ID Set NULL if error but <I>`PUSH_SERVICE_ERROR_INVALID_PARAMETER`</I>
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `PUSH_SERVICE_ERROR_NO_DATA`: No registration ID available
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  int push_service_get_registration_id(
    push_service_connection_h connection,
    ffi.Pointer<ffi.Pointer<ffi.Char>> reg_id,
  ) {
    return _push_service_get_registration_id(
      connection,
      reg_id,
    );
  }

  late final _push_service_get_registration_idPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(push_service_connection_h,
                  ffi.Pointer<ffi.Pointer<ffi.Char>>)>>(
      'push_service_get_registration_id');
  late final _push_service_get_registration_id =
      _push_service_get_registration_idPtr.asFunction<
          int Function(
              push_service_connection_h, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// Frees the notification handle.
  ///
  /// **Since Tizen:**
  /// - Mobile 2.3; Wearable 2.3.1
  ///
  /// **Remarks:**
  /// - The specific error code can be obtained using the get_last_result()
  /// - Error codes are described in the exception section.
  ///
  /// **Parameters:**
  /// - `noti` (in): The notification handle
  ///
  /// **Exceptions:**
  /// - `PUSH_SERVICE_ERROR_NONE`: Successful
  /// - `PUSH_SERVICE_ERROR_INVALID_PARAMETER`: Invalid parameter
  /// - `PUSH_SERVICE_ERROR_NOT_SUPPORTED`: Not supported feature
  void push_service_free_notification(
    push_service_notification_h noti,
  ) {
    return _push_service_free_notification(
      noti,
    );
  }

  late final _push_service_free_notificationPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(push_service_notification_h)>>(
      'push_service_free_notification');
  late final _push_service_free_notification =
      _push_service_free_notificationPtr
          .asFunction<void Function(push_service_notification_h)>();
}

/// Enumerations of error codes for push API.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
/// @nodoc
abstract class push_service_error_e {
  /// < Successful
  static const int PUSH_SERVICE_ERROR_NONE = 0;

  /// < Out of memory
  static const int PUSH_SERVICE_ERROR_OUT_OF_MEMORY = -12;

  /// < Invalid parameter
  static const int PUSH_SERVICE_ERROR_INVALID_PARAMETER = -22;

  /// < Not connected
  static const int PUSH_SERVICE_ERROR_NOT_CONNECTED = -29425664;

  /// < No data available
  static const int PUSH_SERVICE_ERROR_NO_DATA = -61;

  /// < Internal operation failed
  static const int PUSH_SERVICE_ERROR_OPERATION_FAILED = -1073741824;

  /// < No privilege to access the push service
  static const int PUSH_SERVICE_ERROR_PERMISSION_DENIED = -13;

  /// < Push service not supported
  static const int PUSH_SERVICE_ERROR_NOT_SUPPORTED = -1073741822;
}

/// Enumeration of registration states.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
/// @nodoc
abstract class push_service_state_e {
  /// < Registered
  static const int PUSH_SERVICE_STATE_REGISTERED = 0;

  /// < Unregistered
  static const int PUSH_SERVICE_STATE_UNREGISTERED = 1;

  /// < To change the provisioning server IP
  static const int PUSH_SERVICE_STATE_PROVISIONING_IPCHANGE = 2;

  /// < Ping interval is changing
  static const int PUSH_SERVICE_STATE_PING_CHANGE = 3;

  /// < Error
  static const int PUSH_SERVICE_STATE_ERROR = 4;
}

/// Enumeration of result.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
/// @nodoc
abstract class push_service_result_e {
  /// < Successful
  static const int PUSH_SERVICE_RESULT_SUCCESS = 0;

  /// < Request timed out
  static const int PUSH_SERVICE_RESULT_TIMEOUT = 1;

  /// < Push server error
  static const int PUSH_SERVICE_RESULT_SERVER_ERROR = 2;

  /// < System error
  static const int PUSH_SERVICE_RESULT_SYSTEM_ERROR = 3;
}

/// @nodoc
final class push_connection_s extends ffi.Opaque {}

/// @nodoc
final class push_notification_s extends ffi.Opaque {}

/// Called when the registration state is refreshed.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
///
/// **Remarks:**
/// - This callback will be invoked when the registration state is refreshed.
/// - If the registration or deregistration has succeeded, then this state callback must be called.
/// - In addition, the state can be changed if the push server deregisters the application.
///
/// **Parameters:**
/// - `state` (in): The registration state
/// - `err` (in): The error message
/// - `user_data` (in): The user data passed to this callback
///
/// **See also:**
/// - `push_service_connect()`
/// @nodoc
typedef push_service_state_cb
    = ffi.Pointer<ffi.NativeFunction<push_service_state_cbFunction>>;
/// @nodoc
typedef push_service_state_cbFunction = ffi.Void Function(ffi.Int32 state,
    ffi.Pointer<ffi.Char> err, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartpush_service_state_cbFunction = void Function(
    int state, ffi.Pointer<ffi.Char> err, ffi.Pointer<ffi.Void> user_data);

/// Called to handle a notification.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
///
/// **Parameters:**
/// - `noti` (in): A handle of the notification containing its payload The handle is available inside this callback only.
/// - `user_data` (in): The user data passed to this callback
///
/// **See also:**
/// - `push_service_connect()`
/// - `push_service_get_notification_data()`
/// @nodoc
typedef push_service_notify_cb
    = ffi.Pointer<ffi.NativeFunction<push_service_notify_cbFunction>>;
/// @nodoc
typedef push_service_notify_cbFunction = ffi.Void Function(
    push_service_notification_h noti, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartpush_service_notify_cbFunction = void Function(
    push_service_notification_h noti, ffi.Pointer<ffi.Void> user_data);

/// Notification delivered from the push server handle.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
/// @nodoc
typedef push_service_notification_h = ffi.Pointer<push_notification_s>;

/// Connection to the push service handle.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
/// @nodoc
typedef push_service_connection_h = ffi.Pointer<push_connection_s>;

/// Called with the result of a registration/deregistration.
///
/// **Since Tizen:**
/// - Mobile 2.3; Wearable 2.3.1
///
/// **Parameters:**
/// - `result` (in): The registration/deregistration result
/// - `msg` (in): The result message from the push server, otherwise `NULL`
/// - `user_data` (in): The user data passed to this callback
///
/// **See also:**
/// - `push_service_register()`
/// - `push_service_deregister()`
/// @nodoc
typedef push_service_result_cb
    = ffi.Pointer<ffi.NativeFunction<push_service_result_cbFunction>>;
/// @nodoc
typedef push_service_result_cbFunction = ffi.Void Function(ffi.Int32 result,
    ffi.Pointer<ffi.Char> msg, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartpush_service_result_cbFunction = void Function(
    int result, ffi.Pointer<ffi.Char> msg, ffi.Pointer<ffi.Void> user_data);

/// @nodoc
const String APP_CONTROL_DATA_PUSH_LAUNCH_TYPE =
    'http://tizen.org/appcontrol/data/push/launch_type';
