preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen90PrivilegeInfo'
description: 'Dart bindings for Tizen privilege-info APIs.'
output: '../../lib/src/bindings/9.0/generated_bindings_privilege_info.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints.h'
  include-directives:
    - '**/privilege_information.h'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'

  # include Tizen API directories
  - '-I./rootstraps/9.0/usr/include/'
  - '-I./rootstraps/9.0/usr/include/appcore-agent/'
  - '-I./rootstraps/9.0/usr/include/appfw/'
  - '-I./rootstraps/9.0/usr/include/asp/'
  - '-I./rootstraps/9.0/usr/include/badge/'
  - '-I./rootstraps/9.0/usr/include/calendar-service2/'
  - '-I./rootstraps/9.0/usr/include/cion/'
  - '-I./rootstraps/9.0/usr/include/ckm/'
  - '-I./rootstraps/9.0/usr/include/contacts-svc/'
  - '-I./rootstraps/9.0/usr/include/content/'
  - '-I./rootstraps/9.0/usr/include/context-service/'
  - '-I./rootstraps/9.0/usr/include/csr/'
  - '-I./rootstraps/9.0/usr/include/device-certificate-manager/'
  - '-I./rootstraps/9.0/usr/include/dlog/'
  - '-I./rootstraps/9.0/usr/include/eom/'
  - '-I./rootstraps/9.0/usr/include/feedback/'
  - '-I./rootstraps/9.0/usr/include/geofence/'
  - '-I./rootstraps/9.0/usr/include/iotcon/'
  - '-I./rootstraps/9.0/usr/include/location/'
  - '-I./rootstraps/9.0/usr/include/media/'
  - '-I./rootstraps/9.0/usr/include/media-content/'
  - '-I./rootstraps/9.0/usr/include/messaging/'
  - '-I./rootstraps/9.0/usr/include/metadata-editor/'
  - '-I./rootstraps/9.0/usr/include/mmi/'
  - '-I./rootstraps/9.0/usr/include/network/'
  - '-I./rootstraps/9.0/usr/include/nnstreamer/'
  - '-I./rootstraps/9.0/usr/include/nntrainer/'
  - '-I./rootstraps/9.0/usr/include/notification/'
  - '-I./rootstraps/9.0/usr/include/notification-ex/api/'
  - '-I./rootstraps/9.0/usr/include/nsd/'
  - '-I./rootstraps/9.0/usr/include/openssl/'
  - '-I./rootstraps/9.0/usr/include/phonenumber-utils/'
  - '-I./rootstraps/9.0/usr/include/privacy-privilege-manager/'
  - '-I./rootstraps/9.0/usr/include/rpc-port/'
  - '-I./rootstraps/9.0/usr/include/sensor/'
  - '-I./rootstraps/9.0/usr/include/shortcut/'
  - '-I./rootstraps/9.0/usr/include/storage/'
  - '-I./rootstraps/9.0/usr/include/system/'
  - '-I./rootstraps/9.0/usr/include/tizen-core/'
  - '-I./rootstraps/9.0/usr/include/web/'
  - '-I./rootstraps/9.0/usr/include/wifi-direct/'
  - '-I./rootstraps/9.0/usr/include/yaca/'
  # include EFL directories
  - '-I./rootstraps/9.0/usr/include/ecore-imf-1/'
  - '-I./rootstraps/9.0/usr/include/efl-1/'
  - '-I./rootstraps/9.0/usr/include/eina-1/'
  - '-I./rootstraps/9.0/usr/include/eina-1/eina/'
  - '-I./rootstraps/9.0/usr/include/emile-1/'
  - '-I./rootstraps/9.0/usr/include/eo-1/'
  - '-I./rootstraps/9.0/usr/include/evas-1/'

  # include glib directories
  - '-I./rootstraps/9.0/usr/include/glib-2.0/'
  - '-I./rootstraps/9.0/usr/lib/glib-2.0/include/'

enums:
  rename:
    '_+(.*)': '$1'
