preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60CapiSystemSensor'
description: 'Dart bindings for Tizen capi-system-sensor APIs.'
output: '../../lib/src/bindings/6.0/generated_bindings_capi_system_sensor.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints-capi-system-sensor.h'
  include-directives:
    - '**/sensor.h'

library-imports:
  ffi_lib: 'dart:ffi'

type-map:
  typedefs:
    'time_t':
      lib: 'ffi_lib'
      c-type: 'Long'
      dart-type: 'int'
    '__time_t':
      lib: 'ffi_lib'
      c-type: 'Long'
      dart-type: 'int'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.0/usr/include/'
  - '-I./rootstraps/6.0/usr/include/sensor/'

enums:
  rename:
    '_+(.*)': '$1'
