preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60CapiAppfwEvent'
description: 'Dart bindings for Tizen capi-appfw-event APIs.'
output: '../../lib/src/bindings/6.0/generated_bindings_capi_appfw_event.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints-capi-appfw-event.h'
  include-directives:
    - '**/app_event.h'

library-imports:
  bundle: 'generated_bindings_bundle.dart'

type-map:
  typedefs:
    'bundle':
      lib: 'bundle'
      c-type: 'bundle'
      dart-type: 'bundle'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.0/usr/include/'
  - '-I./rootstraps/6.0/usr/include/appfw/'

enums:
  rename:
    '_+(.*)': '$1'
