preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60Time'
description: 'Dart bindings for Tizen time header.'
output: '../../lib/src/bindings/6.0/generated_bindings_time.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints-time.h'
  include-directives:
    - '**/time.h'

library-imports:
  ffi_lib: 'dart:ffi'

type-map:
  typedefs:
    'pid_t':
      lib: 'ffi_lib'
      c-type: 'Int'
      dart-type: 'int'
    '__pid_t':
      lib: 'ffi_lib'
      c-type: 'Int'
      dart-type: 'int'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.0/usr/include/'

enums:
  rename:
    '_+(.*)': '$1'
