preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60FidoClient'

description: 'Dart bindings for Tizen fido-client APIs.'

output: '../../lib/src/bindings/6.0/generated_bindings_fido_client.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints-fido-client.h'
  include-directives:
    - '**/fido.h'
    - '**/fido_uaf_authenticator.h'
    - '**/fido_uaf_client.h'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.0/usr/include/'

enums:
  rename:
    '_+(.*)': '$1'
