preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60AppcoreAgent'
description: 'Dart bindings for Tizen appcore-agent APIs.'
output: '../../lib/src/bindings/6.0/generated_bindings_appcore_agent.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints-appcore-agent.h'
  include-directives:
    - '**/service_app.h'

library-imports:
  app_control: 'generated_bindings_capi_appfw_app_control.dart'
  app_common: 'generated_bindings_capi_appfw_app_common.dart'

type-map:
  typedefs:
    'app_control_h':
      lib: 'app_control'
      c-type: 'app_control_h'
      dart-type: 'app_control_h'
    'app_event_info_h':
      lib: 'app_common'
      c-type: 'app_event_info_h'
      dart-type: 'app_event_info_h'
    'app_event_handler_h':
      lib: 'app_common'
      c-type: 'app_event_handler_h'
      dart-type: 'app_event_handler_h'
    'app_event_cb':
      lib: 'app_common'
      c-type: 'app_event_cb'
      dart-type: 'app_event_cb'
  structs:
    'app_event_handler':
      lib: 'app_common'
      c-type: 'app_event_handler'
      dart-type: 'app_event_handler'
    'app_event_info':
      lib: 'app_common'
      c-type: 'app_event_info'
      dart-type: 'app_event_info'
  

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'
  - '-I./rootstraps/6.0/usr/include/'
  - '-I./rootstraps/6.0/usr/include/appcore-agent/'
  - '-I./rootstraps/6.0/usr/include/appfw/'

enums:
  rename:
    '_+(.*)': '$1'
    'app_event_type_e' : '_app_event_type_e'
