preamble: |
  // Copyright 2021 Samsung Electronics Co., Ltd. All rights reserved.
  // Use of this source code is governed by a BSD-style license that can be
  // found in the LICENSE file.
  // ignore_for_file: type=lint, unused_element, unused_field

name: 'Tizen60VcManager'
description: 'Dart bindings for Tizen vc_manager APIs.'
output: '../../lib/src/bindings/6.0/generated_bindings_vc_manager.dart'

llvm-path:
  - '/usr/lib/llvm-12'

headers:
  entry-points:
    - 'entrypoints.h'
  include-directives:
    - '**/voice_control_manager.h'

library-imports:
  vc: 'generated_bindings_vc.dart'

type-map:
  typedefs:
    'vc_supported_language_cb':
      lib: 'vc'
      c-type: 'vc_supported_language_cb'
      dart-type: 'vc_supported_language_cb'
    'vc_cmd_list_h':
      lib: 'vc'
      c-type: 'vc_cmd_list_h'
      dart-type: 'vc_cmd_list_h'
    'vc_result_cb':
      lib: 'vc'
      c-type: 'vc_result_cb'
      dart-type: 'vc_result_cb'
    'vc_state_changed_cb':
      lib: 'vc'
      c-type: 'vc_state_changed_cb'
      dart-type: 'vc_state_changed_cb'
    'vc_service_state_changed_cb':
      lib: 'vc'
      c-type: 'vc_service_state_changed_cb'
      dart-type: 'vc_service_state_changed_cb'
    'vc_current_language_changed_cb':
      lib: 'vc'
      c-type: 'vc_current_language_changed_cb'
      dart-type: 'vc_current_language_changed_cb'
    'vc_error_cb':
      lib: 'vc'
      c-type: 'vc_error_cb'
      dart-type: 'vc_error_cb'

compiler-opts:
  - '-m32'
  - '-Wno-incomplete-setjmp-declaration'

  # include Tizen API directories
  - '-I./rootstraps/6.0/usr/include/'
  - '-I./rootstraps/6.0/usr/include/appcore-agent/'
  - '-I./rootstraps/6.0/usr/include/appfw/'
  - '-I./rootstraps/6.0/usr/include/asp/'
  - '-I./rootstraps/6.0/usr/include/badge/'
  - '-I./rootstraps/6.0/usr/include/calendar-service2/'
  - '-I./rootstraps/6.0/usr/include/cbhm/'
  - '-I./rootstraps/6.0/usr/include/ckm/'
  - '-I./rootstraps/6.0/usr/include/contacts-svc/'
  - '-I./rootstraps/6.0/usr/include/content/'
  - '-I./rootstraps/6.0/usr/include/context-service/'
  - '-I./rootstraps/6.0/usr/include/csr/'
  - '-I./rootstraps/6.0/usr/include/device-certificate-manager/'
  - '-I./rootstraps/6.0/usr/include/dlog/'
  - '-I./rootstraps/6.0/usr/include/eom/'
  - '-I./rootstraps/6.0/usr/include/feedback/'
  - '-I./rootstraps/6.0/usr/include/geofence/'
  - '-I./rootstraps/6.0/usr/include/iotcon/'
  - '-I./rootstraps/6.0/usr/include/location/'
  - '-I./rootstraps/6.0/usr/include/media/'
  - '-I./rootstraps/6.0/usr/include/media-content/'
  - '-I./rootstraps/6.0/usr/include/messaging/'
  - '-I./rootstraps/6.0/usr/include/metadata-editor/'
  - '-I./rootstraps/6.0/usr/include/network/'
  - '-I./rootstraps/6.0/usr/include/notification/'
  - '-I./rootstraps/6.0/usr/include/notification-ex/api/'
  - '-I./rootstraps/6.0/usr/include/nsd/'
  - '-I./rootstraps/6.0/usr/include/phonenumber-utils/'
  - '-I./rootstraps/6.0/usr/include/privacy-privilege-manager/'
  - '-I./rootstraps/6.0/usr/include/rpc-port/'
  - '-I./rootstraps/6.0/usr/include/sensor/'
  - '-I./rootstraps/6.0/usr/include/shortcut/'
  - '-I./rootstraps/6.0/usr/include/storage/'
  - '-I./rootstraps/6.0/usr/include/system/'
  - '-I./rootstraps/6.0/usr/include/web/'
  - '-I./rootstraps/6.0/usr/include/wifi-direct/'
  - '-I./rootstraps/6.0/usr/include/yaca/'

  # include EFL directories
  - '-I./rootstraps/6.0/usr/include/ecore-imf-1/'
  - '-I./rootstraps/6.0/usr/include/efl-1/'
  - '-I./rootstraps/6.0/usr/include/eina-1/'
  - '-I./rootstraps/6.0/usr/include/eina-1/eina/'
  - '-I./rootstraps/6.0/usr/include/emile-1/'
  - '-I./rootstraps/6.0/usr/include/eo-1/'
  - '-I./rootstraps/6.0/usr/include/evas-1/'

  # include glib directories
  - '-I./rootstraps/6.0/usr/include/glib-2.0/'
  - '-I./rootstraps/6.0/usr/lib/glib-2.0/include/'

enums:
  rename:
    '_+(.*)': '$1'
    'vc_state_e': '_vc_state_e'
    'vc_service_state_e': '_vc_service_state_e'
    'vc_result_event_e': '_vc_result_event_e'
    'vc_audio_channel_e': '_vc_audio_channel_e'
    'vc_audio_type_e': '_vc_audio_type_e'
    'vc_feedback_event_e': '_vc_feedback_event_e'
    'vc_tts_utterance_status_e': '_vc_tts_utterance_status_e'

macros:
  exclude:
    - 'VC_COMMAND_TYPE_FOREGROUND'
    - 'VC_COMMAND_TYPE_BACKGROUND'
    - 'VC_RESULT_MESSAGE_NONE'
    - 'VC_RESULT_MESSAGE_ERROR_TOO_LOUD'
