/// {@category 10.0/tizen}
library tizen_interop_10_0.shortcut;

// Copyright 2026 Samsung Electronics Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Dart bindings for Tizen shortcut APIs.
/// {@category 10.0/tizen}
class Tizen100Shortcut {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Tizen100Shortcut(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Tizen100Shortcut.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Adds a shortcut to home, asynchronously.
  ///
  /// **Since Tizen:**
  /// - 2.3
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - If a homescreen does not support this feature, you will get a proper error code.
  /// - Application must check the return value of this function.
  /// - Application must check the return status from the callback function.
  /// - Application should set the callback function to get the result of this request.
  ///
  /// **Parameters:**
  /// - `name` (in): The name of the created shortcut icon
  /// - `type` (in): The type of shortcuts
  /// - `uri` (in): The specific information for delivering to the viewer for creating a shortcut
  /// - `icon` (in): The absolute path of an icon file
  /// - `allow_duplicate` (in): `1` if it accepts the duplicated shortcut, otherwise `0`
  /// - `cb` (in): The address of the callback function that is called when the result comes back from the viewer
  /// - `data` (in): The callback data that is used in the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_RESOURCE_BUSY`: Device or resource busy
  /// - `SHORTCUT_ERROR_NO_SPACE`: There is no space to add a new shortcut
  /// - `SHORTCUT_ERROR_EXIST`: Shortcut is already exist
  /// - `SHORTCUT_ERROR_FAULT`: Unrecoverable error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare the callback function.
  ///
  /// **Postconditions:**
  /// - You have to check the return status from the callback function which is passed by the argument.
  ///
  /// **See also:**
  /// - `result_cb()`
  ///
  /// **Example:**
  ///
  /// ```
  /// #include <stdio.h>
  /// #include <shortcut_manager.h>
  /// static int _result_cb(int ret, int pid, void *data)
  /// {
  /// if (ret < 0)
  /// dlog_print("Failed to add a shortcut: %s\n", perror(ret));
  ///
  /// dlog_print("Processed by the %d\n", pid);
  /// return 0;
  /// }
  ///
  /// static int app_create(void *data)
  /// {
  /// char* data_path = app_get_data_path();
  /// int path_len = strlen(data_path)+10;
  /// char * path = malloc(path_len);
  /// memset(path, 0, path_len);
  /// strncat(path, data_path, path_len);
  /// strncat(path, "Friend.jpg", path_len);
  ///
  /// shortcut_add_to_home("With friends", LAUNCH_BY_URI, "gallery:0000-0000", path, 0, _result_cb, NULL);
  /// free(path);
  ///
  /// return 0;
  /// }
  /// ```
  int shortcut_add_to_home(
    ffi.Pointer<ffi.Char> name,
    int type,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<ffi.Char> icon,
    int allow_duplicate,
    result_cb cb,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _shortcut_add_to_home(
      name,
      type,
      uri,
      icon,
      allow_duplicate,
      cb,
      data,
    );
  }

  late final _shortcut_add_to_homePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Int,
              result_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_add_to_home');
  late final _shortcut_add_to_home = _shortcut_add_to_homePtr.asFunction<
      int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, int, result_cb, ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Adds a widget to home, asynchronously.
  ///
  /// **Since Tizen:**
  /// - 2.4
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - If a homescreen does not support this feature, you will get a proper error code.
  /// - Application must check the return value of this function.
  /// - Application must check the return status from the callback function.
  /// - Application should set the callback function to get the result of this request.
  ///
  /// **Parameters:**
  /// - `name` (in): The name of the created widget which will be shown when the widget is not prepared
  /// - `size` (in): The size of widget
  /// - `widget_id` (in): Widget ID
  /// - `icon` (in): The absolute path of an icon file which will be shown when the widget is not prepared
  /// - `period` (in): The Update period in seconds
  /// - `allow_duplicate` (in): `1` if it accepts the duplicated widget, otherwise `0`
  /// - `cb` (in): The address of the callback function that is called when the result comes back from the viewer
  /// - `data` (in): The callback data that is used in the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_FAULT`: Unrecoverable error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare the callback function.
  ///
  /// **Postconditions:**
  /// - You have to check the return status from the callback function which is passed by the argument.
  ///
  /// **See also:**
  /// - `result_cb()`
  /// - `shortcut_widget_size_e`
  ///
  /// **Example:**
  ///
  /// ```
  /// #include <stdio.h>
  /// #include <shortcut.h>
  /// #include <storage.h>
  ///
  /// #define TIZEN_PATH_MAX 1024
  /// static int _result_cb(int ret, int pid, void *data)
  /// {
  /// if (ret < 0)
  /// dlog_print("Failed to add a widget: %s\n", perror(ret));
  ///
  /// dlog_print("Processed by the %d\n", pid);
  ///
  /// return 0;
  /// }
  ///
  /// static int app_create(void *data)
  /// {
  /// char *image_root = NULL;
  /// char image_path[TIZEN_PATH_MAX] = {0,};
  ///
  /// storage_get_directory(STORAGE_TYPE_INTERNAL, STORAGE_DIRECTORY_IMAGES, &image_root);
  /// snprintf(image_path, TIZEN_PATH_MAX, "%s/alter_icon.png", image_root);
  ///
  /// shortcut_add_to_home_widget("alter_name", WIDGET_SIZE_1x1, "org.tizen.testwidget",
  /// image_path, -1.0f, 0, _result_cb, NULL);
  ///
  /// return 0;
  /// }
  /// ```
  int shortcut_add_to_home_widget(
    ffi.Pointer<ffi.Char> name,
    int size,
    ffi.Pointer<ffi.Char> widget_id,
    ffi.Pointer<ffi.Char> icon,
    double period,
    int allow_duplicate,
    result_cb cb,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _shortcut_add_to_home_widget(
      name,
      size,
      widget_id,
      icon,
      period,
      allow_duplicate,
      cb,
      data,
    );
  }

  late final _shortcut_add_to_home_widgetPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Int32,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Double,
              ffi.Int,
              result_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_add_to_home_widget');
  late final _shortcut_add_to_home_widget =
      _shortcut_add_to_home_widgetPtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              double,
              int,
              result_cb,
              ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Removes a shortcut from home, asynchronously.
  ///
  /// If the callback function registered for a widget, the shortcut deletion is possible.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Parameters:**
  /// - `name` (in): The name of the created shortcut icon
  /// - `cb` (in): The address of the callback function that is called when the result comes back from the viewer
  /// - `user_data` (in): The callback data that is used in the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare the callback function.
  ///
  /// **Postconditions:**
  /// - You have to check the return status from the callback function which is passed by the argument.
  ///
  /// **See also:**
  /// - `result_cb()`
  ///
  /// **Example:**
  ///
  /// ```
  /// #include <shortcut_manager.h>
  ///
  /// int _result_cb(int ret, void *data)
  /// {
  /// if (ret < 0)
  /// dlog_print("Failed to remove a shortcut: %d\n", ret);
  ///
  /// return 0;
  /// }
  ///
  /// {
  /// int result;
  ///
  /// result = shortcut_remove_from_home("shortcut_name", _result_cb, NULL);
  /// if (result != SHORTCUT_ERROR_NONE) {
  /// dlog_print("Failed to remove a shortcut: %d\n", result);
  /// return result;
  /// }
  /// }
  ///
  /// ```
  int shortcut_remove_from_home(
    ffi.Pointer<ffi.Char> name,
    result_cb cb,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _shortcut_remove_from_home(
      name,
      cb,
      user_data,
    );
  }

  late final _shortcut_remove_from_homePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, result_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_remove_from_home');
  late final _shortcut_remove_from_home =
      _shortcut_remove_from_homePtr.asFunction<
          int Function(
              ffi.Pointer<ffi.Char>, result_cb, ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Gets the preset list of shortcut template from the installed package, synchronously.
  ///
  /// **Since Tizen:**
  /// - 2.4
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - If a homescreen does not support this feature, you will get a proper error code.
  /// - Application must check the return value of this function.
  /// - Application must check the return status from the callback function.
  /// - Application should set the callback function to get the result of this request.
  ///
  /// **Parameters:**
  /// - `package_name` (in): The package name
  /// - `list_cb` (in): The callback function to get the shortcut item information
  /// - `data` (in): The callback data that is used in the callback function
  ///
  /// **Returns:**
  /// - `N` Number of items (call count of the callback function), otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_FAULT`: Unrecoverable error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare the callback function.
  ///
  /// **Postconditions:**
  /// - You have to check the return status from the callback function which is passed by the argument.
  int shortcut_get_list(
    ffi.Pointer<ffi.Char> package_name,
    shortcut_list_cb list_cb,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _shortcut_get_list(
      package_name,
      list_cb,
      data,
    );
  }

  late final _shortcut_get_listPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, shortcut_list_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_get_list');
  late final _shortcut_get_list = _shortcut_get_listPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>, shortcut_list_cb, ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Sets a callback function to listen requests from applications.
  ///
  /// **Since Tizen:**
  /// - 2.4
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - Should be used in the homescreen.
  /// - Should check the return value of this function.
  /// - Prospective Clients: Homescreen.
  ///
  /// **Parameters:**
  /// - `request_cb` (in): The callback function pointer that is invoked when add_to_home is requested
  /// - `data` (in): The callback data to deliver to the callback function
  ///
  /// **Returns:**
  /// - `0` on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare a callback function.
  ///
  /// **Postconditions:**
  /// - If a request is sent from the application, the registered callback will be invoked.
  ///
  /// **See also:**
  /// - `shortcut_request_cb()`
  /// - `shortcut_error_e`
  int shortcut_set_request_cb(
    shortcut_request_cb request_cb,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _shortcut_set_request_cb(
      request_cb,
      data,
    );
  }

  late final _shortcut_set_request_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(shortcut_request_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_set_request_cb');
  late final _shortcut_set_request_cb = _shortcut_set_request_cbPtr
      .asFunction<int Function(shortcut_request_cb, ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Unsets a callback for the shortcut request.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - The specific error code can be obtained using the gat_last_result() method. Error codes are described in Exception section.
  ///
  /// **Returns:**
  /// - None
  ///
  /// **Exceptions:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  ///
  /// **See also:**
  /// - `shortcut_set_request_cb()`
  /// - `get_last_result()`
  void shortcut_unset_request_cb() {
    return _shortcut_unset_request_cb();
  }

  late final _shortcut_unset_request_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'shortcut_unset_request_cb');
  late final _shortcut_unset_request_cb =
      _shortcut_unset_request_cbPtr.asFunction<void Function()>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Sets the callback function to listen the remove requests from applications.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - Should be used in the homescreen.
  /// - Should check the return value of this function.
  /// - Prospective Clients: Homescreen.
  ///
  /// **Parameters:**
  /// - `remove_cb` (in): The callback function pointer that is invoked when remove_from_home is requested
  /// - `data` (in): The callback data to deliver to the callback function
  ///
  /// **Returns:**
  /// - 0 on success, otherwise a negative error value
  ///
  /// **Return values:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  /// - `SHORTCUT_ERROR_INVALID_PARAMETER`: Invalid function parameter
  /// - `SHORTCUT_ERROR_OUT_OF_MEMORY`: Out of memory
  /// - `SHORTCUT_ERROR_IO_ERROR`: I/O Error
  /// - `SHORTCUT_ERROR_COMM`: Connection not established or communication problem
  ///
  /// **Preconditions:**
  /// - You have to prepare a callback function.
  ///
  /// **Postconditions:**
  /// - If a request is sent from the application, the registered callback will be invoked.
  ///
  /// **See also:**
  /// - `shortcut_remove_cb()`
  /// - `shortcut_error_e`
  int shortcut_set_remove_cb(
    shortcut_remove_cb remove_cb,
    ffi.Pointer<ffi.Void> data,
  ) {
    return _shortcut_set_remove_cb(
      remove_cb,
      data,
    );
  }

  late final _shortcut_set_remove_cbPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(shortcut_remove_cb,
              ffi.Pointer<ffi.Void>)>>('shortcut_set_remove_cb');
  late final _shortcut_set_remove_cb = _shortcut_set_remove_cbPtr
      .asFunction<int Function(shortcut_remove_cb, ffi.Pointer<ffi.Void>)>();

  /// **Deprecated:** Deprecated since 9.0
  ///
  /// Unsets a callback for the shortcut remove.
  ///
  /// **Since Tizen:**
  /// - 3.0
  ///
  /// **Privilege level:**
  /// - public
  ///
  /// **Privileges:**
  /// - <http://tizen.org/privilege/shortcut>
  ///
  /// **Remarks:**
  /// - The specific error code can be obtained using the gat_last_result() method. Error codes are described in Exception section.
  ///
  /// **Returns:**
  /// - None
  ///
  /// **Exceptions:**
  /// - `SHORTCUT_ERROR_NONE`: Successful
  /// - `SHORTCUT_ERROR_NOT_SUPPORTED`: Not supported
  /// - `SHORTCUT_ERROR_PERMISSION_DENIED`: Permission denied
  ///
  /// **See also:**
  /// - `shortcut_set_remove_cb()`
  /// - `get_last_result()`
  void shortcut_unset_remove_cb() {
    return _shortcut_unset_remove_cb();
  }

  late final _shortcut_unset_remove_cbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          'shortcut_unset_remove_cb');
  late final _shortcut_unset_remove_cb =
      _shortcut_unset_remove_cbPtr.asFunction<void Function()>();
}

/// **Deprecated:** Deprecated since 9.0
///
/// Enumeration for values of shortcut response types.
///
/// **Since Tizen:**
/// - 2.3
/// @nodoc
abstract class shortcut_error_e {
  /// < Successful
  static const int SHORTCUT_ERROR_NONE = 0;

  /// < Invalid function parameter
  static const int SHORTCUT_ERROR_INVALID_PARAMETER = -22;

  /// < Out of memory
  static const int SHORTCUT_ERROR_OUT_OF_MEMORY = -12;

  /// < I/O Error
  static const int SHORTCUT_ERROR_IO_ERROR = -5;

  /// < Permission denied
  static const int SHORTCUT_ERROR_PERMISSION_DENIED = -13;

  /// < Not supported
  static const int SHORTCUT_ERROR_NOT_SUPPORTED = -1073741822;

  /// < Device or resource busy
  static const int SHORTCUT_ERROR_RESOURCE_BUSY = -16;

  /// < There is no space to add a new shortcut
  static const int SHORTCUT_ERROR_NO_SPACE = -18219007;

  /// < Shortcut is already added
  static const int SHORTCUT_ERROR_EXIST = -18219006;

  /// < Unrecoverable error
  static const int SHORTCUT_ERROR_FAULT = -18219004;

  /// < Not exist shortcut(**Since**: 3.0)
  static const int SHORTCUT_ERROR_NOT_EXIST = -18219000;

  /// < Connection not established or communication problem
  static const int SHORTCUT_ERROR_COMM = -18218944;
}

/// **Deprecated:** Deprecated since 9.0
///
/// Enumeration for shortcut types.
///
/// Basically, two types of shortcuts are defined. Every homescreen developer should support these types of shortcuts. Or return, a proper errno to figure out why the application failed to add a shortcut. `LAUNCH_BY_APP` is used for adding a package itself as a shortcut. `LAUNCH_BY_URI` is used for adding a shortcut for "uri" data.
///
/// **Since Tizen:**
/// - 2.3
/// @nodoc
abstract class shortcut_type {
  /// < Launch the application itself
  static const int LAUNCH_BY_APP = 0;

  /// < Launch the application with the given data(URI)
  static const int LAUNCH_BY_URI = 1;
}

/// **Deprecated:** Deprecated since 9.0
///
/// Enumeration for sizes of shortcut widget.
///
/// **Since Tizen:**
/// - 2.4
/// @nodoc
abstract class shortcut_widget_size {
  /// < Type mask for the normal mode widget , don't use this value for specific size.
  static const int WIDGET_SIZE_DEFAULT = 268435456;

  /// < 1x1
  static const int WIDGET_SIZE_1x1 = 268500992;

  /// < 2x1
  static const int WIDGET_SIZE_2x1 = 268566528;

  /// < 2x2
  static const int WIDGET_SIZE_2x2 = 268697600;

  /// < 4x1
  static const int WIDGET_SIZE_4x1 = 268959744;

  /// < 4x2
  static const int WIDGET_SIZE_4x2 = 269484032;

  /// < 4x3
  static const int WIDGET_SIZE_4x3 = 270532608;

  /// < 4x4
  static const int WIDGET_SIZE_4x4 = 272629760;

  /// < 4x5
  static const int WIDGET_SIZE_4x5 = 285212672;

  /// < 4x6
  static const int WIDGET_SIZE_4x6 = 301989888;

  /// < Type mask for the easy mode widget, don't use this value for specific size.
  static const int WIDGET_SIZE_EASY_DEFAULT = 805306368;

  /// < Easy mode 1x1
  static const int WIDGET_SIZE_EASY_1x1 = 805371904;

  /// < Easy mode 3x2
  static const int WIDGET_SIZE_EASY_3x1 = 805437440;

  /// < Easy mode 3x3
  static const int WIDGET_SIZE_EASY_3x3 = 805568512;
}

/// **Deprecated:** Deprecated since 9.0
///
/// Called to receive the result of shortcut_add_to_home().
///
/// **Since Tizen:**
/// - 2.3
///
/// **Parameters:**
/// - `ret` (in): The result value, it could be `0` if it succeeds to add a shortcut, otherwise it returns an errno
/// - `user_data` (in): The callback data
///
/// **Returns:**
/// - int `0` if there is no error, otherwise errno
///
/// **See also:**
/// - `shortcut_add_to_home()`
/// @nodoc
typedef result_cb = ffi.Pointer<ffi.NativeFunction<result_cbFunction>>;
/// @nodoc
typedef result_cbFunction = ffi.Int Function(
    ffi.Int ret, ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartresult_cbFunction = int Function(
    int ret, ffi.Pointer<ffi.Void> user_data);

/// **Deprecated:** Deprecated since 9.0
///
/// Called to receive the result of shortcut_get_list().
///
/// **Since Tizen:**
/// - 2.4
///
/// **Parameters:**
/// - `package_name` (in): The name of package
/// - `icon` (in): The absolute path of an icon file for this shortcut
/// - `name` (in): The name of the created shortcut icon
/// - `extra_key` (in): The user data. A property of shortcut element in manifest file
/// - `extra_data` (in): The user data. A property of shortcut element in manifest file
/// - `user_data` (in): The callback user data
///
/// **Returns:**
/// - SHORTCUT_ERROR_NONE to continue with the next iteration of the loop, other error values to break out of the loop
///
/// **See also:**
/// - `shortcut_get_list()`
/// @nodoc
typedef shortcut_list_cb
    = ffi.Pointer<ffi.NativeFunction<shortcut_list_cbFunction>>;
/// @nodoc
typedef shortcut_list_cbFunction = ffi.Int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> icon,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> extra_key,
    ffi.Pointer<ffi.Char> extra_data,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartshortcut_list_cbFunction = int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> icon,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> extra_key,
    ffi.Pointer<ffi.Char> extra_data,
    ffi.Pointer<ffi.Void> user_data);

/// **Deprecated:** Deprecated since 9.0
///
/// Called to the add_to_home request.
///
/// The homescreen should define a callback as this type and implement the service code for adding a new application shortcut.
///
/// **Since Tizen:**
/// - 2.4
///
/// **Parameters:**
/// - `package_name` (in): The name of package
/// - `name` (in): The name of the created shortcut icon
/// - `type` (in): One of the three defined types
/// - `content_info` (in): The specific information for creating a new shortcut
/// - `icon` (in): The absolute path of an icon file for this shortcut
/// - `pid` (in): The process ID of who request add_to_home
/// - `period` (in): The Update period in seconds
/// - `allow_duplicate` (in): `1` if the shortcut can be duplicated, otherwise a shortcut should exist only once
/// - `user_data` (in): The callback data
///
/// **Returns:**
/// - The result of handling a shortcut creation request This returns `0` if the add_to_home request is handled successfully, otherwise it returns a proper errno
///
/// **See also:**
/// - `shortcut_set_request_cb()`
/// @nodoc
typedef shortcut_request_cb
    = ffi.Pointer<ffi.NativeFunction<shortcut_request_cbFunction>>;
/// @nodoc
typedef shortcut_request_cbFunction = ffi.Int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> name,
    ffi.Int type,
    ffi.Pointer<ffi.Char> content_info,
    ffi.Pointer<ffi.Char> icon,
    ffi.Int pid,
    ffi.Double period,
    ffi.Int allow_duplicate,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartshortcut_request_cbFunction = int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> name,
    int type,
    ffi.Pointer<ffi.Char> content_info,
    ffi.Pointer<ffi.Char> icon,
    int pid,
    double period,
    int allow_duplicate,
    ffi.Pointer<ffi.Void> user_data);

/// **Deprecated:** Deprecated since 9.0
///
/// Called to the shortcut_remove_from_home() request.
///
/// **Since Tizen:**
/// - 3.0
///
/// **Parameters:**
/// - `package_name` (in): The name of package
/// - `name` (in): The name of the created shortcut icon
/// - `sender_pid` (in): The process ID of who request shortcut_remove_from_home()
/// - `user_data` (in): The user data passed from the callback register function
///
/// **Returns:**
/// - The result of handling a shortcut remove request This returns `0` if the remove_from_home request is handled successfully, otherwise it returns a proper errno.
///
/// **See also:**
/// - `shortcut_set_remove_cb()`
/// @nodoc
typedef shortcut_remove_cb
    = ffi.Pointer<ffi.NativeFunction<shortcut_remove_cbFunction>>;
/// @nodoc
typedef shortcut_remove_cbFunction = ffi.Int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> name,
    ffi.Int sender_pid,
    ffi.Pointer<ffi.Void> user_data);
/// @nodoc
typedef Dartshortcut_remove_cbFunction = int Function(
    ffi.Pointer<ffi.Char> package_name,
    ffi.Pointer<ffi.Char> name,
    int sender_pid,
    ffi.Pointer<ffi.Void> user_data);
