name: symgen
description: Symbol mapping generator for shared libraries.
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies: 
  args: ^2.1.1
  file: ^7.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
