name: symgen
description: Symbol mapping generator for shared libraries.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  args: ^2.1.1
  file: ^6.1.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
